### ISSUE TITLE
Get macroblock information

### ISSUE THREAD

**Issue by w495** [mikeboers/PyAV#101]
Is there any way to get macroblock information of frame with pyav?
If it impossible, is there any another way to get motion vector.
I've based on http://www.princeton.edu/~jiasic/cos435/motion_vector.c

**Comment by mikeboers** [comment]
Possible: yes. Currently implemented: no.

I'm personally unfamiliar with these macroblocks and use of motion vectors in the library. I see the motion-related fields of AVFrame getting used by a few codecs, and some motion-specific files (e.g. ``motion_est.c``. Can you tell me any more about the use case, where I might tend to find files with motion vectors, etc.?

**Comment by w495** [comment]
I intend to use them for advanced shot\scene detection as a part of NDVR-problem (Near Duplicate Video Retrieval). More over, MVs (and Optical Flow) are very interesting features for NDVR itself. Surely, I can get it from frames (http://opencv-python-tutroals.readthedocs.org/en/latest/py_tutorials/py_video/py_lucas_kanade/py_lucas_kanade.html), but many videos already have this information.

**Comment by mikeboers** [comment]
[This link](https://trac.ffmpeg.org/wiki/Debug/MacroblocksAndMotionVectors) helped me greatly.

Play a video with macroblock types overlaid:

~~~
ffplay -debug vis_mb_type INPUT
~~~

Play a video with motion vectors overlaid:

~~~
ffplay -flags2 +export_mvs INPUT -vf codecview=mv=pf+bf+bb
~~~

**Comment by mikeboers** [comment]
Looks like this gets into the realm of code deprecated and removed from libav, and then deprecated from ffmpeg. See [this discussion](http://comments.gmane.org/gmane.comp.video.ffmpeg.libav.user/12698).

**Comment by mikeboers** [comment]
PR #106 is about dealing with these deprecated structure members.

**Comment by mikeboers** [comment]
Motion vector support is coming from side data soon™. See #558

**Comment by mfoglio** [comment]
Is it possible to retrieve the motion vectors without decoding the actual frame?
