### ISSUE TITLE
Passing AVOptions to libavcodec

### ISSUE THREAD

**Issue by malc0** [mikeboers/PyAV#102]
The options parameter to open() gets passed to libavformat, but this does not pass through to libavcodec for input decoding.

Making the following change to av/container.pyx (apologies: somewhat old checkout), successfully achieves the equivalent of passing `-err_detect explode' on the ffmpeg command line: could an interface to do this programmatically be added?

```
-        err_check(lib.avformat_find_stream_info(self.proxy.ptr, NULL))
+        dict_to_avdict(&self.options, {'err_detect' : 'explode'})
+        err_check(lib.avformat_find_stream_info(self.proxy.ptr, &self.options))

**Comment by mikeboers** [comment]
I think the ideal thing to do would be to defer any operations that call `avformat_find_stream_info` or `avcodec_open2` until they are necessary, giving the user the chance to do some inspection of what information they do have before determining options.

In the meantime, passing a series of options to the constructor for each steam sounds like a pretty okay idea.

**Comment by mikeboers** [comment]
I'm not 100% on available options: are there any conflicts between container and codec options?

**Comment by malc0** [comment]
I'm not that familiar with the (many) options, but FFmpeg's opt_default() (cmdutils.c) appears to try applying available options to both avcodec and avformat, emitting the "Routing option %s to both codec and muxer layer\n" message when they are accepted by both.  This behaviour would seem to imply a lack of conflict...

**Comment by mikeboers** [comment]
I've (finally) put this in place for both reading and writing.

Cheers!

Mike

**Comment by malc0** [comment]
Sorry for only now getting round for looking at this, but the new code doesn't work for my particular case.  I'm trying to use the `err_detect` option, which applies to both avcodec and avformat.  From the FFmpeg documentation on `avformat_open_input()`'s `options` parameter: 'On return this parameter will be destroyed and replaced with a dict containing options that were not found'.  This means that `self.options` no longer contains `err_detect` when passing it to `avformat_find_stream_info()` (which also filters the returned dictionary); might I suggest passing a throwaway copy of `self.options` in each case?

**Comment by mikeboers** [comment]
Ok. What about the `shared-options` branch?

**Comment by malc0** [comment]
shared-options works well for me, thanks.

**Comment by mikeboers** [comment]
I've done a ton of refactoring, and reimplemented this another way on the master. The `shared-options` branch will not be merged.

Cheers!

**Comment by malc0** [comment]
Wow, quite a set of changes, thanks!  Unfortunately:

```
Traceback (most recent call last):
  File "test_case.py", line 10, in <module>
    video = av.open('/home/stuart/cycling/drop_test.broken.h264', options={ 'err_detect' : 'explode' })
  File "av/container/core.pyx", line 287, in av.container.core.open (src/av/container/core.c:4233)
  File "av/container/core.pyx", line 251, in av.container.core.Container.__cinit__ (src/av/container/core.c:3628)
  File "av/dictionary.pyx", line 12, in av.dictionary._Dictionary.__cinit__ (src/av/dictionary.c:951)
  File "/usr/lib64/python3.4/_collections_abc.py", line 578, in update
    self[key] = other[key]
TypeError: Argument 'key' has incorrect type (expected bytes, got str)
```

Python 3 incompatibility?

**Comment by mikeboers** [comment]
Hooray for Python 3's ability to bite me over and over and...

**Comment by mikeboers** [comment]
There are a few more commits which should fix it.

I'll let you close the issue this time. ;)

**Comment by malc0** [comment]
So current master doesn't compile for me, as my distro libavutil/opt.h (FFmpeg 2.3.5) doesn't define AV_OPT_TYPE_DICT, which one of the other recent commits references.  However, just applying the two Python 3 changes atop 55ccb65 compiles and works just fine, fixing this bug.  Cheers!
