### ISSUE TITLE
feature request: allow reading and writing of YUV images

### ISSUE THREAD

**Issue by mkassner** [mikeboers/PyAV#103]
YUV frames with subsampling use less CPU time to encode and decode. This can be very useful in many cases. (In my case I decode jpegs to YUV and would like to save them as a mpeg4 or similar coded video.)

How much work would it be to allow making frames from YUV420 buffers?

Any pointers would be appreciated!

**Comment by mikeboers** [comment]
The issue I see is that FFmpeg/Libav have only "planar" YUV* pixel formats, such that I don't think you can express a frame in a single buffer. If you have separate Y, U, and V, then you can update the planes individually with a string or something with the buffer protocol (IIRC).

That would be via:

~~~
frame = VideoFrame(1920, 10280, 'yuv420p')
frame.planes[0].update(Y_buffer)
# etc.
~~~

**Comment by mkassner** [comment]
hi,
this works perfectly. Im using YUV422PHowever I don't see the speed increase I expected... 

I thought MPEG-4 is based on YUV but I was wrong. 

Going from here I was wondering wether it is possible to mux raw jpeg frames into a container?
