### ISSUE TITLE
Libraries not found on Ubuntu 14.04

### ISSUE THREAD

**Issue by happycharleswang** [mikeboers/PyAV#105]
Hi!
I was installing  on ubuntu LTS 14.04,         sudo python setup.py install

errors came out : 

~~~
Could not find avformat with ctypes; looked in:
    libavformat.so.54
    /usr/local/lib/libavformat.so.54
Could not find avutil with ctypes; looked in:
    libavutil.so.52
    /usr/local/lib/libavutil.so.52
Could not find avcodec with ctypes; looked in:
    libavcodec.so.54
    /usr/local/lib/libavcodec.so.54
Could not find ['avformat', 'avutil', 'avcodec'] with ctypes.util.find_library
Some libraries can not be found for inspection; aborting!
~~~

I have looked in previous issues post here,  they are similar.
You said to remove some thing and then compile, but that thing is already removed in the current  version, right?
So why this problem is still there.... I am confused... someone please help, will appreciate.

**Comment by mikeboers** [comment]
I'm sorry to say there isn't enough information here for me to help. Can you tell us anything about your library installs, what pkg-config returns, and any investigations into the paths listed in the error?

With a clean Ubuntu 14 the complete build in a virtualenv should be very similar to:

~~~
sudo apt-get install -y python-dev python-virtualenv pkg-config
sudo sudo apt-get install -y \
    libavformat-dev libavcodec-dev libavdevice-dev \
    libavutil-dev libswscale-dev libavresample-dev
git clone git@github.com:mikeboers/PyAV.git
cd PyAV
virtualenv venv
. venv/bin/activate
pip install Cython
python setup.py build
~~~

**Comment by happycharleswang** [comment]
hi Mike, thx for reply!

It seems ctypes was trying to find files in /usr/local/lib
but my files are located in another folder:
/usr/lib/x86_64-linux-gnu/libavcodec.so.54
/usr/lib/x86_64-linux-gnu/libavformat.so.54
/usr/lib/x86_64-linux-gnu/libavutil.so.52

yet
static libs are located in /usr/local/lib
/usr/local/lib/libavcodec.a
/usr/local/lib/libavformat.a
/usr/local/lib/libavutil.a



            pkg-config --libs libavcodec
-pthread -L/usr/local/lib -lavcodec -lavresample -lavutil -lm 
 
             python -c 'import ctypes.util; print ctypes.util.find_library("avcodec")'
libavcodec.so.54

any clue?
thanks!

**Comment by happycharleswang** [comment]
hi Mike, 
that problem is fixed after install some dependencies suggested by your latest update.
sudo apt-get install -y \
libavformat-dev libavcodec-dev libavdevice-dev \
libavutil-dev libswscale-dev libavresample-dev \

Thanks a lot!


But another error comes : 

creating build/temp.linux-x86_64-2.7/src/av
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Iinclude -I/usr/include/python2.7 -Ibuild/temp.linux-x86_64-2.7/include -c src/av/stream.c -o build/temp.linux-x86_64-2.7/src/av/stream.o
In file included from src/av/stream.c:311:0:
include/libswresample/swresample.pyav.h:34:9: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     int swresample_version() { return -1; }
         ^
include/libswresample/swresample.pyav.h:35:17: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     const char* swresample_configuration() { return ""; }
                 ^
include/libswresample/swresample.pyav.h:36:17: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     const char* swresample_license() { return ""; }
                 ^
src/av/stream.c: In function ‘__pyx_f_2av_6stream_6Stream__init’:
src/av/stream.c:2210:16: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
     __pyx_t_10 = __pyx_v_self->_codec_context->codec;
                ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/av/stream.o -L/usr/local/lib -lavcodec -lavdevice -lavformat -lavresample -lavutil -lm -lswscale -o build/lib.linux-x86_64-2.7/av/stream.so
/usr/bin/ld: /usr/local/lib/libavcodec.a(utils.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavcodec.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by happycharleswang** [comment]
I removed these files : 

libavdevice.a  
libavformat.a    
libavutil.a  
libswscale.a  
libavcodec.a
libavfilter.a 
libavresample.a   

from /usr/local/lib, and after that I installed PyAV finally!

Does removing those static files have some side effects?

**Comment by mikeboers** [comment]
Ah yes, we've seen this before. It is a side effect of us inspecting the different libraries in several slightly different ways. In this case the static libs are being inspected for which functions exist, while the dynamic ones are being linked against.

I believe this would be solved by #106 

Thanks for sticking to it! This adds another vote for that change.

**Comment by WisdomTsou** [comment]
Hello happycharleswang,
I have encountered exactly the same problem in your third post, that is, after I install some dependencies as follows:
sudo apt-get install -y \
libavformat-dev libavcodec-dev libavdevice-dev \
libavutil-dev libswscale-dev libavresample-dev \

the same another error comes.....

You said you removed the libavdevice.a, libavformat.a, libavutil.a, libswscale.a, libavcodec.a, libavfilter.a, libavresample.a from /usr/local/lib and then it works, I would like to know how to remove these files such that you can install PyAV successfully finally?

Look forward to your reply!

**Comment by happycharleswang** [comment]
I think I just delete it like this：
sudo rm path/to/the/.a/files
