### ISSUE TITLE
Drop support for Libav

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#110]
Given that Libav is no longer preferred over FFmpeg on any Linux distros, do we care enough to keep supporting it?

This is a conversation that @markreidvfx and I have been having off-line. At this point there is no reason to act, but only to keep this in mind for the next time there is a serious burden put upon us by Libav-vs-FFmpeg.

---

Annoying things we've had to deal with recently (I'm editing this list as we go):
- Libav has no `avfilter_graph_dump`; the functionality was not added.
- Libav has no `AV_ROUND_PASS_MINMAX` in the `AVRounding` enum; I coded around it. (#175)

---

**Edit 2018-05-22:** We're doing this.

- [x] Discuss this history in the docs.
- [x] Remove `avresample` (which will simplify a bunch of `setup.py`).
- [ ] `AV_ROUND_PASS_MINMAX` missing (#175).
- [ ] Look at every symbol looked for in `setup.py`.
- [x] Strip "FFmpeg/Libav" from all casual use in documentation.

**Comment by danielballan** [comment]
I don't have a dog in the FFmpeg vs. Libav question, but I think it's reasonable to pick one to support for the sake of simplified code.

**Comment by mikeboers** [comment]
I've been trying to get filters ready to ship (as they have been in a feature branch for nearly a year now). Libav is now the only thing stopping me. I'm **very** tempted to mark it as deprecated, and disregard test failures on Travis...

Anyone have strong opinions?

**Comment by mikeboers** [comment]
I feel that I ought to mention that digging into why Libav was failing led to me fixing something that simply did not come up during dev with FFmpeg, and would have been a problem.

**Comment by mkassner** [comment]
I dont care about ffmpg vs libav, but simplifying pyav's setup and source would be great.

**Comment by mikeboers** [comment]
Digging this back up. Since it has been a few years since I even bothered with the libav tests, I'm going to finally declare that PyAV only supports FFmpeg. I'll slowly dig out libav-ism's as I come across them.

- [ ] Discuss this history in the docs.
- [ ] Remove `avresample` (which will simplify a bunch of `setup.py`).
- [ ] `AV_ROUND_PASS_MINMAX` missing (#175).
- [ ] Look at every symbol looked for in `setup.py`.
- [ ] Strip "FFmpeg/Libav" from all casual use in documentation.

**Comment by jlaine** [comment]
Done!

**Comment by mikeboers** [comment]
Right you are again. I've opened a new one for the one thing I would like to revisit because of this.
