### ISSUE TITLE
Using a buffer like object when creating a container for writing

### ISSUE THREAD

**Issue by tab1293** [mikeboers/PyAV#111]
Instead of passing the `av.open` function a filename, I am trying to pass it a buffer like object. I thought using io.BytesIO would work in this case but it does not. Here is some example code where I am trying to segment a video file into a 10 second clip. 

```python
import av
import io

input_container = av.open('../bbb.mp4')
input_video_stream = next(s for s in input_container.streams if s.type == "video")

# video_buffer = 'test.mp4'
video_buffer = io.BytesIO()
output_container= av.open(video_buffer, 'w', 'mp4')
output_video_stream = output_container.add_stream('mpeg4', 25)

frame_count = 0

for packet in input_container.demux(input_video_stream):
    for frame in packet.decode():
        frame.pts = None
        output_packets = [output_video_stream.encode(frame)]
        while output_packets[-1]:
            output_packets.append(output_video_stream.encode(None))

        for p in output_packets:
            if p:
                output_container.mux(p)

        frame_count = frame_count + 1
    
    if frame_count == 250:
        break

output_container.close()
```
Here is the traceback output
```
Traceback (most recent call last):
  File "encode.py", line 17, in <module>
    output_packets = [output_video_stream.encode(frame)]
  File "av/video/stream.pyx", line 86, in av.video.stream.VideoStream.encode (src/av/video/stream.c:2665)
    cpdef encode(self, VideoFrame frame=None):
  File "av/video/stream.pyx", line 95, in av.video.stream.VideoStream.encode (src/av/video/stream.c:2061)
    self._weak_container().start_encoding()
  File "av/container.pyx", line 501, in av.container.OutputContainer.start_encoding (src/av/container.c:8040)
    cpdef start_encoding(self):
  File "av/container.pyx", line 525, in av.container.OutputContainer.start_encoding (src/av/container.c:7925)
    err_check(lib.avio_open(&self.proxy.ptr.pb, self.name, lib.AVIO_FLAG_WRITE))
  File "av/utils.pyx", line 32, in av.utils.err_check (src/av/utils.c:1023)
    raise AVError(-res, c_buffer)
av.AVError: [Errno 2] No such file or directory
```
Does anyone know what may be causing this error and if this functionality can even be supported.

*Note that if the comment on the declaration of the video_buffer variable is swapped, the program works correctly.*

Thanks!

**Comment by mikeboers** [comment]
I can confirm the error on a new unit test. Looking into it.

**Comment by tab1293** [comment]
After looking into the error a little more it seems like this problem is occurring because [`avio_open`](https://www.ffmpeg.org/doxygen/2.5/avio_8h.html#a371a670112abc5f3e15bc570da076301) is trying to create an [`AVIOContext`](http://ffmpeg.org/doxygen/trunk/structAVIOContext.html) with a filename. When using the `BytesIO()` object, the name of the container is an empty string so `avio_open` fails because it is expecting a valid filename. Below is lines 523 to 530 in container.pyx where `avio_open` fails
```python
if not self.proxy.ptr.pb:
    if not self.proxy.ptr.oformat.flags & lib.AVFMT_NOFILE:
        err_check(lib.avio_open(&self.proxy.ptr.pb, self.name, lib.AVIO_FLAG_WRITE))
    dict_to_avdict(&self.proxy.ptr.metadata, self.metadata, clear=True)
    err_check(lib.avformat_write_header(
        self.proxy.ptr, 
        &self.options if self.options else NULL
    ))
```
 I don't have much experience using Cython, but I think a solution may be to use [avio_alloc_context](https://www.ffmpeg.org/doxygen/2.5/avio_8h.html#a853f5149136a27ffba3207d8520172a5) instead of avio_open. What do you think?

**Comment by mikeboers** [comment]
My tests are now passing here; please try the `pyio` branch.

**Comment by mikeboers** [comment]
This has been merged into master.

Cheers!
