### ISSUE TITLE
Segfault on `VideoStream.encode()`

### ISSUE THREAD

**Issue by vidartf** [mikeboers/PyAV#118]
The following basic script based on one of the examples, segfaults for me (as indicated by comment).
System info: Windows 7, latest official ffmpeg builds for windows, PyAV master compiled using both MSVC and MinGW (same behaviour).

I've tried varying format, codec, file name/extension, no difference.

```python
import av
import numpy as np

w, h = 100, 100

data = np.zeros((10, w, h, 3), dtype=np.uint8)

output = av.open('test.mp4', 'w')
try:
    stream = output.add_stream('h264', 24)
    stream.height = h
    stream.width = w
    stream.pix_fmt = "yuv420p"

    for i in xrange(10):
        img = data[i, ...]
        img = np.ascontiguousarray(img)
        frame = av.VideoFrame.from_ndarray(img)
        packet = stream.encode(frame)      # <----  This line segfaults.
        output.mux(packet)
        packet = stream.encode(frame)
finally:
    output.close()

```

**Comment by mikeboers** [comment]
I was not able to replicate this segfault. The script does need to be modified in order to work (the codec doesn't start producing frames after only 10 and needs to be flushed), but when it does I get a small black video.

If you can dig out a debugger that would be great. Even without debugging symbols in the underlying library, we can learn a ton just from what Cython line is causing it.

**Comment by vidartf** [comment]
So, event the first test fails with a segfault:
```python
container = av.open(asset('1KHz.wav'))
```

I'm not completely up and running with debugging, but I'm getting this output now:
```
  File "video_test.py", line 1, in <module>
    import av
  File "c:\github\pyav\av\__init__.py", line 15, in <module>
    from av.audio.fifo import AudioFifo
  File "av\audio\format.pxd", line 4, in init av.audio.fifo (..\src\av\audio\fif
o.c:2781)
    cdef class AudioFormat(object):
AttributeError: 'module' object has no attribute 'AudioFormat'
```

Hopefully this can be of assistance?

**Comment by vidartf** [comment]
If I comment out the relevant lines in `av/__init__.py` I continue on to get this:
```
  File "video_test.py", line 3, in <module>
    import av
  File "c:\github\pyav\av\__init__.py", line 17, in <module>
    from av.audio.frame import AudioFrame
  File "av\container\core.pxd", line 10, in init av.frame (..\src\av\frame.c:261
5)
    cdef class ContainerProxy(object):
  File "c:\github\pyav\av\container\__init__.py", line 1, in <module>
    from .core import Container, open
  File "av\packet.pxd", line 6, in init av.container.core (..\src\av\container\c
ore.c:5044)
    cdef class Packet(object):
  File "av\frame.pxd", line 6, in init av.packet (..\src\av\packet.c:2351)
    cdef class Frame(object):
  File "av\stream.pxd", line 10, in init av.frame (..\src\av\frame.c:2618)
    cdef class Stream(object):
  File "av\audio\stream.pyx", line 1, in init av.audio.stream (..\src\av\audio\s
tream.c:2853)
    from av.audio.format cimport get_audio_format
AttributeError: 'module' object has no attribute 'Stream'
```

**Comment by vidartf** [comment]
Alright, so those previous traces were a red herring due to the build setup. I've fixed that now, and now I'm getting the exception here:

logging.c:1689: 
      free(__pyx_v_req);
Unhandled exception at 0x77cdffc2 (ntdll.dll) in python.exe: 0xC0000374: A heap has been corrupted.

**Comment by vidartf** [comment]
PYX Context:
```
      /* "av\logging.pyx":140
 *     finally:
 *         free(req.message)
 *         free(req)             # <<<<<<<<<<<<<<
 * 
 *     return 0
 */
```

**Comment by vidartf** [comment]
I was able to extract `req` as well (or rather, its source `arg`):
```
{level=48, item_name="libx264", message="using mv_range_thread = 24" }
```

**Comment by vidartf** [comment]
It was this diff that introduced the segfault:
```
logging.pyx:
-    cdef int cn = snprintf(NULL, 0, format, args)
-    req.message = <char*>malloc(cn+1)
-    snprintf(req.message, cn+1, format, args)
+    # Use the library's formatting functions (which are cross platform).
+    cdef lib.AVBPrint buf
+    lib.av_bprint_init(&buf, 0, 65536);
+    lib.av_vbprintf(&buf, format, args);
+    lib.av_bprint_finalize(&buf, &req.message);
```

**Comment by vidartf** [comment]
It can be fixed by replacing `free(req.message)` with `lib.av_freep(&req.message)`.

**Comment by mikeboers** [comment]
What was it about the build that was causing the first errors (for curiosity)?

**Comment by vidartf** [comment]
Some weird interaction between cython and the linker setup. It kind of just disappeared, so I wasn't able to diagnose it fully.

**Comment by mikeboers** [comment]
I'm having a hard time wrapping my mind around why that free is a problem, and why it would be introduced by the change to using `AVBPrint` buffers (and also not on the platforms I'm testing).

**Comment by vidartf** [comment]
It might just be an error in the way the OS tracks heap corruption, but either way `av_freep` is the corresponding free routine for the allocation that happens in `AVBPrint`.

Here are the raw routines used my libav:
```
void av_free(void *ptr)
{
#if CONFIG_MEMALIGN_HACK
    if (ptr) {
        int v= ((char *)ptr)[-1];
        av_assert0(v>0 && v<=ALIGN);
        free((char *)ptr - v);
    }
#elif HAVE_ALIGNED_MALLOC
    _aligned_free(ptr);
#else
    free(ptr);
#endif
}

void av_freep(void *arg)
{
    void *val;

    memcpy(&val, arg, sizeof(val));
    memcpy(arg, &(void *){ NULL }, sizeof(val));
    av_free(val);
}
```
I'm guessing it has something to do with those memory alignment things.

**Comment by mikeboers** [comment]
I'll buy that explanation. Thanks!

I'll check that return code, and cherry-pick 7af141b ;)

(Also, that is a LOT of work towards AppVeyor!! I'm excited.)

**Comment by vidartf** [comment]
AppVeyor is basically up and running now. Currently builds succeed on 2.7 (I'm not sure which are supposed to be working): https://ci.appveyor.com/project/vidartf/pyav/build/1.0.42

**Comment by mikeboers** [comment]
Seems like Appveyor is finding Python3 issues, and Travis has an old version of FFmpeg.

The issue on Appveyor is in:

~~~
  File "setup.py", line 116, in dump_config
    print('Python:', sys.version.encode('string-escape'))
LookupError: unknown encoding: string-escape
~~~

I just pushed an attempted fix in 9c301a1 (along with your segfault fixing commit).

**Comment by mikeboers** [comment]
Let me know when you are happy with the Appveyor stuff, and I'll start slogging through merging it. Hopefully the majority of it can be squashed. =P

**Comment by vidartf** [comment]
Fixing the `string-escape` is good, but a major issue in the 3.x builds is the config:
```
running build_ext
running reflect
running config
looking for avformat_open_input... missing
looking for pyav_function_should_not_exist... missing
looking for av_calloc... missing
looking for av_frame_get_best_effort_timestamp... missing
looking for avformat_alloc_output_context2... missing
looking for avformat_close_input... missing
looking for AVStream.index... found
looking for PyAV.struct_should_not_exist... missing
looking for AVFrame.mb_type... found
 
We didn't find `avformat_open_input` in the libraries.
We look for it only as a sanity check to make sure the build
process is working as expected. It is not, so we must abort.
```
Not sure why this happens though...

**Comment by vidartf** [comment]
But yeah, from my perspective I'm done, as I have a working interface to libav from Python now :)

**Comment by mikeboers** [comment]
Python 2 being tested on Windows is already a huge deal for me. Amazing!
