### ISSUE TITLE
Python 3 on Windows

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#119]
Copying from #118 (which is not yet merged into master anyways):

```
running build_ext
running reflect
running config
looking for avformat_open_input... missing
looking for pyav_function_should_not_exist... missing
looking for av_calloc... missing
looking for av_frame_get_best_effort_timestamp... missing
looking for avformat_alloc_output_context2... missing
looking for avformat_close_input... missing
looking for AVStream.index... found
looking for PyAV.struct_should_not_exist... missing
looking for AVFrame.mb_type... found

We didn't find `avformat_open_input` in the libraries.
We look for it only as a sanity check to make sure the build
process is working as expected. It is not, so we must abort.
```

We should instrument the sanity checks to output everything captured from the build so that we have a chance of debugging this.

**Comment by vidartf** [comment]
> We should instrument the sanity checks to output everything captured from the build so that we have a chance of debugging this.

Just change [this line in `setup.py`](https://github.com/mikeboers/PyAV/blob/master/setup.py#L195) and you'll get all the compiler/linker output from config.

**Comment by jlaine** [comment]
As the appveyor builds against Python 3 seem to work fine I'm tempted to say this is fixed?

**Comment by mikeboers** [comment]
Sure!
