### ISSUE TITLE
Use pre-compiled library and dependencies on Travis

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#121]
Similar to #88 which uses Conda, which would be okay if we can get it to work with both FFmpeg and Libav, multiple OSes (since I have OS X support on Travis for this repo), and ideally multiple versions of the libraries.

**Comment by danielballan** [comment]
I'm game to help build this out. The conda recipe for works for Linux and OSX currently. It looks like we could get it working on Windows if we wanted to, given the recent heroic efforts toward a straightforward Windows build.

I have no experience with LibAV. But if you have a bash script for building it, I can probably make a conda recipe in short order.

**Comment by mikeboers** [comment]
That would be amazing!

The build for Libav is identical to FFmpeg (except tarball/directory names).

Right now on Travis we have fixed (and very old) versions of the libraries. I would love to be able to test against multiple, to see how we do with current and minimally supported versions.

At this moment I'm trying to migrate to Travis' new container system, in which we can also cache the dependencies after the first build.

**Comment by mikeboers** [comment]
I seem to have the caching working quite well. I've expanded to 3 versions of ffmpeg, and 2 of libav.

**Comment by mikeboers** [comment]
I'm totally satisfied with where I have landed with this.

**Comment by danielballan** [comment]
Cool. Nice work.
