### ISSUE TITLE
Mac OS X installation problem

### ISSUE THREAD

**Issue by cmmoenne** [mikeboers/PyAV#122]
When installing PyAV in Mac OS X 10.9 the cythonize step is ignored (around line 562 in setup.py) without creating the C source files (the *ext.sources* list consists in a list of filenames with extension .c and not .pyx for each *ext*). At compiling time, the compiler fails to find av/_core.c and the process stops.

Any ideas to make a a successful compilation/installation?

**Comment by mikeboers** [comment]
We've seen that happen with old versions of setuptools. Can you upgrade that and try again?

**Comment by markreidvfx** [comment]
the default version of setuptools for mavericks yosemite is 
pip show setuptools
Name: setuptools
Version: 0.6c12dev-r88846
Location: /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python

**Comment by cmmoenne** [comment]
(sorry for the late reply... it's a lab computer so I can't use it at any time)

pip show setuptools
Name: setuptools
Version: 0.6c12dev-r88846
Location: /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python

and when upgraded to setuptools-18.2 the problem disappears. Thank you for your help :-)

**Comment by mikeboers** [comment]
Thanks! I'm going to resubmit this as something we should warn about.
