### ISSUE TITLE
No 0.2.4 tag?

### ISSUE THREAD

**Issue by ksze** [mikeboers/PyAV#126]
Version 0.2.4 is on PyPI, but it's doesn't seem to be tagged here. Can you tag it?

**Comment by mikeboers** [comment]
Here you go -> https://github.com/mikeboers/PyAV/releases/tag/v0.2.4

**Comment by ksze** [comment]
Thanks. :)
That was quick. :+1:

**Comment by mikeboers** [comment]
It was tagged in my repo, and just needed a `git push --tags`. =]
