### ISSUE TITLE
Refcount/Memory issues

### ISSUE THREAD

**Issue by mkassner** [mikeboers/PyAV#128]
I m not versed with Pyhton refcounting and memory management but I have experienced some problems with av.VideoFrame

In my application I save numpy arrays to a video file using pyav. For this I call:

`frame  = av.VideoFrame(input_frame.width,input_frame.height,'bgr24')` to create a frame for each image.

Since this is done inside a fn that is called continuously, I expect frame to go out of scope and be garbage collected. On MacOS this is the case and I don't have any trouble. 

However on Linux I quickly run out of memory (I can watch the python process growing in memory use until the system hangs.)

A simple workaround is creating a single instance of `frame` attaching it to `self.` and re-using it by updating the planes. 

Any ideas why this happens when I make new frames?

**Comment by mikeboers** [comment]
This and #61 seem to indicate that it is in the `Frame` (and likely `VideoFrame`) class. It is also helpful that you identify it as a problem on Linux, since I would have started tackling this on a Mac.

Step 1 is to figure out a minimal test that leaks, and go from there.

**Comment by mkassner** [comment]
this makes my linux machine crash or stop the script with signal -9 within 20 seconds.

```python
import av
import cv2

cap = cv2.VideoCapture('/home/mkassner/Desktop/003/world.mp4')
for x in xrange(7000):
    s_img = cap.read()
    for f in xrange(100):
        foo = av.VideoFrame(1280,720)
```

the same script with the same version of PyAV behaves nicely on mac.

**Comment by mikeboers** [comment]
Excellent. Thanks!

**Comment by mkassner** [comment]
Any insights? Where you able to recreate the bug?

**Comment by mikeboers** [comment]
I must admit I have not tried yet as it has been a particularly stuffed week.

It seems the `av` and `cv2` parts of your script are isolated, so I tried:

~~~
import av

for x in xrange(100):
    print x
    for f in xrange(100000):
        foo = av.VideoFrame(1280,720)
~~~

This does not crash on my local Fedora 20 machines, and looking at the memory usage it doesn't appear to leak.

I was hoping I would get some time today to really dig into this, but I think that opportunity has been taken from me. Can you confirm my tinier script crashes for you, and let me know the OS?

**Comment by mkassner** [comment]
No. It only crashes in this combo. This is the most minimal example was
able to create.

I m guessing that's it does not matter how, but you need to keep the CPU
busy. Possibly also create a second thread? I think that's was
cv2.videocapture is doing.

**Comment by mikeboers** [comment]
Heh. Amazing. I'll try to get something going with OpenCV too later.

**Comment by mikeboers** [comment]
I wonder if it has to do with [this](https://ffmpeg.org/doxygen/2.8/structAVCodecContext.html#ab16d1e0c729a7b63d918d5ec027ba064
), which is something I need to deal with in general.

**Comment by ksze** [comment]
I also get memory leak like this on my Debian 8.1 server.

    import av
    ffv1_video = av.open(some_ffv1_video, 'r')
    for packet in ffv1_video.demux():
        for frame in packet.decode():
            pass

Interestingly, the severity of the leak seems to be different depending on how the video is encoded. I have the same gray16le video encoded in two ways:
- FFV1 level 1, default gop
- FFV1 level 3, coder 1, large context, gop 300, 30 slices

I seem to get memory leak in both cases, but it's a lot more severe with FFV1 level 3: more than 7 GiB in about 30 seconds, using about 400% CPU. Whereas with FFV1 level 1, the memory usage grew very slowly by about 5 MiB after 30 seconds,using about 200% CPU.

**Comment by mikeboers** [comment]
My instinct says that this isn't a library ref-count problem, since PyAV is erring on the side of being too destructive. Once I've got an isolated/reproducible sample/script, then I can instrument the ref-counts to verify.

**Comment by mikeboers** [comment]
Just messing around with some files I have sitting around with:

```
ffmpeg -i input.mp4 -c:v ffv1 -level 3 -coder 1 -context 1 -g 1 ~/Desktop/ffv1-level3.mkv
```
The first one results in a memory graph of:

![screen shot 2016-03-04 at 6 36 29 pm](https://cloud.githubusercontent.com/assets/130470/13545178/1645b74a-e238-11e5-84be-1fe38386e6b4.png)

The second one looks like:

![screen shot 2016-03-04 at 6 36 35 pm](https://cloud.githubusercontent.com/assets/130470/13545177/16315c6e-e238-11e5-8413-3a21ecd463aa.png)

The first appears to do periodic garbage collection, while the second does not, and is leaking 4kB on every frame/packet. This is on my Mac.

**Comment by ksze** [comment]
What do you mean by "first" and "second"? You have only pasted one command line.

**Comment by mikeboers** [comment]
I used the same command to encode two files I have sitting around. I didn't show the differences, as it is just file names.

**Comment by mikeboers** [comment]
I also wasn't at all clear what I am doing. I am using `ffmpeg` (pasted above) to prep the files, and then PyAV to decode them, and outputting a CSV of memory usage that I'm graphing. So these plots are PyAV simply reading the files.

**Comment by mikeboers** [comment]
I've gotten PyAV building against FFmpeg 3.0 on Debian 8 (in a virtual machine on my Mac).

This is the memory usage across a sample video on my Mac:

![screen shot 2016-03-04 at 8 24 08 pm](https://cloud.githubusercontent.com/assets/130470/13545642/778bbc34-e247-11e5-87d0-9a31cd98626a.png)

And this is Debian 8:

![screen shot 2016-03-04 at 8 26 54 pm](https://cloud.githubusercontent.com/assets/130470/13545645/8321d81c-e247-11e5-9cbf-8b1c46bac60a.png)

Debian does 3x better WRT memory usage, and while they don't look amazing, they don't seem drastically leaky.

Is it at all possible for someone to provide a sample file (and ideally script) which leak?

**Comment by mikeboers** [comment]
I've done a better job replicating your settings with:

```
$ ffmpeg -i input.mp4  -c:v ffv1 -level 3 -coder 1 -context 1 -slices 30 -context 1 -g 300 ~/Desktop/ffv1-level3.4.mkv
```
It takes up ~250MB on my Mac now, but not very leaky looking.

**Comment by mikeboers** [comment]
At this point, I'm on Debian 8, using FFmpeg 2.5.3 (as you said), against the PyAV commit you said, with the settings on a test video match (as far as I can tell) what you were saying above. This is the memory usage across a ~8m file:

![screen shot 2016-03-04 at 8 51 12 pm](https://cloud.githubusercontent.com/assets/130470/13545760/dbf19948-e24a-11e5-9800-56f1b0d4c79d.png)

This may not be perfect, but it is certainly not 7GB of usage.

I think I need a sample from you.

**Comment by ksze** [comment]
I don't have my computer with me, but I'll try to reproduce the problem again and give you a script. I forget how many frames it took to get that 7GB memory usage.

**Comment by ksze** [comment]
I just reproduced the problem.

Can you try this script on your Debian 8 machine?

```
#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-

# Python standard library
import resource
import subprocess

# PyAV
import av

def make_ffv1_level1(ffmpeg_bin_path, number_of_frames):
    print 'Making the initial ffv1 level 1 video (ffv1_level1.nut).'
    ffmpeg_args = [
        ffmpeg_bin_path,
        '-loglevel', 'quiet', '-hide_banner',
        '-f', 'rawvideo', '-s:v', '512x424', '-pix_fmt', 'gray16le', '-i', 'pipe:0',
        '-r', '30', '-c:v', 'ffv1', '-level', '1', '-y', 'ffv1_level1.nut',
    ]

    ffmpeg = subprocess.Popen(ffmpeg_args, stdin=subprocess.PIPE)

    frame = chr(0) * 2 * 512 * 424  # Just a gray16le frame filled with zeroes

    with ffmpeg.stdin:
        # Write 10000 frames
        for i in xrange(number_of_frames):
            ffmpeg.stdin.write(frame)

    ffmpeg.wait()

def transcode_level1_to_level3(ffmpeg_bin_path):
    print 'Now transcoding it to level 3 (ffv1_level3.nut).'
    ffmpeg_args = [
        ffmpeg_bin_path,
        '-loglevel', 'quiet', '-hide_banner',
        '-i', 'ffv1_level1.nut',
        '-c:v', 'ffv1', '-level', '3', '-coder', '1', '-context', '1', '-slices', '30', '-g', '300', '-y', 'ffv1_level3.nut',
    ]

    ffmpeg = subprocess.Popen(ffmpeg_args)
    ffmpeg.wait()

def decode_using_pyav():
    print 'Decoding using PyAV.'
    ffv1_video = av.open('ffv1_level3.nut', 'r')

    count = 0
    for packet in ffv1_video.demux():
        for frame in packet.decode():
            count += 1

            if count % 1000 == 0:
                # Print the resident memory usage. This is in kibibytes, I believe.
                # Or you can just watch the memory usage in `top`.
                print resource.getrusage(resource.RUSAGE_SELF).ru_maxrss

if __name__ == '__main__':
    # Make sure this is ffmpeg n2.5.3
    ffmpeg_bin_path = '/usr/local/bin/ffmpeg'

    # Make this number sufficiently large and you'll hit swap (and hate yourself).
    # e.g. 100000, which is still less than an hour of video at 30 fps.
    number_of_frames = 10000

    make_ffv1_level1(ffmpeg_bin_path, number_of_frames)

    transcode_level1_to_level3(ffmpeg_bin_path)

    decode_using_pyav()
```

**Comment by ksze** [comment]
To understand what the script was doing:

It appears that ffmpeg can be quirky when encoding or transcoding to ffv1 level 3.

If you take that `ffv1_level3.nut` file and just open it with the `ffmpeg` command in the terminal, you'll see this:

```
$ ffmpeg -i ffv1_level3.nut
ffmpeg version n2.5.3 Copyright (c) 2000-2015 the FFmpeg developers
  built on Jun 10 2015 19:04:24 with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: --prefix=/usr/local/ --extra-cflags=-I/home/toolchain/ffmpeg_build/include --extra-ldflags=-L/home/toolchain/ffmpeg_build/lib --bindir=/usr/local/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-shared --enable-pic
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 13.100 / 56. 13.100
  libavformat    56. 15.102 / 56. 15.102
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  2.103 /  5.  2.103
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[ffv1 @ 0x1b7fec0] ignoring invalid SAR: 0/0
    Last message repeated 29 times
Input #0, nut, from 'ffv1_level3.nut':
  Metadata:
    encoder         : Lavf56.15.102
  Duration: 00:06:39.97, start: 0.000000, bitrate: 194 kb/s
    Stream #0:0: Video: ffv1 (FFV1 / 0x31564646), gray16le, 512x424, 30 fps, 30 tbr, 61440 tbn, 61440 tbc
    Metadata:
      encoder         : Lavc56.13.100 ffv1
At least one output file must be specified
```
Notice the line that says `[ffv1 @ 0x1b7fec0] ignoring invalid SAR: 0/0`. That's the quirk I'm talking about.
And so when PyAV opens the ffv1 level 3 video, it sees that it's quirky and doesn't automatically free the frame

**Comment by mikeboers** [comment]
Thanks for the script! Unfortunately, it maxes out at `28532`here.

Can you send me the output of `python setup.py doctor` and `python -m av --version` so I can make sure I'm matching your FFmpeg build as close as possible?

Are you building it yourself, or getting it from the package manager?

**Comment by mikeboers** [comment]
Just tried it with the standard `apt` sources, and it immediately plateaus at ~35k. What sort of behavior should I be seeing?

**Comment by ksze** [comment]
Here it is:
```
$ python setup.py doctor
running doctor
running config
running reflect
looking for avformat_open_input... found
looking for pyav_function_should_not_exist... missing
looking for av_calloc... found
looking for av_frame_get_best_effort_timestamp... found
looking for avformat_alloc_output_context2... found
looking for avformat_close_input... found
looking for AVStream.index... found
looking for PyAV.struct_should_not_exist... missing
looking for AVFrame.mb_type... found

PyAV: 0.2.4 v0.2.4-86-g2ba8cf7
Python: 2.7.9 (default, Mar  1 2015, 12:57:24) \n[GCC 4.9.2]
platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
extension_extra:
        libraries: ['avcodec', 'avdevice', 'avformat', 'avutil', 'swresample', 'swscale']
        library_dirs: ['/usr/local//lib']
        include_dirs: ['/usr/local//include', 'include', '/usr/include/python2.7']
config_macros:
        PYAV_VERSION=0.2.4
        PYAV_VERSION_STR="0.2.4"
        PYAV_COMMIT_STR="v0.2.4-86-g2ba8cf7"
        PYAV_HAVE_LIBSWRESAMPLE=1
        PYAV_HAVE_AV_CALLOC=1
        PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=1
        PYAV_HAVE_AVFORMAT_ALLOC_OUTPUT_CONTEXT2=1
        PYAV_HAVE_AVFORMAT_CLOSE_INPUT=1
        PYAV_HAVE_AVFRAME__MB_TYPE=1
```
and
```
$ python -m av --version
PyAV v0.2.4
git origin: git@github.com:mikeboers/PyAV
git commit: v0.2.4-86-g2ba8cf7
library configuration: --prefix=/usr/local/ --extra-cflags=-I/home/toolchain/ffmpeg_build/include --extra-ldflags=-L/home/toolchain/ffmpeg_build/lib --bindir=/usr/local/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-shared --enable-pic
library license: nonfree and unredistributable
libavcodec     56. 13.100
libavdevice    56.  3.100
libavformat    56. 15.102
libavutil      54. 15.100
libswresample   1.  1.100
libswscale      3.  1.101
```
We built ffmpeg ourselves, based on the recipe at https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu.

Did you at least get a quirky FFV1 level 3 video using my script (i.e. with the "ignoring invalid SAR: 0/0" lines)?

**Comment by mikeboers** [comment]
I did get a series of:

```
[ffv1 @ 0x2527b20] ignoring invalid SAR: 0/0
```

There are a few directions that we could go:

1. I keep trying to match your build (your config flags are different than mine, and I can follow the recipe);
2. you send me an archive of your build (but my gut says that it still wont replicate);
3. you try to match my build:

  ```
  $ . scripts/activate ffmpeg 2.5.3
  $ ./scripts/build-deps
  $ export PATH/LD_LIBRARY_PATH/PKG_CONFIG_PATH to venvs/$xxx/vendor/ffmpeg-2.5.3/$yyy
  ```

4. you provide me with SSH access to a server that has this problem;
5. we figure out a base recipe for demo-ing the problem on a virtual machine or cloud machine.

**Comment by ksze** [comment]
Number 1 and 3 are probably the best things to try now.

For number 3, can you paste me *your* output of `python setup.py doctor` and `python -m av --version` as well? I would like to see what's different between our config flags.

**Comment by mikeboers** [comment]
My `python setup.py doctor` is identical:

```
vagrant@debian-jessie:/vagrant$ python setup.py doctor
running doctor
running config
running reflect
looking for avformat_open_input... found
looking for pyav_function_should_not_exist... missing
looking for av_calloc... found
looking for av_frame_get_best_effort_timestamp... found
looking for avformat_alloc_output_context2... found
looking for avformat_close_input... found
looking for AVStream.index... found
looking for PyAV.struct_should_not_exist... missing
looking for AVFrame.mb_type... found

PyAV: 0.2.4 v0.2.4-86-g2ba8cf7
Python: 2.7.9 (default, Mar  1 2015, 12:57:24) \n[GCC 4.9.2]
platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
extension_extra:
	libraries: ['avcodec', 'avdevice', 'avformat', 'avutil', 'swresample', 'swscale']
	library_dirs: ['/usr/local//lib']
	include_dirs: ['/usr/local//include', 'include', '/usr/include/python2.7']
config_macros:
	PYAV_VERSION=0.2.4
	PYAV_VERSION_STR="0.2.4"
	PYAV_COMMIT_STR="v0.2.4-86-g2ba8cf7"
	PYAV_HAVE_LIBSWRESAMPLE=1
	PYAV_HAVE_AV_CALLOC=1
	PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=1
	PYAV_HAVE_AVFORMAT_ALLOC_OUTPUT_CONTEXT2=1
	PYAV_HAVE_AVFORMAT_CLOSE_INPUT=1
	PYAV_HAVE_AVFRAME__MB_TYPE=1
```
My config flags are nearly the same (I haven't manually built every dependency yet):

```
vagrant@debian-jessie:/vagrant$ python -m av --version
PyAV v0.2.4
git origin: git@github.com:mikeboers/PyAV
git commit: v0.2.4-86-g2ba8cf7
library configuration: --prefix=/usr/local/ --enable-gpl --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-shared --enable-pic
library license: nonfree and unredistributable
libavcodec     56. 13.100
libavdevice    56.  3.100
libavformat    56. 15.102
libavutil      54. 15.100
libswresample   1.  1.100
libswscale      3.  1.101
```

The leaking script hits `35228`, and doesn't budge.

I guess I'll try matching the build exactly... *shrugs*

**Comment by mkassner** [comment]
We are still seeing issues with PyAV and memory. This time with reading media. Interestingly ONLY Linux never MacOS (here PyAV/Cython/ffmpeg are super well behaved.)

this is really annoying. I ll try to investigate a bit more.

**Comment by mikeboers** [comment]
As soon as I'd be able to replicate these problems I'm sure I can fix them.

Would people be open to me spinning up Digital Ocean droplets as close to your platforms as possible, and then you building everything on them exactly as you do?

**Comment by mkassner** [comment]
I have a vm I can send you...

**Comment by mikeboers** [comment]
That would certainly do!

**Comment by mikeboers** [comment]
@ksze, if you have a VM that you can share, could you upload it to <https://www.dropbox.com/request/3Wtr9LB4rUZhIV73CZDu>? I'm afraid I have not been able to make any headway replicating either of the problems here.

I'm also happy to take a look at a build on anyone's server ([SSH keys here](https://gist.github.com/mikeboers/6adcbc09a882bf6c66bf66dd515072d9)), or spin up a VPS for us to work on together.

**Comment by ksze** [comment]
I think we have a script to build our toolchain (which includes ffmpeg and PyAV) on Debian 8. I'll see if I can whip up a Debian VirtualBox and reproduce the problem there.

**Comment by mikeboers** [comment]
Amazingly enough, I can't reproduce either problem with @mkassner's VM. :unamused:

I am still on a Mac, and using VirtualBox instead of VMWare, but I can't imagine those cause differences (do they?).

**Comment by mikeboers** [comment]
I take it back! Once I gave the machine a second processor, @mkassner's VM leaks and crashes with @ksze's test at ~1.8GB. Huzzah! :grinning:

**Comment by ksze** [comment]
ah, so it has to do with multiprocessing! nice!

**Comment by mkassner** [comment]
thats great to hear. Any idea on why this happens?

**Comment by mikeboers** [comment]
Not really. I'm going to try to throw Valgrind at it, but I don't think that will be very helpful (for a few reasons, including Python, Cython, and my inexperience). I've been thinking of instrumenting key places with memory inspection, so I can get a report akin to PDBs. Then, I can run exactly the same tests in my VM only changing the number of processors, and see where the behavior changes. I figure that will isolate it to a single library function which is supposed to deallocate, but does not when there are multiple CPUs.

**Comment by mikeboers** [comment]
I've build the current master against FFmpeg 2.7 on Ubuntu 14 now as well, and reproducing the issue seems to only be upon the VM having multiple CPUs (for me). That is promising.

**Comment by mikeboers** [comment]
Another clean build with FFmpeg 3.0 is consistent with above. So, it isn't a problem with the library that was fixed.

**Comment by mikeboers** [comment]
At this point I am fairly certain that the excess memory is being allocated in `avcodec_decode_video2`.

Also, the "invalid SAR" is referring to the Sample Aspect Ratio, and I don't think it could be causing problems. Could, but I don't think so.

**Comment by mikeboers** [comment]
Not a solution, but a workaround: setting `thread_count` on a stream to `1` stops the leak on my test case (as this effectively stops multi-threaded decoding)!!

**Comment by mikeboers** [comment]
Also putting an occasional `time.sleep(0.001)` mitigates the problem, although not nearly to the same degree as not threading.

**Comment by mikeboers** [comment]
Oddly enough, the CentOS 7 machine I'm testing right now does *not* exhibit this behaviour. It is a real  machine with many more CPUs than my test VMs. It does take up a pile more RAM to run with threads (because it tends to buffer `num_cpu + 1` frames, and all those objects are rather expensive for 1080p), but it isn't leaking like a sieve.

**Comment by mikeboers** [comment]
I think I take it back (as I was also playing with the Python GC at the same time); it does seem to leak when threaded, and not when not threaded, however the leak appears to be much less pronounced.

My strongest two ideas are:
1. there is a bug in ffmpeg;
2. turning on threading activates refcounted buffers, and PyAV is not dealing with them properly (although I'm not sure how to deal with them; nothing I have tried so far has worked).

**Comment by mikeboers** [comment]
Hilariously enough, the leak goes away when running under Valgrind, and Valgrind doesn't report much of anything.

**Comment by mikeboers** [comment]
I spent all this time looking at refcounting...

I'm pretty sure it is in the log handler, and it doesn't work out well when threaded.

**Comment by mikeboers** [comment]
I think that fixes it!

Turns out that `Py_AddPendingCall` sometimes misses a few scheduled functions when there is a ton of calls to it (due to every thread logging about the "SAR" on every frame). That leaks ~1kB every time. Over 10k frames, with lots of bad luck, that can be a few GB.

**Comment by ksze** [comment]
I took a quick look at your commit. So you are now writing to a global `LogRequest req` instead of passing `req` as an argument via `Py_AddPendingCall`. Does that mean that threads can overwrite each other's log message before the main thread has a chance to process it?

(I don't hugely care about ffmpeg/libav's log messages. It's just an observation and I'm trying to understand the change.)

**Comment by mikeboers** [comment]
Your interpretation is correct. I wanted to first make sure the leak was fixed, which made the logging a little less reliable. I'll go open a new issue about the logging, but it shouldn't be bad.

**Comment by mkassner** [comment]
I have tested on my vm and it seems to be fixed. GREAT!

**Comment by ksze** [comment]
Awesome. I just tested on our production machine and now the memory usage is pretty much at a constant low value.

**Comment by mikeboers** [comment]
I'm calling it. Hooray!
