### ISSUE TITLE
Segfault when using more threads 

### ISSUE THREAD

**Issue by mkassner** [mikeboers/PyAV#131]
On Linux VM using more threads than 2. (setting the video stream thread count was introduced with #73)
will segfault.

**Comment by mkassner** [comment]
Actually I found this to happen on Mac and Linux whenever threads > multiprocessing.cpu_count()

**Comment by mkassner** [comment]
I guess this is not really a bug und it can really bite you. I would propose:

1) add a note to the docs
or 
2) check that value  > multiprocessing.cpu_count() in the property setter

**Comment by mikeboers** [comment]
What do you mean, it isn't really a bug?

**Comment by mkassner** [comment]
I should have been a bit more clear on this: Im not sure wether this is a pyav issue or a libav issue.
