### ISSUE TITLE
add _stream rate is inverted

### ISSUE THREAD

**Issue by mkassner** [mikeboers/PyAV#133]
It may be a typo or a conceptual misunderstanding but these two should be switched:

https://github.com/mikeboers/PyAV/blob/55ccb65746cc6c4d771d97cb62ec868ae466dc04/av/container/output.pyx#L110-L111

**Comment by mikeboers** [comment]
Also, the ones from #94 (?)

**Comment by mkassner** [comment]
Yes I think so,

the frame timebase is correct but the stream timebase needs to be inverted at the moment.

**Comment by mikeboers** [comment]
Gross. =P

The tricky part (as is the same that has kept me from doing a massive time overhaul), is "fixing" everything without breaking backwards compatibility.

**Comment by mkassner** [comment]
I think that wont be possible without adding a new parameter besides 'rate' like 'timebase'.

**Comment by mikeboers** [comment]
I'm thinking that inverted stuff like this can be fixed, then a `av.utils.auto_correct_time_bases()` method would trigger global behaviour to automatically flip things like this (so that numerators are always less than denominators, for instance).

Or just break backwards compatibility. Whichever.

**Comment by jlaine** [comment]
This was fixed by 229917c00501e731a16cc54faa272671469a45f8 so it can be closed.

**Comment by mikeboers** [comment]
Thanks @jlaine!
