### ISSUE TITLE
Problem with pyinstaller

### ISSUE THREAD

**Issue by jordijp** [mikeboers/PyAV#136]
Hi,
first of all, thank you very much for the pyav bindings !
I am having trouble with pyinstaller and av

Let's say we have this simple script
<pre>
import av
print "Hello World"
</pre>

If I pack it with pyinstaller:
<pre>pyinstaller helloav.py --onefile</pre>

I get the following error:
<pre>
jordi@lab:~$ cd dist/
jordi@lab:~/dist$ ls
helloav
jordi@lab:~/dist$ ./helloav 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/av/__init__.py", line 15, in <module>
    from .audio.fifo import AudioFifo
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 517, in load_module
    module = imp.load_module(fullname, fp, filename, ext_tuple)
  File "av/format.pxd", line 4, in init av.audio.fifo (src/av/audio/fifo.c:2806)
ImportError: No module named format
helloav returned -1
</pre>

The version I am using:
<pre>
---
Name: av
Version: 0.2.4
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
</pre>

Any help or suggestions will be appreciated

**Comment by mikeboers** [comment]
My guess is that pyinstaller does not natively recognize Cython extensions. Take a look at [this SO answer](https://github.com/prologic/pyinstaller-cython-bundling).

I'm closing this because this is unlikely a PyAV problem, but please feel free to reply with whatever you figure out.

**Comment by mkassner** [comment]
Have a look at the pupil eye tracking project bundle.spec we have solved
this there. It comes down to adding some hidden imports.

**Comment by happlebao** [comment]
the previous comment is right solution.
here is the spec file he mentioned.
https://github.com/pupil-labs/pupil/blob/master/deployment/deploy_player/bundle.spec

the file may need adjust as you need

**Comment by ocard** [comment]
I tried using @mkassner's solution, and get the following error on runtime:

`File "site-packages\av\audio\__init__.py", line 1, in <module>
  File "av\audio\frame.pyx", line 1, in init av.audio.frame
  File "av\frame.pyx", line 8, in init av.frame
AttributeError: type object 'av.frame.Frame' has no attribute '__reduce_cython__'`

pyav==8.0.0, pyinstaller==3.6

Anyone have any clues?
