### ISSUE TITLE
Unable to install pyAV

### ISSUE THREAD

**Issue by anshul1912** [mikeboers/PyAV#138]
Here are logs
I dont know why it is trying to find library in /usr/local/lib in actual library is in /usr/lib
anshul@linux-kiran:~/Project/mutimediavisualprogramming> ./download_dependency.py 
Downloading/unpacking av
  Running setup.py egg_info for package av
    Could not find avformat with ctypes; looked in:
        libavformat.so.55
        /usr/local/lib/libavformat.so.55
    Could not find avutil with ctypes; looked in:
        libavutil.so.52
        /usr/local/lib/libavutil.so.52
    Could not find avcodec with ctypes; looked in:
        libavcodec.so.55
        /usr/local/lib/libavcodec.so.55
    Could not find ['avformat', 'avutil', 'avcodec'] with ctypes.util.find_library
    Some libraries can not be found for inspection; aborting!
    Complete output from command python setup.py egg_info:
    Could not find avformat with ctypes; looked in:

        libavformat.so.55

        /usr/local/lib/libavformat.so.55

Could not find avutil with ctypes; looked in:

        libavutil.so.52

        /usr/local/lib/libavutil.so.52

Could not find avcodec with ctypes; looked in:

        libavcodec.so.55

        /usr/local/lib/libavcodec.so.55

Could not find ['avformat', 'avutil', 'avcodec'] with ctypes.util.find_library

Some libraries can not be found for inspection; aborting!

----------------------------------------
Command python setup.py egg_info failed with error code 2 in /tmp/pip-build/av
Storing complete log in /home/anshul/.pip/pip.log
anshul@linux-kiran:~/Project/mutimediavisualprogramming> python
Python 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> find_library("avformat")
'libavformat.so.55'

**Comment by mikeboers** [comment]
The build system has been redesigned since the last release. Please try building from source.

**Comment by anshul1912** [comment]
from source too it fails with some other error. I was able to install it on similar system a week ago, it could be problem with recent code. Have not yet done regruss testing, will do it and let you know the result
```
anshul@linux-kiran:~/Project/mutimediavisualprogramming/PyAV> python setup.py build
running build
running build_py
creating build
creating build/lib.linux-i686-2.7
creating build/lib.linux-i686-2.7/av
copying av/__main__.py -> build/lib.linux-i686-2.7/av
copying av/__init__.py -> build/lib.linux-i686-2.7/av
creating build/lib.linux-i686-2.7/av/subtitles
copying av/subtitles/__init__.py -> build/lib.linux-i686-2.7/av/subtitles
creating build/lib.linux-i686-2.7/av/container
copying av/container/__init__.py -> build/lib.linux-i686-2.7/av/container
creating build/lib.linux-i686-2.7/av/video
copying av/video/__init__.py -> build/lib.linux-i686-2.7/av/video
creating build/lib.linux-i686-2.7/av/audio
copying av/audio/__init__.py -> build/lib.linux-i686-2.7/av/audio
running build_ext
running reflect
running config
looking for avformat_open_input... found
looking for pyav_function_should_not_exist... missing
looking for av_calloc... found
looking for av_frame_get_best_effort_timestamp... found
looking for avformat_alloc_output_context2... found
looking for avformat_close_input... found
looking for AVStream.index... found
looking for PyAV.struct_should_not_exist... missing
looking for AVFrame.mb_type... missing
writing build/temp.linux-i686-2.7/include/pyav/config.h
running cythonize
Traceback (most recent call last):
  File "setup.py", line 715, in <module>
    distclass=distclass,
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 657, in run
    self.run_command('cythonize')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 575, in run
    include_path=ext.include_dirs,
  File "/usr/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 603, in cythonize
    aliases=aliases)
  File "/usr/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 505, in create_extension_list
    explicit_modules = set([m.name for m in patterns if isinstance(m, Extension)])
TypeError: iteration over non-sequence
```

**Comment by mikeboers** [comment]
At least it is finding the libraries that time! :grinning:

What version of Cython do you have?

**Comment by mkassner** [comment]
I know ffmpeg changed a lot since 2.7 I know some of the fn PyAV looks for
no longer exist.

**Comment by anshul1912** [comment]
cython version 0.17.2-2.1.2
