### ISSUE TITLE
reformatting a frame from `rgb24` to `yuv420p` segfaults

### ISSUE THREAD

**Issue by hbristow** [mikeboers/PyAV#142]
I'm having issues encoding numpy arrays to an output stream with `yuv420p` or `yuv422p` encoding. I've traced it down to this MWE:

```
import av
import numpy as np

np_frame = np.zeros((720,1280,3), dtype=np.uint8)
rgb_frame = av.VideoFrame.from_ndarray(np_frame, format='rgb24') # putting 'yuv420p' here raises ValueError: got 720 bytes; need 921600 bytes

while True:
    yuv_frame = rgb_frame.reformat(format='yuv420p') # boom!
```

For me this produces either a `Segmentation Fault: 11` or a `Bus Error: 10`

**Comment by mikeboers** [comment]
Oh dear. Are you using PyPI or the latest master?

**Comment by mikeboers** [comment]
I just replicated this on the current master. That answers that question...

**Comment by mikeboers** [comment]
It is happening somewhere in swsscale, [called in VideoFrame.reformat](https://github.com/mikeboers/PyAV/blob/2ba8cf7162e0c21ff208ca5df8e6b69abe80feff/av/video/frame.pyx#L191-L199). I might need to rebuild FFmpeg with debugging symbols to really dig into it.

**Comment by mikeboers** [comment]
Building FFmpeg with `--disable-optimizations --disable-mmx --disable-stripping` stops the segfault. How irritating...

**Comment by hbristow** [comment]
Hmm, interesting. I noticed it only happens with certain frame sizes. 1920x1200 never caused an issue, but 1280x720 always did.

**Comment by mikeboers** [comment]
I have isolated it to the function [called here](https://github.com/FFmpeg/FFmpeg/blob/master/libswscale/swscale.c#L260). As far as I can tell, everything we're passing into swscale is correct. I intend to try this with the ffmpeg HEAD and see what happens.

I'm going to be super crazy busy for the next few days. Please hang tight.

**Comment by hbristow** [comment]
No rush at all. I was just experimenting with PyAv to see if it would be useful for a project, but I've got other projects that are higher priority for the next few weeks.

**Comment by mikeboers** [comment]
Nearly 3 years later, this does not happen anymore.
