### ISSUE TITLE
Make PyAV work with latest ffmpeg releases

### ISSUE THREAD

**Issue by mkassner** [mikeboers/PyAV#146]
These two patches are needed to reflect updates in the ffmpeg source:

https://gist.github.com/mkassner/f8c29b4e7c7a4806ec73

Since I work in a different branch I was not able to PR. But I think the patches should apply cleanly.

**Comment by mikeboers** [comment]
I'm pretty sure this is covered by the `ffmpeg-3.0` branch, which will (likely) be merged very shortly.
