### ISSUE TITLE
av built and installed correctly via pip, python 3.4 interpreter doesn't find it

### ISSUE THREAD

**Issue by chromafunk** [mikeboers/PyAV#147]
ImportError: No module named 'av'

pip3 freeze : 

av==0.2.4

Any idea ?

Managed to fix by creating a virtual env

**Comment by eggs23** [comment]
same error for me for different project.
You solved this ?

**Comment by MichaelRomeroJr** [comment]
I got the error "ERROR: Failed building wheel for av" using pip 19.1.1 trying to install av 6.2.0
Installing the module using -conda worked though.
