### ISSUE TITLE
Random audio channel layout when there are more than 8 channels of audio

### ISSUE THREAD

**Issue by tahpee** [mikeboers/PyAV#148]
I've got a video clip that has 16 channels of audio. When I try to decode the audio packets I get a random channel layout. It turns out that it is looking up an entry in default_layouts (audio/layout.pyx) for 16 channels and there is no entry, so it reads some random rubbish from memory and tries to use that as the channel layout.

Oddly the same file and script is fine on Ubuntu with PyAV 0.2.4 and LibAV but under OS X with ffmpeg 2.8.6 it fails.

Fix is to add some entries in default_layouts for channel counts > 8.

**Comment by jlaine** [comment]
What's the status of this? It looks like the corresponding PR was merged?

**Comment by mikeboers** [comment]
Looks like.
