### ISSUE TITLE
missing test assets

### ISSUE THREAD

**Issue by mkovacs** [mikeboers/PyAV#152]
Tests fail due to missing assets.

The missing files are:
- av-0.2.4/tests/assets/1KHz.wav
- av-0.2.4/tests/assets/320x240x4.mov
- av-0.2.4/tests/assets/lenna.png

**Comment by mikeboers** [comment]
Back in the 0.2.4 release, the `Makefile` generated those assets. I'm pretty sure we don't even have those anymore, so it won't be a problem in the next release. =]
