### ISSUE TITLE
FLV1 decode/encode

### ISSUE THREAD

**Issue by TechWhizZ199** [mikeboers/PyAV#154]
Hey,

I have some raw RTMP FLV1 frame data which I would love to convert into something useful, possibly get the raw pixel data which can be converted into an image. I was wondering if PyAV has any libavcodec or any other bindings which can enable me to do so. Just to let you know the frames themselves come out compressed by the looks of it.

Thank you!

**Comment by mikeboers** [comment]
Not enough information here to say for sure. You can create a `StringIO` with your data and pass that to `av.open(...)`. That likely requires them to be in some sort of container. If you have individual packets maybe there is something that can be exposed to do that.

**Comment by TechWhizZ199** [comment]
Just to give you some context to what this actually is. All I am trying to do is get the data received from sending an RTMP 'play' command and converting the data I get (whether it is a keyframe/interframe/disposable - interframe) into a JPEG image or any other image type. I know that the video data is encoded in FLV1. And as for the individual packets, I do receive them individually, I have muted out audio packets so I can just try to convert the video messages into images.

In terms of converting the raw pixel data, I know PIL can do that. But I just need a way of decoding that flv1 data. I am not sure as to what you mean by the container though.

Thanks as well.

**Comment by mikeboers** [comment]
Can you provide a script which does this interaction with the RTMP server and gets the raw packets? And also, hopefully, the RTMP stream you are trying to convert.

**Comment by TechWhizZ199** [comment]
I can show you the script, but since it is part of an IRC/Chat bot for https://tinychat.com/. It is hard to tell you how to operate it. I have pasted two consecutive raw packets which I received from the server here http://hastebin.com/calawobexu.tex .

**Comment by mikeboers** [comment]
I've not managed to coerce PyAV to be able to decode data without a container, and I haven't figured out a way to trick it. To be fair, I have not attempted to use `flv1` at this level before, so I actually don't really know what I'm doing.

I think it is certainly possible using the underlying libraries, but PyAV has not been structured in a way that allows it. #155 is the proposal to refactor.

**Comment by TechWhizZ199** [comment]
Thank you for the help anyway Mr. Boers. I know some people have done it in C with the aid of libavvcodev and libavresample. I'll update you if I do find any solutions to this.
