### ISSUE TITLE
Slow video conversion.

### ISSUE THREAD

**Issue by Duality4Y** [mikeboers/PyAV#157]
I have been playing around with pyav, and this is the code i have written so far:
http://pastebin.com/JLZfy73A

basicly paints a frame onto a surface which you inherit from.

but there is allot of time wasted in the draw_frame function.

is there a more efficient way to do this? I only need frames.

also I find the example lacking comments, and the docs too, 
unless i am not looking in the right place ?
http://mikeboers.github.io/PyAV/

also I do not know what i am doing here :) since descriptions are lacking.

**Comment by mikeboers** [comment]
There is going to be a ton of time spent in converting to an Numpy array, and then every row into tuples, and then again setting every pixel individually.

I recommend that you, somehow, take advantage of the buffer protocol that the video planes (in `VideoFrame.planes`) expose. Then you can get all of the data for a frame in a single blob without all of the copying and iterating.

Good luck!

**Comment by Duality4Y** [comment]
yes that would be nice i'll investigate it :) thanks for the tip!
