### ISSUE TITLE
FFmpeg 3.0 compatibility

### ISSUE THREAD

**Issue by tcwalther** [mikeboers/PyAV#159]
PyAV doesn't work with recent ffmpeg releases, such as 3.0. It currently relies on `audioconvert.h`, which was removed last summer: 

https://ffmpeg.org/pipermail/ffmpeg-cvslog/2015-September/093332.html

The ffmpeg source recommends using `libswresample` instead. Would it be a lot of work to make the switch?

**Comment by mikeboers** [comment]
This has been addressed in 9b72401 (at least enough to compile and run), and should get merged relatively soon.

Does anyone thing there is enough pressure that this should get released on its own ASAP?

**Comment by tcwalther** [comment]
Excellent. I had searched the master branch before filing this issue, but didn't notice that you had already done this work in a separate branch.

Right now, it's not extremely urgent for me. However, new people installing ffmpeg via homebrew will always install version 3.0; installing an older version via homebrew is not trivial (as `brew versions` is now completely deprecated, and ffmpeg is not in the `homebrew/versions` tap), so it might be worth planning a release relatively soon.

**Comment by mikeboers** [comment]
I agree with everything above. It has been a long time since we have released to PyPI.

**Comment by mikeboers** [comment]
I just got an email from someone else having the same problem. So... :+1:

**Comment by tcwalther** [comment]
Is there any blocking issue to a new release? I successfully compiled the ffmpeg-3.0 branch, and it runs perfectly fine.

**Comment by mikeboers** [comment]
Not really. Fear of breaking everything since it has been forever, and there were a lot of changes. Mostly backwards compatible.

I guess that is what semantic versioning is for. ;)

I'll find the time to do it Soon™.

**Comment by mikeboers** [comment]
I just uploaded 0.3.0 to PyPI. Lets see what issues this causes...

**Comment by mkassner** [comment]
:+1:
