### ISSUE TITLE
Way to generate thumbnail every X second

### ISSUE THREAD

**Issue by jeyraof** [mikeboers/PyAV#160]
Hi.

How to generate thumbnail from video every X second, not frame?

Thank you.

In CLI ffmpeg, I had used:

`$ ffmpeg -i test.mp4 -f image2 -vf fps=fps=1 ffmpeg/%03d.jpg`

**Comment by mikeboers** [comment]
Iterate across the video frames, and check their `time` property. Every time you get to a new second, save the image (e.g. via PIL `frame.to_image().save('path/to/frame.jpg')`).

Good luck!

**Comment by sipie800** [comment]
Iterate across the frames? oh no...
that's way too slow, just 1-2x speed, when the video is 60fps, it's just meaning less.
Go for ffmpeg cli or ffmpeg with gpu decode.
