### ISSUE TITLE
Logging is very slow

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#166]
During #128 and #164, the actual decoding takes ~6 seconds. Processing the main log callback adds very little overhead. Getting to the point of being ready to dump into the Python logging system adds ~2s. Actually doing it adds another ~4s. So that is fully an additional 100% for logging the same message thousands of times.

Perhaps we should severely raise the default logging threshold to ERROR.

It would be interesting to see if we could instrument the loggers so that the C callback is aware of the minimum Python threshold.

**Comment by mkassner** [comment]
I have noticed this too. 

Is doing 

```python
av.logging.set_level(av.logging.ERROR)
```

enough in this case?

**Comment by mikeboers** [comment]
Yes. That cuts it off very early in the process.

**Comment by mikeboers** [comment]
I implemented the same behavior as FFmpeg does, and skip repeated messages. This will likely be good enough. In the future this could be made a little better (e.g. remembering the last message by logger name, such that two repeating messages will get caught). #167 will suggest setting the level to `ERROR` once you are confident in the script.
