### ISSUE TITLE
SIGSEGV on some mov files(with embedded timecode)

### ISSUE THREAD

**Issue by KengoSawa2** [mikeboers/PyAV#169]
PyAV segfaults on some mov files.

Test data and Test code:
[pyav_crashtest.zip](https://github.com/mikeboers/PyAV/files/235936/pyav_crashtest.zip)

My Environment:

> pip list
> av (0.3.1)
> port installed ffmpeg
> ffmpeg @2.8.6_1+gpl2+x11 (active)

OS X crash report:
[tc_crashreport.txt](https://github.com/mikeboers/PyAV/files/236000/tc_crashreport.txt)

I use ffprobe to testdata.
ffprobe display error message is below:
"Unsupported codec with id 0 for input stream 2"

The cause of the crash I'm thinking that it is the presence or absence of the time code.

**Comment by mikeboers** [comment]
I can confirm the segfault on the current master with FFmpeg 3.0. Thanks so much for the samples!

I wonder/hope this is related to #163 (but I doubt it).

**Comment by KengoSawa2** [comment]
Thank you quick response and explanation.

though being late,
pyav is us to strongly support me. I am very grateful to you.
Thank you for the wonderful library :)
I used a PyAV, trying to make a xlsx shotlist with thumbnails.


I read issue #163.
hmmm... 
According to your description, this problem is not because of pyav?
Do you think that it is a problem of the python interpreter or ffmpeg process?

If there is a possibility of ffmpeg issues,
I use various versions of ffmpeg, I think to try whether it is possible to avoid this problem.

**Comment by mikeboers** [comment]
Oh no, I think it is PyAV, or something about PyAV. I have not figured out #163, but (1) I don't think it is likely they are related, and (2) I'm pretty sure it is PyAV's or Cython's fault.

I haven't actually tried debugging this yet.

**Comment by KengoSawa2** [comment]
I see.
I had been a misunderstanding about the contents of # 132.

I'm a python novice, but I think that it is difficult to solve your bug,
I think I will also try to read the code.

Thank you.

**Comment by cbenhagen** [comment]
@mikeboers please reopen this issue

```python
import av
av.open('tmcd_test.mov')
```
Opening the mov in [tmcd_test.mov.zip](https://github.com/mikeboers/PyAV/files/783597/tmcd_test.mov.zip) with PyAV 0.3.2 still produces [this crash](https://github.com/mikeboers/PyAV/files/783602/error_report.txt). I do not think this is related to #163.


```
$ ffmpeg -version
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
configuration: --prefix=/usr/local/Cellar/ffmpeg/3.2.4 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
libavutil      55. 34.101 / 55. 34.101
libavcodec     57. 64.101 / 57. 64.101
libavformat    57. 56.101 / 57. 56.101
libavdevice    57.  1.100 / 57.  1.100
libavfilter     6. 65.100 /  6. 65.100
libavresample   3.  1.  0 /  3.  1.  0
libswscale      4.  2.100 /  4.  2.100
libswresample   2.  3.100 /  2.  3.100
libpostproc    54.  1.100 / 54.  1.100
```

**Comment by mikeboers** [comment]
Sure.

```
$ python -c 'import av; av.open("tmcd_test.mov")'
Segmentation fault: 11
```

**Comment by mikeboers** [comment]
I managed to cobble together a slightly better debugging Python. Most of the time it doesn't crash.

Sometimes, however, it does:

```
$ python crash.py 
Fatal Python error: Objects/typeobject.c:1035 object at 0x102823880 has negative ref count -5764607522763168925
Abort trap: 6
```

**Comment by KengoSawa2** [comment]
wow! This is a great fix!

I was trying to make a product that utilized PyAV.
I think that my development will also proceed thanks to this correction.
thank you.

I am glad that you can tell diff about the details of the problem.
Because I have to study PyAV and ffmpeg for my product
