### ISSUE TITLE
Didn't find 'avformat_open_input' Ubuntu

### ISSUE THREAD

**Issue by katrinabrock** [mikeboers/PyAV#170]
```
   We didn't find `avformat_open_input` in the libraries.
    We look for it only as a sanity check to make sure the build
    process is working as expected. It is not, so we must abort.

    Please open a ticket at https://github.com/mikeboers/PyAV/issues
    with the folowing information:

    PyAV: 0.3.1
    Python: 2.7.6 (default, Jun 22 2015, 17:58:13) \n[GCC 4.8.2]
    platform: Linux-3.19.0-59-generic-x86_64-with-Ubuntu-14.04-trusty
    extension_extra:
        libraries: ['X11', 'Xext', 'Xv', 'avcodec', 'avdevice', 'avfilter', 'avformat', 'avutil', 'bz2', 'm', 'swresample', 'swscale', 'xcb', 'xcb-render', 'xcb-shape', 'xcb-xfixes', 'z']
        library_dirs: ['/usr/local/lib']
        include_dirs: ['/usr/local/include', 'include', '/usr/include/python2.7']
    config_macros:
        PYAV_VERSION=0.3.1
        PYAV_VERSION_STR="0.3.1"
        PYAV_COMMIT_STR="unknown-commit"
        PYAV_HAVE_LIBSWRESAMPLE=1
        PYAV_HAVE_AV_CALLOC=1
        PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-A8DzRj/av/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-txMrAL-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-A8DzRj/av/
```

---

**EDIT by @mikeboers:** [down the page I wrote](https://github.com/mikeboers/PyAV/issues/170#issuecomment-226245778):

> I'm pretty sure there there is some sort of compilation error that arises during linking to the static library vs the dynamic ones. The "fix", I believe, is to discuss this in the error message, and expose a flag so that you can try again and print out all of the compiler errors.

**Comment by mikeboers** [comment]
Can you tell us what version of FFmpeg/LibAV you are compiling against?

**Comment by katrinabrock** [comment]
Here is the version:

$ ffmpeg -version
ffmpeg version N-79976-gcb928fc Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
configuration: 
libavutil      55. 24.100 / 55. 24.100
libavcodec     57. 41.102 / 57. 41.102
libavformat    57. 36.100 / 57. 36.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 45.100 /  6. 45.100
libswscale      4.  1.100 /  4.  1.100
libswresample   2.  0.101 /  2.  0.101

**Comment by martijnende** [comment]
Same problem here:
    
    PyAV: 0.3.1
    Python: 2.7.6 (default, Jun 22 2015, 17:58:13) \n[GCC 4.8.2]
    platform: Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa
    extension_extra:
    	libraries: ['X11', 'avcodec', 'avdevice', 'avfilter', 'avformat', 'avutil', 'm', 'swresample', 'swscale', 'xcb', 'xcb-render', 'xcb-shape', 'xcb-xfixes']
    	library_dirs: ['/usr/local/lib']
    	include_dirs: ['/usr/local/include', 'include', '/usr/include/python2.7']
    config_macros:
    	PYAV_VERSION=0.3.1
    	PYAV_VERSION_STR="0.3.1"
    	PYAV_COMMIT_STR="unknown-commit"
    	PYAV_HAVE_LIBSWRESAMPLE=1
    	PYAV_HAVE_AV_CALLOC=1
    	PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=1

FFmpeg version:

    ffmpeg version N-80003-g2f76157 Copyright (c) 2000-2016 the FFmpeg developers
    built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
    configuration: 
    libavutil      55. 24.100 / 55. 24.100
    libavcodec     57. 42.100 / 57. 42.100
    libavformat    57. 36.100 / 57. 36.100
    libavdevice    57.  0.101 / 57.  0.101
    libavfilter     6. 45.100 /  6. 45.100
    libswscale      4.  1.100 /  4.  1.100
    libswresample   2.  0.101 /  2.  0.101

**Comment by qenops** [comment]
I am having the same problem.  The curl file to compile ffmpeg did not run on my machine since some of the config.guess files are from 2003 and do not support ARM architecture, so I compiled on my own. Here is the output from mine:
```
running config
looking for avformat_open_input... missing
looking for pyav_function_should_not_exist... missing
looking for av_calloc... found
looking for av_frame_get_best_effort_timestamp... found
looking for avformat_alloc_output_context2... missing
looking for avformat_close_input... missing
looking for AVStream.index... found
looking for PyAV.struct_should_not_exist... missing
looking for AVFrame.mb_type... missing

We didn't find `avformat_open_input` in the libraries.
We look for it only as a sanity check to make sure the build
process is working as expected. It is not, so we must abort.

Please open a ticket at https://github.com/mikeboers/PyAV/issues
with the folowing information:

PyAV: 0.3.0 v0.3.0-18-g498516d
Python: 2.7.6 (default, Jun 22 2015, 18:31:26) \n[GCC 4.8.2]
platform: Linux-3.10.67-g3a5c467-aarch64-with-Ubuntu-14.04-trusty
extension_extra:
	libraries: ['X11', 'asound', 'avcodec', 'avdevice', 'avfilter', 'avformat', 'avutil', 'faac', 'gnutls', 'm', 'mp3lame', 'ogg', 'opencore-amrnb', 'opencore-amrwb', 'postproc', 'rtmp', 'swresample', 'swscale', 'theoradec', 'theoraenc', 'vorbis', 'vorbisenc', 'x264', 'xcb', 'xcb-render', 'xcb-shape', 'xcb-xfixes', 'xvidcore', 'z']
	library_dirs: ['/usr/local/lib']
	include_dirs: ['/usr/local/include', 'include', '/usr/include/python2.7']
config_macros:
	PYAV_VERSION=0.3.0
	PYAV_VERSION_STR="0.3.0"
	PYAV_COMMIT_STR="v0.3.0-18-g498516d"
	PYAV_HAVE_LIBSWRESAMPLE=1
	PYAV_HAVE_AV_CALLOC=1
	PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=1
```
ffmpeg version here:
```
ubuntu@tegra-ubuntu:~/git/PyAV$ ffmpeg -version
ffmpeg version git-2016-05-17-d55568d Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 4.8 (Ubuntu/Linaro 4.8.4-2ubuntu1~14.04.3)
configuration: --enable-gpl --enable-libfaac --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librtmp --enable-libtheora --enable-libvorbis --enable-libx264 --enable-nonfree --enable-version3 --enable-libxvid --arch=armel --target-os=linux
libavutil      55. 24.100 / 55. 24.100
libavcodec     57. 42.100 / 57. 42.100
libavformat    57. 36.100 / 57. 36.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 45.100 /  6. 45.100
libswscale      4.  1.100 /  4.  1.100
libswresample   2.  0.101 /  2.  0.101
libpostproc    54.  0.100 / 54.  0.100
```
Any thoughts?
Thanks!

**Comment by haradai1262** [comment]
Same error?

(cdl)*name*_sub@eir:~$ pip install av
Collecting av
  Using cached av-0.3.1.tar.gz
Building wheels for collected packages: av
  Running setup.py bdist_wheel for av ... error
  Complete output from command /home/*name*_sub/.virtualenvs/cdl/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cPVfn9/av/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpQxlOXIpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/av
  copying av/__main__.py -> build/lib.linux-x86_64-2.7/av
  copying av/__init__.py -> build/lib.linux-x86_64-2.7/av
  creating build/lib.linux-x86_64-2.7/av/audio
  copying av/audio/__init__.py -> build/lib.linux-x86_64-2.7/av/audio
  creating build/lib.linux-x86_64-2.7/av/video
  copying av/video/__init__.py -> build/lib.linux-x86_64-2.7/av/video
  creating build/lib.linux-x86_64-2.7/av/container
  copying av/container/__init__.py -> build/lib.linux-x86_64-2.7/av/container
  creating build/lib.linux-x86_64-2.7/av/subtitles
  copying av/subtitles/__init__.py -> build/lib.linux-x86_64-2.7/av/subtitles
  running build_ext
  running reflect
  running config
  looking for avformat_open_input... missing
  looking for pyav_function_should_not_exist... missing
  looking for av_calloc... found
  looking for av_frame_get_best_effort_timestamp... found
  looking for avformat_alloc_output_context2... missing
  looking for avformat_close_input... missing
  looking for AVStream.index... found
  looking for PyAV.struct_should_not_exist... missing
  looking for AVFrame.mb_type... missing
  
  We didn't find `avformat_open_input` in the libraries.
  We look for it only as a sanity check to make sure the build
  process is working as expected. It is not, so we must abort.
  
  Please open a ticket at https://github.com/mikeboers/PyAV/issues
  with the folowing information:
  
  PyAV: 0.3.1
  Python: 2.7.11 (default, May 19 2016, 15:35:23) \n[GCC 4.8.4]
  platform: Linux-3.13.0-86-generic-x86_64-with-debian-jessie-sid
  extension_extra:
  	libraries: ['SDL', 'X11', 'asound', 'ass', 'avcodec', 'avdevice', 'avfilter', 'avformat', 'avutil', 'bz2', 'dl', 'fdk-aac', 'lzma', 'm', 'mp3lame', 'ogg', 'opus', 'postproc', 'pthread', 'swresample', 'swscale', 'theoradec', 'theoraenc', 'va', 'va-drm', 'va-x11', 'vorbis', 'vorbisenc', 'vpx', 'x264', 'xcb', 'xcb-render', 'xcb-shape', 'xcb-shm', 'xcb-xfixes', 'z']
  	library_dirs: ['/usr/local/lib']
  	include_dirs: ['/usr/local/include', 'include', '/usr/local/lib/python2.7.11/include/python2.7']
  config_macros:
  	PYAV_VERSION=0.3.1
  	PYAV_VERSION_STR="0.3.1"
  	PYAV_COMMIT_STR="unknown-commit"
  	PYAV_HAVE_LIBSWRESAMPLE=1
  	PYAV_HAVE_AV_CALLOC=1
  	PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=1
  
  ----------------------------------------
  Failed building wheel for av
  Running setup.py clean for av
Failed to build av
Installing collected packages: av
  Running setup.py install for av ... error
    Complete output from command /home/*name*_sub/.virtualenvs/cdl/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cPVfn9/av/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-nWqHwD-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/*name*_sub/.virtualenvs/cdl/include/site/python2.7/av:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/av
    copying av/__main__.py -> build/lib.linux-x86_64-2.7/av
    copying av/__init__.py -> build/lib.linux-x86_64-2.7/av
    creating build/lib.linux-x86_64-2.7/av/audio
    copying av/audio/__init__.py -> build/lib.linux-x86_64-2.7/av/audio
    creating build/lib.linux-x86_64-2.7/av/video
    copying av/video/__init__.py -> build/lib.linux-x86_64-2.7/av/video
    creating build/lib.linux-x86_64-2.7/av/container
    copying av/container/__init__.py -> build/lib.linux-x86_64-2.7/av/container
    creating build/lib.linux-x86_64-2.7/av/subtitles
    copying av/subtitles/__init__.py -> build/lib.linux-x86_64-2.7/av/subtitles
    running build_ext
    running reflect
    running config
    looking for avformat_open_input... missing
    looking for pyav_function_should_not_exist... missing
    looking for av_calloc... found
    looking for av_frame_get_best_effort_timestamp... found
    looking for avformat_alloc_output_context2... missing
    looking for avformat_close_input... missing
    looking for AVStream.index... found
    looking for PyAV.struct_should_not_exist... missing
    looking for AVFrame.mb_type... missing
    
    We didn't find `avformat_open_input` in the libraries.
    We look for it only as a sanity check to make sure the build
    process is working as expected. It is not, so we must abort.
    
    Please open a ticket at https://github.com/mikeboers/PyAV/issues
    with the folowing information:
    
    PyAV: 0.3.1
    Python: 2.7.11 (default, May 19 2016, 15:35:23) \n[GCC 4.8.4]
    platform: Linux-3.13.0-86-generic-x86_64-with-debian-jessie-sid
    extension_extra:
    	libraries: ['SDL', 'X11', 'asound', 'ass', 'avcodec', 'avdevice', 'avfilter', 'avformat', 'avutil', 'bz2', 'dl', 'fdk-aac', 'lzma', 'm', 'mp3lame', 'ogg', 'opus', 'postproc', 'pthread', 'swresample', 'swscale', 'theoradec', 'theoraenc', 'va', 'va-drm', 'va-x11', 'vorbis', 'vorbisenc', 'vpx', 'x264', 'xcb', 'xcb-render', 'xcb-shape', 'xcb-shm', 'xcb-xfixes', 'z']
    	library_dirs: ['/usr/local/lib']
    	include_dirs: ['/usr/local/include', 'include', '/usr/local/lib/python2.7.11/include/python2.7']
    config_macros:
    	PYAV_VERSION=0.3.1
    	PYAV_VERSION_STR="0.3.1"
    	PYAV_COMMIT_STR="unknown-commit"
    	PYAV_HAVE_LIBSWRESAMPLE=1
    	PYAV_HAVE_AV_CALLOC=1
    	PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=1
    
    ----------------------------------------
Command "/home/*name*_sub/.virtualenvs/cdl/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cPVfn9/av/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-nWqHwD-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/*name*_sub/.virtualenvs/cdl/include/site/python2.7/av" failed with error code 1 in /tmp/pip-build-cPVfn9/av/

**Comment by mikeboers** [comment]
Huh. Consistently `avformat_open_input` is not being found, but others are. Makes me immediately guess that the function was removed from the newest version of the library, but that doesn't seem to be the case.

**Comment by mikeboers** [comment]
Not reproducing on my Mac with FFmpeg 3.0.2, but version-wise it seems a little behind:

```
libavutil      55. 17.103 / 55. 17.103
libavcodec     57. 24.102 / 57. 24.102
libavformat    57. 25.100 / 57. 25.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 31.100 /  6. 31.100
libswscale      4.  0.100 /  4.  0.100
libswresample   2.  0.101 /  2.  0.101
```
Seems like we have Ubuntu 14, and Debian in the list above. Also PyAv `v0.3.1` and something from git after `v0.3.0`. Everyone seems to have the same FFmpeg. Where is that coming from? Current HEAD?

**Comment by qenops** [comment]
Yeah, I'm cloning the current ffmpeg from github:
`git clone https://github.com/FFmpeg/FFmpeg.git`

**Comment by nicholascarroll** [comment]
getting this on osx yosemite. recent dev version of ffmpeg built from source.

**Comment by mikeboers** [comment]
@nicholascarroll That is good news (for me), because it means I should be much more likely to be able to reproduce this.

**Comment by mikeboers** [comment]
Hooray! I have finally replicated this problem!

~~~
looking for avformat_open_input... missing
looking for pyav_function_should_not_exist... missing
looking for av_calloc... found
looking for av_frame_get_best_effort_timestamp... found
looking for avformat_alloc_output_context2... missing
looking for avformat_close_input... missing
looking for AVStream.index... found
looking for PyAV.struct_should_not_exist... missing
looking for AVFrame.mb_type... missing

We didn't find `avformat_open_input` in the libraries.
We look for it only as a sanity check to make sure the build
process is working as expected. It is not, so we must abort.
~~~

**Comment by mikeboers** [comment]
My immediate guess is that it is trying to link against the static libraries, and <insert something> happens. When I rebuild ffmpeg `--without-static` it is fine. Needs more testing.

**Comment by mikeboers** [comment]
I'm pretty sure there there is some sort of compilation error that arises during linking to the static library vs the dynamic ones. The "fix", I believe, is to discuss this in the error message, and expose a flag so that you can try again and print out all of the compiler errors.

**Comment by tcwalther** [comment]
I just ran into the same issue, trying to install pyav in an Anaconda environment where I installed ffmpeg via conda-forge. Tried 0.3.1 and current Git. Here's my `ffmpeg -version` output:

```
ubuntu@box72:~$ ffmpeg -version
ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 4.8.2 (GCC) 20140120 (Red Hat 4.8.2-15)
configuration: --prefix=/opt/conda/envs/_build --disable-doc --enable-shared --enable-static --extra-cflags='-Wall -g -m64 -pipe -O3 -march=x86-64 -fPIC -I/opt/conda/envs/_build/include ' --extra-cxxflags='=-Wall -g -m64 -pipe -O3 -march=x86-64 -fPIC' --extra-libs='-L/opt/conda/envs/_build/lib -lz ' --enable-pic --enable-gpl --enable-libx264
libavutil      54. 31.100 / 54. 31.100
libavcodec     56. 60.100 / 56. 60.100
libavformat    56. 40.101 / 56. 40.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 40.101 /  5. 40.101
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.101 /  1.  2.101
libpostproc    53.  3.100 / 53.  3.100
```

Is there a workaround?

**Comment by mikeboers** [comment]
I think it is trying to link against the static libs. I imagine there should be a compiler flag to prefer dynamic libs, but it might be a pain to get it cross-platform.

If you find such a thing, you can do:

```
CFLAGS=xxx python setup.py build_ext --inplace
```

**Comment by tcwalther** [comment]
After a lot of testing, I found the issue for my case:

First, I had to set `PKG_CONFIG_PATH` to point to the pkg-config directory in my conda environment. Then, I had to fix the `libavformat.pc` file provided by the ffmpeg installation from conda-forge, see: https://github.com/conda-forge/ffmpeg-feedstock/issues/10

After that, I could install PyAV just fine.

**Comment by GoelBiju** [comment]
@mikeboers , would it be useful if you highlighted using the [install_ffmpeg_ubunutu.sh](https://gist.githubusercontent.com/mkassner/1caa1b45c19521c884d5/raw/b5ce332808b8e26406af0db78115761ea605441c/install_ffmpeg_ubuntu.sh) file with some more priority in the README? That seemed be to the resolution a lot of my installation problems when setting up ffmpeg/libav on Ubunutu 14.04 (trusty) LTS from scratch.

**Comment by tcwalther** [comment]
Yes, that's probably a good idea. Although in my case - CircleCI - compiling from scratch would have probably exceeded the time that a container may run in CI.

**Comment by GoelBiju** [comment]
@tcwalther , It took about 40-50 minutes to get it installed on Ubuntu, I suppose this is why using the wheel is a better idea, though I really am not experienced with compiling it.

**Comment by notedit** [comment]
still have this error

**Comment by notedit** [comment]
after  several try,  i finally figured out,  you  should compile the ffmpeg  with  --enable-shared  

this works for me.

**Comment by clover978** [comment]
@mikeboers 
Aha, I find a potential cause of this issue.
`setup.py` calls  `pkg-config` to find dependencies for `PyAV`. 
However, someone may accidentally have another pkg-config executable in SYSTEM_PATH, that happens to me when I ran `pip install pkg-config` ahead of  `apt-get install pkg-config`. The former will output nothing for any input. 
In that case, [`setup.py::get_library_config()`](https://github.com/mikeboers/PyAV/blob/78152dc06ce02e2b1fb7354ade115b4a62cc2577/setup.py#L78) would never throw exception but return an dict whose values are all null.
```
import shlex, argparse
_cflag_parser = argparse.ArgumentParser(add_help=False)
_cflag_parser.add_argument('-I', dest='include_dirs', action='append')
_cflag_parser.add_argument('-L', dest='library_dirs', action='append')
_cflag_parser.add_argument('-l', dest='libraries', action='append')
_cflag_parser.add_argument('-D', dest='define_macros', action='append')
_cflag_parser.add_argument('-R', dest='runtime_library_dirs', action='append')

raw_args = ''
raw_args = shlex.split(raw_cflags.strip())
args, unknown = _cflag_parser.parse_known_args(raw_args)
config = {k: v or [] for k, v in args.__dict__.items()}    # {'include_dirs': [], 'library_dirs': [], 'define_macros': [], 'runtime_library_dirs':[], 'libraries': []}
print(bool(config))   # True
print(bool(config.values()))   # False
```
maybe verify the output of `pkg-config` more carefully would be better.
