### ISSUE TITLE
Can i use pyav to built a rtmp retransmit-server?

### ISSUE THREAD

**Issue by ifdandy** [mikeboers/PyAV#171]
hi, i want to make a  retransmit by PyAV, just connect source rtmp server to get live stream data,and transfer the live stream data  to the other servers.
retransmit  processes like : 
anyone-rtmp-server-------get stream----->My Program--------send stream------->my-rtmp-server

how to program it? i can not understand PyAV's API documents,please give me a hand!

thanks very much.

**Comment by TechWhizZ199** [comment]
What will PyAV's function be on the server. As far as I know, PyAV can only deal with media files (e.g. .mp4/.flv/.mp3). 

It doesn't interface with RTMP or any live packets as such.

Maybe be @mikeboers can help you with this?

**Comment by mikeboers** [comment]
@TechWhizZ199 PyAV can use whatever formats/devices that FFmpeg can, which includes streaming media.

@ifdandy I'm not personally familiar with doing this sort of thing. If you aren't modifying the data in any way, straight up FFmpeg should work. If you need PyAV, then you should be able to open the source stream like most of the decoding examples, open the destination stream like the encoding examples, and transfer frames from one to the other. If there is anything missing in PyAV it wouldn't be very large.

**Comment by ifdandy** [comment]
@mikeboers tks,i  actualize it with ffmpeg-cffi-py,and it works.:blush:
@TechWhizZ199 tks

**Comment by TechWhizZ199** [comment]
That library looks really useful @ifdandy. Thanks and I might take a look at it as well.

**Comment by idealhack** [comment]
Hi, all. I'm trying to do something similar, except I want to modify images of frames.

When I read RTMP stream using `av.open('rtmp://[host]/live/stream')`, it's works.

But when I want to write using `av.open('rtmp://[host]/live/stream', 'w')`, it raised an error:

```
[PyAV] python examples/demo.py
Traceback (most recent call last):
  File "examples/demo.py", line 16, in <module>
    output = av.open('rtmp://[host]/live/stream', 'w')
  File "av/container/core.pyx", line 290, in av.container.core.open (src/av/container/core.c:4823)
    return OutputContainer(_cinit_sentinel, file, format, options)
  File "av/container/core.pyx", line 254, in av.container.core.Container.__cinit__ (src/av/container/core.c:4185)
    self.proxy = ContainerProxy(_cinit_sentinel, self)
  File "av/container/core.pyx", line 116, in av.container.core.ContainerProxy.__init__ (src/av/container/core.c:2852)
    raise ValueError("Could not determine output format")
ValueError: Could not determine output format
```

Does PyAV capable to do this?

My Environments:

```
[PyAV] python setup.py doctor
running doctor
running config
running reflect
looking for avformat_open_input... found
looking for pyav_function_should_not_exist... missing
looking for av_calloc... found
looking for av_frame_get_best_effort_timestamp... found
looking for avformat_alloc_output_context2... found
looking for avformat_close_input... found
looking for AVStream.index... found
looking for PyAV.struct_should_not_exist... missing
looking for AVFrame.mb_type... missing

PyAV: 0.3.1 v0.3.1-30-g7b62aeb
Python: 2.7.11 |Anaconda 4.1.0 (x86_64)| (default, Jun 15 2016, 16:09:16) \n[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)]
platform: Darwin-15.6.0-x86_64-i386-64bit
extension_extra:
	libraries: ['avcodec', 'avdevice', 'avfilter', 'avformat', 'avutil', 'swresample', 'swscale']
	library_dirs: ['/usr/local/Cellar/ffmpeg/3.1.1/lib', '/Users/idealhack/anaconda2/lib']
	include_dirs: ['/usr/local/Cellar/ffmpeg/3.1.1/include', 'include', '/Users/idealhack/anaconda2/include/python2.7']
config_macros:
	PYAV_VERSION=0.3.1
	PYAV_VERSION_STR="0.3.1"
	PYAV_COMMIT_STR="v0.3.1-30-g7b62aeb"
	PYAV_HAVE_LIBSWRESAMPLE=1
	PYAV_HAVE_AV_CALLOC=1
	PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=1
	PYAV_HAVE_AVFORMAT_ALLOC_OUTPUT_CONTEXT2=1
	PYAV_HAVE_AVFORMAT_CLOSE_INPUT=1
```

```
[PyAV] ffmpeg -version
ffmpeg version 3.1.1 Copyright (c) 2000-2016 the FFmpeg developers
built with Apple LLVM version 7.3.0 (clang-703.0.31)
configuration: --prefix=/usr/local/Cellar/ffmpeg/3.1.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --enable-librtmp --disable-lzma --enable-vda
libavutil      55. 28.100 / 55. 28.100
libavcodec     57. 48.101 / 57. 48.101
libavformat    57. 41.100 / 57. 41.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 47.100 /  6. 47.100
libavresample   3.  0.  0 /  3.  0.  0
libswscale      4.  1.100 /  4.  1.100
libswresample   2.  1.100 /  2.  1.100
libpostproc    54.  0.100 / 54.  0.100
```

**Comment by idealhack** [comment]
For RTMP decoding and re-encoding, It turns out that the delay of new stream will continuous adds up.

Any ideas, folks?
