### ISSUE TITLE
libavcodec.so.57: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ifdandy** [mikeboers/PyAV#172]
hi, i install pyav successfully,but i run demo and raise ImportError,like these detail:

~~~
/usr/local/bin/python2.7 /root/PycharmProjects/fflive/pyav.py
Traceback (most recent call last):
  File "/root/PycharmProjects/fflive/pyav.py", line 3, in <module>
    import av
  File "/usr/local/lib/python2.7/site-packages/av-0.3.1-py2.7-linux-x86_64.egg/av/__init__.py", line 9, in <module>
    from av._core import time_base, pyav_version as __version__
ImportError: libavcodec.so.57: cannot open shared object file: No such file or directory
~~~

I'm sure of 'libavcodec.so.57' is existed in lib folder of ffmpeg,but i don't how to make it work.

**Comment by mikeboers** [comment]
99% the library isn't in `$LD_LIBRARY_PATH`, either one you have set or the default. Options to solve include making sure FFmpeg is installed into the typical locations, or modifying `LD_LIBRARY_PATH` yourself.
