### ISSUE TITLE
Can't read file after calling stream.seek(0)

### ISSUE THREAD

**Issue by tcwalther** [mikeboers/PyAV#173]
I have a problem on my Linux server that I cannot reproduce on my local Mac machine. I suppose it has to do with the underlying ffmpeg, but I'd appreciate help in debugging the issue further, if possible.

```python
import av
filename = 'example.mp3'
```

The following works:

```python
container = av.open(filename)
stream = next(s for s in container.streams if s.type == b'audio')
for packet in container.demux(stream):
     for frame in packet.decode():
         pass
```

The following doesn't:

```python
container = av.open(filename)
stream = next(s for s in container.streams if s.type == b'audio')
stream.seek(0)
for packet in container.demux(stream):
     for frame in packet.decode():
         pass
```

Output:

```c
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "av/packet.pyx", line 36, in av.packet.Packet.decode (src/av/packet.c:1642)
  File "av/stream.pyx", line 203, in av.stream.Stream.decode (src/av/stream.c:4351)
  File "av/audio/stream.pyx", line 53, in av.audio.stream.AudioStream._decode_one (src/av/audio/stream.c:1991)
  File "av/utils.pyx", line 78, in av.utils.err_check (src/av/utils.c:1528)
AVError: [Errno 1094995529] Invalid data found when processing input
```

The linux server runs CentOS 7, with ffmpeg 3.0.2-git (also tried 3.0.0-git before that), Python 2.7 from Anaconda and pyav 0.3.1. My mac runs ffmpeg 3.0.2 from homebrew (I also tried 2.8.6) and Python 2.7 from Anaconda with pyav 0.3.1. I cannot reproduce the crash on my mac, and it also happens with only one audio file on my server. I can't share the audio file publicly due to copyright restrictions, but I'd be happy to send it to you directly if you want to try to reproduce the problem.

Since it seems difficult to reproduce the problem on other environments, I would welcome suggestions on how to debug this further. Do you have any idea why `stream.seek(0)` would break the decoding? Are there certain things in the header of the mp3 container/stream that I could check for sanity? I had a look at various attributes of `container` and `stream`, but couldn't find anything looking suspiciously different when comparing the problematic file with one that works.

Any ideas?

**Comment by mikeboers** [comment]
@markreidvfx have any ideas?

**Comment by markreidvfx** [comment]
I don't have access to a computer at the moment but does this work?

container = av.open(filename)
stream = next(s for s in container.streams if s.type == b'audio')
for packet in container.demux(stream):
     for frame in packet.decode():
         break

stream.seek(0)

**Comment by mikeboers** [comment]
@tcwalther Please give @markreidvfx's suggestion a try. Not a solution, but might let us isolate the problem. Can you also double check that your FFmpeg versions are exactly the same? You can run `python -m av --version` to get the version it compiled against.

**Comment by markreidvfx** [comment]
It was hard to type from a phone. I really meant to try this:

```python
container = av.open(filename)
stream = next(s for s in container.streams if s.type == b'audio')
for packet in container.demux(stream):
     for frame in packet.decode():
         break

stream.seek(0)

for packet in container.demux(stream):
     for frame in packet.decode():
         pass
```

Some formats are might not populate some data until after a packet has been demuxed or a frame has been decoded, I really can't remember what ones, there some flags the tell you I think.  Does ffplay seek correctly? What is the mp3 library you using with mp3 on linux? Is there anyway we could generate a similar formatted mp3?

**Comment by mikeboers** [comment]
Pending more info, I'm closing this.
