### ISSUE TITLE
Ability to set decoder/codec context without stream

### ISSUE THREAD

**Issue by TechWhizZ199** [mikeboers/PyAV#174]
I believe this would be a follow on if issue number #161 was solved, we would need to set up a custom codec context e.g. FLV1 to decode our own FLV1 packet data.

It would be amazing to have PyAV as a library which can not only decode frames from a complete media file, but also decode frames from live packets which we can just feed into it.

**Comment by mikeboers** [comment]
This is actually #155. Go add a :+1: there? 😜
