### ISSUE TITLE
illegal memory management control operation 32/7/28..

### ISSUE THREAD

**Issue by ifdandy** [mikeboers/PyAV#176]
i have experience this problem，can you help me?
@mikeboers 
![qq 20160615180418](https://cloud.githubusercontent.com/assets/5428774/16075943/a18db78a-3323-11e6-9c6e-489c914859b3.png)

**Comment by mikeboers** [comment]
I don't know what this is.

### TODO:

- [ ] Figure out where this is coming from.
- [ ] ???

**Comment by winger-chan** [comment]
Maybe you can try set 'tune' to 'zerolatency' to fix it.
