### ISSUE TITLE
encoding H.264, bad packets 

### ISSUE THREAD

**Issue by davesc** [mikeboers/PyAV#179]
I have some simple code to pull frames from a video, manipulate them, and then encode them back to video.  When I use 'mpeg4' to encode the output video it works fine (and it's fast! yay!), but when I switch to 'h264', muxing the output packet throws this error:
    **Argument 'packet' has incorrect type (expected av.packet.Packet, got NoneType)**
It looks like the encoding step produces bad packets or none at all, am I missing something here?

the short version of the code: 

```python
# open output video file for writing
output_file = av.open(outputname,'w','mp4')
# add a video stream to the output at 5fps
output_video_stream = output_file.add_stream('h264', 5)

#... a bunch of code to loop through frames, and process images with openCV
    
    # store the numpy array as a frame
    frame_out.planes[0].update(newimg)
    # encode an output frame
    output_packet = output_video_stream.encode(frame_out)
    # code breaks here when using 'h264'
    output_file.mux(output_packet)
```

The h264 encoder works fine when I convert videos using ffmpeg on the command line, so it's there, but not playing well with PyAV.

**Comment by mikeboers** [comment]
H.264 has [B-frames](https://en.wikipedia.org/wiki/Video_compression_picture_types#Bi-directional_predicted_frames.2Fslices_.28B-frames.2Fslices.29), so it has to buffer up a few frames before giving you packets. `Stream.encode()` can give you `None`, and you need to test for that.

**Comment by davesc** [comment]
Hi Mike
thanks for the quick reply!  That solved it.  I was testing with 10 frames,
and that wasn't enough to produce a packet.

cheers
dave
