### ISSUE TITLE
setup.py fails if no git is installed

### ISSUE THREAD

**Issue by FlorianLudwig** [mikeboers/PyAV#184]
The setup.py should work without having git - at least in the source distribution for `pip install av`

**Comment by mikeboers** [comment]
Good point. I'll fix that up next time I do a sprint.

**Comment by pravic** [comment]
Confirm. Also it would be nice to add the `shell=True` for those users who use `git.cmd` instead of `git.exe`.

**Comment by pravic** [comment]
And no shell still? Disappointing though.

**Comment by mikeboers** [comment]
I don't understand why that would help. From the docs:

> On Windows with `shell=True`, the COMSPEC environment variable specifies the default shell. The only time you need to specify `shell=True` on Windows is when the command you wish to execute is built into the shell (e.g. dir or copy). You do not need `shell=True` to run a batch file or console-based executable.

This missing functionality in the build debug reporting is that disappointing to you?
