### ISSUE TITLE
Option to *not* drop damaged frames

### ISSUE THREAD

**Issue by ksze** [mikeboers/PyAV#185]
It appears that when decoding videos, PyAV will automatically drop damaged frames. It would be nice to have an option to _not_ drop them. The ffmpeg command line appears capable of keeping damaged frames anyway.

I have a video (`my_damaged_ffv1.nut`) of this spec:
- 512x424
- 30 fps
- gray16le pixel format
- encoded as FFV1 level 1
  - default GOP 12
  - default context 0
  - coder 1
- nut container

It contains some damaged frames because it was recorded over SMB3 to a NAS. And damaged frames can appear when the ethernet connection is unstable. If I decode the file as rawvideo using the `ffmpeg` command line, `ffmpeg` would output _all_ frames, including damaged ones. The damaged frames would obviously look like garbage, but they would be there.

However, when PyAV decodes the same file, the damaged frames are skipped over. I can tell because there are gaps in the pts and because the resulting SHA1 would be different:

First, let's calculate the SHA1 when the video is decoded by the `ffmpeg` command line:

```
$ ffmpeg -nostats -i my_damaged_ffv1.nut -f rawvideo -pix_fmt gray16le pipe:1 | sha1sum -b
ffmpeg version n2.5.3 Copyright (c) 2000-2015 the FFmpeg developers
  built on Jun 10 2015 19:04:24 with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: --prefix=/usr/local/ --extra-cflags=-I/home/toolchain/ffmpeg_build/include --extra-ldflags=-L/home/toolchain/ffmpeg_build/lib --bindir=/usr/local/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-shared --enable-pic
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 13.100 / 56. 13.100
  libavformat    56. 15.102 / 56. 15.102
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  2.103 /  5.  2.103
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[nut @ 0x1c680e0] no index at the end
[nut @ 0x1c680e0] read_timestamp failed.
    Last message repeated 14 times
Input #0, nut, from 'my_damaged_ffv1.nut':
  Metadata:
    encoder         : Lavf56.15.103
  Duration: 00:03:24.33, start: 0.000000, bitrate: 19573 kb/s
    Stream #0:0: Video: ffv1 (FFV1 / 0x31564646), gray16le, 512x424, 30 fps, 30 tbr, 61440 tbn, 61440 tbc
    Metadata:
      encoder         : Lavc56.14.100 ffv1
Output #0, rawvideo, to 'pipe:1':
  Metadata:
    encoder         : Lavf56.15.102
    Stream #0:0: Video: rawvideo (Y1[0][16] / 0x10003159), gray16le, 512x424, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc
    Metadata:
      encoder         : Lavc56.13.100 rawvideo
Stream mapping:
  Stream #0:0 -> #0:0 (ffv1 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
[nut @ 0x1c680e0] Last frame must have been damaged 261774994 > 261698154 + 32767
[nut @ 0x1c680e0] Last frame must have been damaged 301544673 > 301468680 + 32767
[nut @ 0x1c680e0] Last frame must have been damaged 465955735 > 465877254 + 32767
[nut @ 0x1c680e0] Last frame must have been damaged 466666727 > 466586770 + 32767
my_damaged_ffv1.nut: Invalid data found when processing input
frame= 6131 fps=125 q=0.0 Lsize= 2599544kB time=00:03:24.36 bitrate=104202.2kbits/s dup=3 drop=0
video:2599544kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
dbe7c9b3e07084be0774c9031d642d3c44ff6b64 *-
```

So, according to the last line of that output, the SHA1 of the frame data, when decoded by ffmpeg, is `dbe7c9b3e07084be0774c9031d642d3c44ff6b64`

Now let's decode the same file by PyAV:

``` python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Python standard library
import argparse
import hashlib

# Numpy
import numpy as np

# PyAV
import av

def calculate_sha1(video_path):
    print video_path
    sha1 = hashlib.sha1()

    container = av.open(video_path)

    last_pts = -2048

    count = 0
    for packet in container.demux():
        for frame in packet.decode():
            if isinstance(frame, av.VideoFrame):
                count += 1
                diff = frame.pts - last_pts

                # if the pts differ by more than 1/30 seconds, we have a gap, so print them
                if diff != 2048:
                    print 'last pts={0}, current pts={1}, diff={2}'.format(last_pts, frame.pts, diff)

                last_pts = frame.pts

                sha1.update(np.frombuffer(frame.planes[0], dtype=np.uint16).reshape(424, 512))

    print 'SHA1: {0}'.format(sha1.hexdigest())
    print 'Frames: {0}'.format(count)
    print

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('video', help='The FFV1 video file to check.')
    args = parser.parse_args()
    calculate_sha1(args.video)
```

Let's see the output:

```
$ python ~/check_ffv1.py my_damaged_ffv1.nut
my_damaged_ffv1.nut
No handlers could be found for logger "libav.nut"
last pts=7041024, current pts=7045120, diff=4096
last pts=8108032, current pts=8112128, diff=4096
last pts=12535808, current pts=12539904, diff=4096
SHA1: 87eff3605243bc7a8bb4e5ace94492d12848ceae
Frames: 6128
```

The SHA1 doesn't match what we get from the `ffmpeg` command line. The number of frames returned is also short by 3 frames (6128 frames, compared to 6131 frames reported by `ffmpeg` command line).

For completeness, I have tried re-encoding the damaged ffv1 file:

```
$ ffmpeg -i my_damaged_ffv1.nut -f rawvideo -pix_fmt gray16le pipe:1 | \
ffmpeg -f rawvideo -framerate 30 -s:v 512x424 -pix_fmt gray16le -i pipe:0 -c:v ffv1 -level 3 -coder 1 -context 0 -g 250 -slices 30 -slicecrc 0 -y my_reencoded_ffv1.nut
```

If I decode this re-encoded FFV1 file using PyAV, I get no more skipped pts, the same SHA1 and the same frame count as the ffmpeg command line:

```
$ python check_ffv1.py my_reencoded_ffv1.nut
my_reencoded_ffv1.nut
SHA1: dbe7c9b3e07084be0774c9031d642d3c44ff6b64
Frames: 6131
```

In fact, the same applies also to H.264 video in nut containers.

I'm not sure if this is a container option, demuxer option, or decoder option in the ffmpeg libraries. I'm just hoping that you have a better idea of where the option might be found in the ffmpeg libraries.

**Comment by mikeboers** [comment]
That's interesting. I have a few ideas. I won't be able to look immediately, but can I get a sample to https://www.dropbox.com/request/96jjuIMiVejvhFHshjox ?

Thanks.

**Comment by ksze** [comment]
I just uploaded a sample file. Note that there are in fact close to 100 damaged frames in the sample file, but even ffmpeg only detects 3 of them, probably because this is FFV1 level 1 and there is no built-in CRC, unlike FFV1 level 3, which at least has a slice CRC option.

**Comment by mikeboers** [comment]
Going grep-ping for the error we find:

```
if (!(nut->flags & NUT_PIPE) &&
    avio_tell(bc) > nut->last_syncpoint_pos + nut->max_distance) {
    av_log(s, AV_LOG_ERROR,
           "Last frame must have been damaged %"PRId64" > %"PRId64" + %d\n",
           avio_tell(bc), nut->last_syncpoint_pos, nut->max_distance);
    return AVERROR_INVALIDDATA;
}
```
Looking for references to `NUT_PIPE`, we find the option in the encoder:

```
{ "none",        "Disable syncpoints, low overhead and unseekable", 0,             AV_OPT_TYPE_CONST, {.i64 = NUT_PIPE},      INT_MIN, INT_MAX, E, "syncpoints" },
```

I'm not sure how to influence that for the decoder.

**Comment by ksze** [comment]
Meanwhile, I think I have a simple workaround.

If I look at the re-encoded video file, it *appears* that the ffmpeg command line would take the next *decodable* (not necessarily intact) frame and repeat it as many times as needed to fill in the gap.

e.g. if my video has frames 1 to 10, with frames 5, 6, and 7 being damaged to the point of being undecodable, then I think ffmpeg will output 1, 2, 3, 4, 8, 8, 8, 8, 9, 10; even though frame 8 may also be slightly damaged (but still decodable).

**Comment by mikeboers** [comment]
So, if I understand correctly, it appears the ffmpeg CLI is dropping damaged frames, and duplicating "good" ones to fill the pts gaps?

If so, this falls out of the scope of PyAV's main purpose, although I've been thinking of `av.contrib` package which contains handy things which re-implement what we are used to with the CLI.

**Comment by ksze** [comment]
That sounds reasonable.

I also modified the decode loop in the `calculate_sha1` function above, so it repeats a frame when a pts gap is detected. I can confirm that the ffmpeg command line indeed repeats the next decodable frame to fill in the gap, because now I get a matching number of frames and matching SHA1.

**Comment by jlaine** [comment]
I think this is out of scope and can be implemented by API users. I'm closing this issue, @mikeboers feel free to re-open if you feel this is wrong.
