### ISSUE TITLE
Video synthesized / encoded in PyAV seeks poorly and gives VLC errors.

### ISSUE THREAD

**Issue by aselle** [mikeboers/PyAV#194]
I've attached a script that generates an animated text and encoded it using libx264. It seems to not be setup for seeking properly. When I try to seek it distorts like it is not finding the nearest keyframe. I set frame.pts=None (as one of the example indicates). If I run ffmpeg quickly to re-encode it, it works fine, I'm wondering if there is some option I need to set in the API to mimic ffmpeg command line behavior. It also planes fine in QuickTime player (on Mac OS X). I tried encoding the videos both on Linux Ubuntu 16.04 LTS and also Mac OS.  Let me know if you need more information! Thanks.

```python
import av
import sys
from PIL import Image 
from PIL import ImageDraw
from PIL import ImageFont
import logging
font = ImageFont.truetype("Helvetica.ttf",80)
logging.basicConfig(level=logging.DEBUG)

w,h=1920,1080
out=av.open("test.mov",mode="w",options={"preset":"fast", "crf":"22"})
stream = out.add_stream('libx264', 24)
stream.width = w
stream.height = h
stream.pix_fmt = "yuv420p"
idx = 0
for frame in range(64):
        image = Image.new('RGB', (w, h))
        outframe = av.VideoFrame(w,h, 'rgb24')
        draw=ImageDraw.Draw(image)
        draw.text((10+4*idx,10+4*idx), "Hello", font=font, fill=(0,255,255,255))
        outframe.planes[0].update_from_string(image.tobytes())
	outframe.pts = None
        packet = stream.encode(outframe)
        if packet:
            out.mux(packet)
        idx += 1
    
while True:
    out_packet = stream.encode()
    if out_packet:
        out.mux(out_packet)
    else:
        break
out.close()
```

**Comment by mikeboers** [comment]
Sorry to leave this idle for so long. Instead of letting this linger even longer: I see your behavior, and I don't understand it.

**Comment by mikeboers** [comment]
Removing this line stops the problem -> https://github.com/mikeboers/PyAV/blob/534565e92fbdcbbf5b7e026675cc286565a3dc21/av/video/stream.pyx#L172

Time to go figure out WTF it is supposed to be doing in the first place...

**Comment by mikeboers** [comment]
I don't think it is there for a good reason for this to exist, so I've removed it.

Sorry that took so long, and thank you for submitting an illustrative example upfront.

🎉
