### ISSUE TITLE
Problems installing on Windows...

### ISSUE THREAD

**Issue by IchordeDionysos** [mikeboers/PyAV#199]
Now I've tried it for many hours...
This library seems to be exactly what I need, but unfortunately I'm not able to install it.

Here are some Infos:

We didn't find `avformat_open_input` in the libraries.   We look for it only as a sanity check to make sure the build
PyAV: 0.3.2   
Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]   
platform: Windows-10-10.0.14393   
extension_extra:         
....libraries: ['avformat', 'avcodec', 'avdevice', 'avutil', 'avfilter', 'swscale', 'swresample']         
....extra_link_args: ['/OPT:NOREF']         
....library_dirs: ['c:\\python27\\libs', 'c:\\python27\\PCbuild', 'c:\\python27\\PC\\VS9.0']        
....include_dirs: ['include', 'c:\\python27\\include', 'c:\\python27\\PC']   
config_macros:         
....PYAV_VERSION=0.3.2         
....PYAV_VERSION_STR="0.3.2"         
....PYAV_COMMIT_STR="unknown-commit"         
....inline=__inline         
....PYAV_HAVE_LIBSWRESAMPLE=1

**Comment by caspervdw** [comment]
As of yesterday, `pyav` for windows is available from conda-forge. This reatly simplifies installation as you do not need to compile. If you have anaconda:

    conda install av -c conda-forge

**Comment by pravic** [comment]
However, it is still possible to install PyAV under Windows without conda, you just need to tell compiler where to find ffmpeg libraries.

1. Download FFmpeg ([shared and dev packages](https://ffmpeg.zeranoe.com/builds/))
2. Unpack them somewhere (like C:\ffmpeg)
3. Add paths for compiler:
```cmd
set INCLUDE=%INCLUDE%;c:\ffmpeg\include
set LIB=%LIB%;c:\ffmpeg\lib
set PATH=%PATH%;c:\ffmpeg\bin
```
4. Build PyAV: `python setup.py build`
5. Install it: `python setup.py install`

**Comment by caspervdw** [comment]
Check https://wiki.python.org/moin/WindowsCompilers on how to obtain the right msvc compiler for your windows/python versions.

**Comment by mikeboers** [comment]
@pravic @caspervdw Do we need to improve the docs here?

**Comment by caspervdw** [comment]
@mikeboers Yes if the instructions by @pravis would be included, with steps 3-4 replaced by the `--ffmpeg-dir` option, that might be of help for others wanting to compile the master on windows.

**Comment by pravic** [comment]
Agree.

**Comment by mikeboers** [comment]
I replaced the existing Windows docs with a take on these instructions (and [deployed them](http://mikeboers.github.io/PyAV/installation.html)). Thanks, everyone!
