### ISSUE TITLE
Add conda-forge distribution to docs

### ISSUE THREAD

**Issue by caspervdw** [mikeboers/PyAV#200]
As of yesterday, the PyAV binaries are available on `conda-forge` on all platforms. Do you want to include this in the docs @mikeboers ?

Installation is done as follows:

    conda install av -c conda-forge

**Comment by mikeboers** [comment]
I've had Conda floating around in the GitHub issues for a long time. I want to be convinced. I honestly don't have the time/interest in spending forever learning about it on my own (I mean... I do have the interest, but not for the foreseeable future).

Do you happen to have a recommendation for something that summarizes the awesome of it in this case?

**Comment by mikeboers** [comment]
I think I finally get it, and while I don't 100% believe it is the best solution, it seems like a pretty great one. Enough to at least include in the docs. ;)

**Comment by mikeboers** [comment]
Tell me what you think of https://github.com/mikeboers/PyAV/tree/docs-conda#pyav and https://github.com/mikeboers/PyAV/blob/docs-conda/docs/installation.rst#conda

**Comment by mikeboers** [comment]
I pushed it to master, and updated the docs on RTD.

Cheers, everyone!
