### ISSUE TITLE
Segfault when seeking on MPEG2 files

### ISSUE THREAD

**Issue by caspervdw** [mikeboers/PyAV#201]
Might be related to #163 

Opening, demuxing and decoding of MPEG2 files works fine. However when I do:

    container.seek(<any_timestamp>)  # tested: 0, duration // 2

I always get

    Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

On both Ubuntu and Windows using ffmpeg 2.8.6. 

This happens for all `.vob` files I tested. If necessary I can supply more tracebacks. But I am not really familiar with Cython so please tell me what you need.

**Comment by mikeboers** [comment]
I fixed #169, which could have easily caused this. Can you please check to see if the current master has this behavior, and if so, upload a sample to https://www.dropbox.com/request/i2QiRodA12glULBJYGV6 and re-open this issue?

Cheers,

Mike

**Comment by caspervdw** [comment]
Thanks, I tried, but still the issue is there, for every VOB file I try. Uploading a sample now!

**Comment by caspervdw** [comment]
@mikeboers I can't reopen on this repo

**Comment by mikeboers** [comment]
I confirm that it still crashes:

```
$ python crash.py 
<av.container.streams.StreamContainer object at 0x1006e3170>
Segmentation fault: 11
```

**Comment by mikeboers** [comment]
That should do it. 😄

**Comment by caspervdw** [comment]
Yes I can confirm! Thanks for the fast fix.

**Comment by mikeboers** [comment]
No problem. Now that the other ambiguous segfault is out of the way, it has gotten a ton less intimidating. ;)
