### ISSUE TITLE
video.sample_aspect_ratio returns Fraction(0, 1)

### ISSUE THREAD

**Issue by animetosho** [mikeboers/PyAV#213]
It seems like for most MKV files I try, video.sample_aspect_ratio returns Fraction(0, 1), although I've found some which do give the proper value. I've found that it works on all AVI files I've tried, and sometimes works on MP4s.

The video files are valid, and mediainfo picks up the correct ratio. I thought that perhaps libav itself is the problem, but I've tried on a very new version and I still get the same issue (otherwise I don't know of an easy way to test libav directly).

Note that video.display_aspect_ratio, which appears to be based on sample_aspect_ratio does the same thing.

Used the following commands to perform tests:

	# python
	Python 2.7.13 (default, Jan 19 2017, 14:48:08)
	[GCC 6.3.0 20170118] on linux2
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import av
	>>> container = av.open('test.mp4')
	>>> video = next(s for s in container.streams if s.type == b'video')
	>>> video.width
	640
	>>> video.sample_aspect_ratio
	Fraction(0, 1)
	>>> quit()

PyAV was installed via `pip install av`. Development libraries were pulled via `apt-get` from deb-multimedia.org (and version numbers below are those reported by the repository).  
I get the same result on the following two systems:

~~~
Debian 8.7 amd64 (+backports)
Python 2.7.9
PyAV 0.3.1
libavformat*, libavcodec*, libavdevice*, libavutil*, libswscale*, libavutil*, libswscale*, libavresample*: 2.8.11-dmo1~bpo8+1
~~~
~~~
Debian 9.0 amd64 (testing)
Python 2.7.13
PyAV 0.3.3
libav*: 3.2.4-dmo3
~~~

Can provide samples if it helps.

Thanks for reading and creating the module!

**Comment by mikeboers** [comment]
You can find `sample_aspect_ratio` in the output of `ffprobe`.

I like doing something like `ffprobe -print_format json -show_format -show_streams tests/assets/320x240x4.mov`.

I'm going to close this for now, but if you find that `ffprobe` gives a reasonable value, or you can't get that to work for you, upload a small sample to https://www.dropbox.com/request/jfjlNSKE7BcneTQ0zitm and re-open this.

Cheers,

Mike

**Comment by animetosho** [comment]
Thank you very much for the response!

I've uploaded a file, *38_9930.mkv* which exhibits this behaviour. ffprobe gives "1:1" as the sample aspect ratio, but `video.sample_aspect_ratio` always gives me 0:1 on every environment I try. Do you get the same?

**Comment by mikeboers** [comment]
Same behaviour over here:

```
import av

fh = av.open('/Users/mikeboers/Dropbox/File requests/PyAV #213 Samples/- - - 38_9930.mkv')
video = fh.streams.video[0]

print repr(video.sample_aspect_ratio)
```

then

```
$ python issue213.py 
Fraction(0, 1)
```

**Comment by mikeboers** [comment]
`ffprobe` uses [av_guess_sample_aspect_ratio](https://ffmpeg.org/doxygen/3.2/group__lavf__misc.html#ga0f62da0e809045bb21166013c404ce43) to determine this number; [it looks at](https://ffmpeg.org/doxygen/3.2/libavformat_2utils_8c_source.html#l04736) the stream, the stream's codec, and a frame.

I'm unsure how I would want to expose such a thing. We could at least expose the `sample_aspect_ratio` on all of those objects.

**Comment by animetosho** [comment]
Ah, that makes sense. Appreciate the explanation!

Yeah, I don't mind manually checking both the stream and codec (just check if it == 0 and try the other one), so definitely useful to expose the property. I think it could be helpful to a handy all-in-one function to get the value, for the unaware, but otherwise I don't mind either way.

**Comment by jlaine** [comment]
Actually looking at the current code I believe it does return None, since we consistently use avrational_to_fraction, which returns None if either `num` or `den` are zero. Close?

**Comment by mikeboers** [comment]
Closing.
