### ISSUE TITLE
Create Packet from Encoded Data

### ISSUE THREAD

**Issue by tjcrone** [mikeboers/PyAV#216]
Hello, I am trying to create a packet from encoded data so that I can decode it using PyAV. Is it possible to do this? I've scoured the documentation and unfortunately cannot figure out a way to make this happen. I have raw packet payload as though it was generated by Packet.to_bytes(). Any help you can provide would be greatly appreciated!

**Comment by jbohman** [comment]
Have you solved this? I'm trying the same thing and I can't figure out how to do it.

**Comment by tjcrone** [comment]
I did finally solve this, but I had to use @markreidvfx's fork referenced in #189. He modified the packet code and added encoder and decoder classes so that something like this worked for me:

```
# create packet
packet = av.packet.Packet(len(frame_data))
packet.update_buffer(frame_data)

# setup decoder
decoder = av.Decoder("prores")
decoder.width = 1920
decoder.height = 1080

# decode frame
frame = next(decoder.decode(packet))
```
it would be great to get his pr merged into the main fork.

**Comment by tjcrone** [comment]
Examples of this working to download single frames from a remote video can be found here: https://github.com/tjcrone/pycamhd

**Comment by mikeboers** [comment]
An offshoot of that PR was merged into master. Let me know if it works for you. :)
