### ISSUE TITLE
Drop support for FFmpeg 2.2.4

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#220]
Anyone object to me dropping 2.2.4 from Travis? We will be testing 2.7 to 3.3.

We can stop doing [stuff like this](https://github.com/mikeboers/PyAV/pull/189/commits/8645c79a9e8f5c8a4377e24e2a927d8e73bad270#diff-c7078bc4ed35ae1143510c56c8ee2775R30).

**Comment by markreidvfx** [comment]
I don't object to this.

**Comment by jlaine** [comment]
Even ffmpeg 2.8.x doesn't work as it seems to lack `av_packet_clone`. I have removed the appveyor/ffmpeg 2.8 test as part of https://github.com/mikeboers/PyAV/pull/373

I suggest documenting ffmpeg 3.x is required and closing this issue.

**Comment by mikeboers** [comment]
@jlaine How do I send you a virtual beer for going back and reading all of these old issues?! 😀

**Comment by jlaine** [comment]
Haha, by taking care of yourself. Being an opensource maintainer isn't always fun!
