### ISSUE TITLE
AVStream.codecpar

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#222]
Lots of people are opening issues and/or sending emails that contain:

```
Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
```

Perhaps we should do that.

The warning comes from [mux.c:300](https://ffmpeg.org/doxygen/3.2/mux_8c_source.html#l00300), called from `avformat_init_output`, called from `avformat_write_header`. It is looking at `AVCodecContext.codec_type`, seeing that it is set, and then issuing the warning.

My guess is that it is being set by `avcodec_open2`, as we are manually opening all of the streams before writing the container header. (Oops?) I'm not sure if that actually makes sense.

**Comment by mikeboers** [comment]
Looking at [the example](https://ffmpeg.org/doxygen/3.2/muxing_8c_source.html#l00396) the problem isn't that we set the parameters on AVCodecContext, but just that they weren't also set on the AVStream.codecpar.

This kinda makes sense, as it means that libavformat becomes more isolated from libavcodec. You may not need codec contexts at all for [de]muxing.

**Comment by jlaine** [comment]
My current understanding is that `AVCodecParameters` will give you the parameters it discovered on an input stream. If we need an `AVCodecContext` for use with a stream, we should be allocating it, storing the pointer somewhere, and de-allocating it - and not using AVStream.codec at all.
