### ISSUE TITLE
AVPacket::flags ~ av.Packet.flags

### ISSUE THREAD

**Issue by crackwitz** [mikeboers/PyAV#226]
I'd like to know which frames are keyframes, without having to decode their contents. I'd like to know this so I can seek to the start of a random GOP quickly (and decode it at once). I'd like to do this because I regularly need to read/display frames backwards.

https://www.ffmpeg.org/doxygen/3.2/structAVPacket.html#a437be96a9da675f12caa228a9c81bd82

Someone in freenode/#ffmpeg told me me that AVPacket::flags can tell me this. I'd then just have to iterate over all packets of the video file and collect the PTSes of keyframe packets. I'm ok with PTSes, but indices would be good too; my video files are usually MPEG 2 Transport streams, so no stored index (that I know of).

https://www.ffmpeg.org/doxygen/3.2/group__lavc__packet.html#ga75603d7c2b8adf5829f4fd2fb860168f

However, when I iterate over video.demux(stream), the resulting av.Packets don't have a flags field.

Does this make sense?

**Comment by mikeboers** [comment]
I added a `Packet.is_keyframe` property which checks that flag. Let me know if it works for you!

**Comment by crackwitz** [comment]
thank you, this works for me!

something I noticed: when I seek a stream, it seems to seek to the given DTS (or whatever comes before that), so if I wanted to start decoding from a keyframe, I'd need to remember its DTS rather than its PTS. I figured that out from behavior. It would be nice to have this in the docs too.
