### ISSUE TITLE
looking for AVStream.index... missing

### ISSUE THREAD

**Issue by crackwitz** [mikeboers/PyAV#227]
hi!

trying to build PyAV in Win7 x64, CPython 2.7, zeranoe ffmpeg (dev and shared) freshly downloaded. I got Visual Studio 2015, which I hope it's picking up. I suspect I need a different compiler perhaps? here's the output of python `setup.py build --ffmpeg-dir=P:\ffmpeg`

looking for avformat_open_input... found
looking for pyav_function_should_not_exist... missing
looking for av_calloc... found
looking for av_frame_get_best_effort_timestamp... found
looking for avformat_alloc_output_context2... found
looking for avformat_close_input... found
looking for avcodec_send_packet... found
looking for AVStream.index... missing
looking for PyAV.struct_should_not_exist... missing
looking for AVFrame.mb_type... missing

We didn't find `AVStream__index` in the libraries.
We look for it only as a sanity check to make sure the build
process is working as expected. It is not, so we must abort.

Please open a ticket at https://github.com/mikeboers/PyAV/issues
with the folowing information:

PyAV: 0.3.3 v0.3.2-55-gc7e602a
Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
platform: Windows-7-6.1.7601-SP1
extension_extra:
        libraries: ['avformat', 'avcodec', 'avdevice', 'avutil', 'avfilter', 'swscale', 'swresample']
        extra_link_args: ['/OPT:NOREF']
        library_dirs: ['P:\\ffmpeg\\lib', 'C:\\Python27\\libs', 'C:\\Python27\\PCbuild\\amd64', 'C:\\Python27\\PC\\VS9.0\\amd64']
        include_dirs: ['include', 'P:\\ffmpeg\\include', 'C:\\Python27\\include', 'C:\\Python27\\PC']
config_macros:
        PYAV_VERSION=0.3.3
        PYAV_VERSION_STR="0.3.3"
        PYAV_COMMIT_STR="v0.3.2-55-gc7e602a"
        inline=__inline
        PYAV_HAVE_LIBSWRESAMPLE=1
        PYAV_HAVE_AV_CALLOC=1
        PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=1
        PYAV_HAVE_AVFORMAT_ALLOC_OUTPUT_CONTEXT2=1
        PYAV_HAVE_AVFORMAT_CLOSE_INPUT=1
        PYAV_HAVE_AVCODEC_SEND_PACKET=1`

**Comment by crackwitz** [comment]
btw, it built fine with python36...

I couldn't "activate" the venv because you don't provide a windows-specific activate script, so I just set PATH=C:\python27;C:\python27\scripts;%PATH%

**Comment by crackwitz** [comment]
MSVC9 is missing inttypes.h and stdint.h, so using FFMPEG headers will always be trouble.

I've copied sensible contents of those into `C:\Users\$USER\appData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include`

now it's building and installing properly also for python 2.7. I did `py -2 setup.py install --ffmpeg-dir=P:\ffmpeg` and `py -3 setup.py install --ffmpeg-dir=P:\ffmpeg` which uses the nifty "py" shebang handler that's bundled with cpython 3.x

**Comment by cuckoldfan** [comment]
can you explain the detail for python 2.7 " I've copied sensible contents of those into C:\Users\$USER\appData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include " .

**Comment by crackwitz** [comment]
I can't, unfortunately. I gave up on python 2.7 entirely a while ago. it's getting too old.

I googled for the missing headers and copied seemingly appropriate candidates into the specified directory until the build process made some progress.

**Comment by Kamekameha** [comment]
MSVC9 does not support C99, which is where both `stdint.h` and `inttypes.h` were introduced.

You can workaround this by having headers like [msinttypes](https://github.com/chemeris/msinttypes) visible in your list of included directory paths. Another approach is, presumably if you need more than just `stdint.h`/`inttypes.h`, to compile your extension module with a Mingw32 compiler conformant to your C standard needs (through the `--compiler`/`-c` option of the `build`/`build_ext` commands).

> btw, it built fine with python36...

Official CPython 3+ binaries are built against a more recent MSVC toolchain.

> I've copied sensible contents of those into `C:\Users\$USER\appData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include`

FTR, there's no need to, and more than likely shouldn't, blindly copy files around install directories for this kind of stuff. In this scenario you can simply pass the `--include-dirs`/`-I` option to the `build_ext` command with the directory paths you need included.
