### ISSUE TITLE
Uniform time representation

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#25]
Pick a uniform representation of time to present to the user.

Candidates are:
- rational
- double
- timestamp

**Comment by jlaine** [comment]
I think the way things are handled at the moment are fine : we reflect pts / dts / time_base exactly, and provide the convenience `time` for lazy users :)

**Comment by mikeboers** [comment]
Since this was written, I feel the time handling has gotten quite a bit nicer.

I'd still be keen to see `time` (as a float) be settable. But I don't ever do it because I don't want to decide how to warn the user that it could be a bad idea due to loss of precision due to a bad time_base (not that floats are bad on their own... there is an overkill amount of precision there for realistic cases).

So... if you're reading, you have floating time. If you're writing, you're understanding what is going on. I'm good with that. Lets drop the issue count by one more.
