### ISSUE TITLE
Cant access property flags from frame.pyx

### ISSUE THREAD

**Issue by Litterfeldt** [mikeboers/PyAV#262]
Im trying to add:
```
    property is_corrupt:
        def __get__(self): return bool(self.ptr.flags & lib.AV_FRAME_FLAG_CORRUPT)
```
to `av/frame.pyx`

But upon make it gives the following error:
```
Error compiling Cython file:
------------------------------------------------------------
...
                return avrational_to_faction(&self._time_base)
        def __set__(self, value):
            to_avrational(value, &self._time_base)

    property is_corrupt:
        def __get__(self): return bool(self.ptr.flags & lib.AV_FRAME_FLAG_CORRUPT)
                                              ^
------------------------------------------------------------

av/frame.pyx:125:47: Object of type 'AVFrame' has no attribute 'flags'
```

According to all ffmpeg specification i have found flags should always exist:
https://www.ffmpeg.org/doxygen/2.3/structAVFrame.html

I'm probably doing something stupid, need some help please.

**Comment by mikeboers** [comment]
Cython doesn't know about the property. You have to add it here -> https://github.com/mikeboers/PyAV/blob/master/include/libavcodec/avcodec.pxd#L200-L226

🍻

**Comment by Litterfeldt** [comment]
Spot on, thanks! If I could fax you a beer I would.
