### ISSUE TITLE
Expect enums to exist and catch exceptions

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#275]
See [here](https://github.com/mikeboers/PyAV/commit/d7de8c22d6d0481348dd5c4f17a764acef363163#commitcomment-23975095) (via @Kamekameha).

**Comment by mikeboers** [comment]
I actually kinda want to implement my own enums, so I can use them in the way I've been using strings all over the PyAV codebase, and do so without breaking everyone's code.

Also, because fundamentally, I care more about the string name than the numeric value. The numeric value only means anything to the library, and in the few cases they seem to be different on different platforms.

As an example, I'd want a `MediaType` with `video`, `audio`, `subtitle`, etc.:

```

>>> type_ = MediaType('video')
>>> type_
MediaType('video')

>>> MediaType(1) # or whatever the number is
MediaType('video')

>>> type_ == 'video'
True

>>> type_ == 1 # Maybe not this.
True

>>> type_ == 'VIDEO' # Maybe this.
True

>>> type_ == 'audio'
False

>>> type_ == 'not a type'
...
ValueError: 'not a type' is not a MediaType.

```

That last one is pretty huge to me.

**Comment by Kamekameha** [comment]
PEP435-like enums do support retrieving their members by name, through item access, see https://docs.python.org/3/library/enum.html#programmatic-access-to-enumeration-members-and-their-attributes. Also the name of an enum's members is available as their `name` attribute.

So, if we take your example the changes would be minimal, e.g.:

```python
>>> type_ = MediaType['video']
>>> type_
<MediaType.video: 1>
>>> MediaType(1)
<MediaType.video: 1>
>>> type_.name == 'video'
True
>>> type_ == 1  # if MediaType is an IntEnum (or int, for that matter) subclass
True
>>> type_.name.upper() == 'VIDEO'  # :^)
True
>>> type_ == 'audio'
False
```

Except for your last one, obviously, which definitely requires some implementation.

> Also, because fundamentally, I care more about the string name than the numeric value. The numeric value only means anything to the library, and in the few cases they seem to be different on different platforms.

Quoting from somewhere in the previously linked docs,

> In the vast majority of use-cases, one doesn’t care what the actual value of an enumeration is.

So, in the end, I think that PEP435 enums will surely fulfill the proposed approach you mention above without much, if any, customization.

**Comment by mikeboers** [comment]
I'm still mulling this over. Another thing I'd like to be keyed by name instead of int value is pickling:

```
import pickle
import enum

Test = enum.Enum('Test', dict(FOO=100, BAR=200))
enc = pickle.dumps(Test.FOO)

Test = enum.Enum('Test', dict(FOO=101, BAR=201))

x = pickle.loads(enc)
print(x)
```

results in:

```
ValueError: 100 is not a valid Test
```

I could be wrong, but I feel like a few of the constants have been different on different platforms, or at least between FFmpeg and Libav. That seems kinda silly, TBH, but it is a feeling I have.

**Comment by mikeboers** [comment]
I implemented my own enums a while ago.
