### ISSUE TITLE
AVFrame.mb_type... missing

### ISSUE THREAD

**Issue by trouperk** [mikeboers/PyAV#278]
Received the following message in response to the following command:
---
sudo pip3 install git+https://github.com/pupil-labs/PyAV
---
 Please open a ticket at https://github.com/mikeboers/PyAV/issues
    with the folowing information:
    
    PyAV: 0.3.1 b'v0.3.0-20-ga39a955'
    Python: b'3.5.3 (default, Jan 19 2017, 14:11:04) \\n[GCC 6.3.0 20170124]'
    platform: Linux-4.9.41-v7+-armv7l-with-debian-9.1
    extension_extra:
    	library_dirs: [b'/usr/local/lib']
    	include_dirs: [b'/usr/local/include', b'include', b'/usr/include/python3.5m']
    	libraries: [b'X11', b'avcodec', b'avdevice', b'avfilter', b'avformat', b'avutil', b'm', b'swresample', b'swscale', b'xcb', b'xcb-shape', b'xcb-xfixes', b'z']
    config_macros:
    	PYAV_VERSION=0.3.1
    	PYAV_VERSION_STR="0.3.1"
    	PYAV_COMMIT_STR="b'v0.3.0-20-ga39a955'"
    	PYAV_HAVE_LIBSWRESAMPLE=1
    	PYAV_HAVE_AV_CALLOC=1
    	PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=1

**Comment by jlaine** [comment]
I don't understand what this issue is about, could you please clarify @trouperk ?

**Comment by mikeboers** [comment]
I suspect that it complained about `AVFrame.mb_type` in the reflection process. It is very likely going to be static linking, because it always is.

Please open this back up if you try with newer versions and/or with `python setup.py reflect --force --debug`.

**Comment by trouperk** [comment]
Sorry for the ambiguity. I attempted to execute the command described (the sudo pip3... line) and it returned everything below the line as the error message with instructions. 

I found another way to approach my project, but if I try it again I will follow mikeboers recommendation.
