### ISSUE TITLE
`pip install av` produces the following

### ISSUE THREAD

**Issue by timseries** [mikeboers/PyAV#280]
We didn't find `avformat_open_input` in the libraries.
    We look for it only as a sanity check to make sure the build
    process is working as expected. It is not, so we must abort.
    
    Please open a ticket at https://github.com/mikeboers/PyAV/issues
    with the folowing information:
    
    PyAV: 0.3.3 b''
    Python: b'3.5.2 (default, Nov 17 2016, 17:05:23) \\n[GCC 5.4.0 20160609]'
    platform: Linux-4.4.0-98-generic-x86_64-with-Ubuntu-16.04-xenial
    extension_extra:
    	library_dirs: [b'/usr/local/lib']
    	libraries: [b'X11', b'asound', b'avcodec', b'avdevice', b'avfilter', b'avformat', b'avutil', b'bz2', b'dl', b'jack', b'lzma', b'm', b'nppc', b'nppicc', b'nppig', b'swresample', b'swscale', b'va', b'va-drm', b'va-x11', b'vdpau', b'xcb', b'xcb-render', b'xcb-shape', b'xcb-shm', b'xcb-xfixes', b'z']
    	include_dirs: [b'/usr/local/include', b'include', b'/usr/include/python3.5m', b'/home/tim/venvs/venv_enc/include/python3.5m']
    config_macros:
    	PYAV_VERSION=0.3.3
    	PYAV_VERSION_STR="0.3.3"
    	PYAV_COMMIT_STR="unknown-commit"
    	PYAV_HAVE_LIBSWRESAMPLE=1
    
    ----------------------------------------
Command "/home/tim/venvs/venv_enc/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-u28_0b8_/av/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7hf3ib7h-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/tim/venvs/venv_enc/include/site/python3.5/av" failed with error code 1 in /tmp/pip-build-u28_0b8_/av/

**Comment by mikeboers** [comment]
This is very likely the same as #170, in which FFmpeg is built statically.
