### ISSUE TITLE
Segfault while reading frames from a certain audio file

### ISSUE THREAD

**Issue by refi64** [mikeboers/PyAV#282]
[This is the file](https://upspin.refi64.com/rymg19@gmail.com/pub/misc/somnus.mp3) (Somnus from the FFXV OST).

The segfault happens some time after reading frame 6227/6228 with both the `audio.py` example program (with `-c some-value-greater-than-6228`) or even this simple example:

```python
import av

audio = av.open('somnus.mp3')
stream = next(stream for stream in audio.streams if stream.type == 'audio')
for packet in audio.demux(stream):
    for frame in packet.decode():
        print(frame)
```

**Comment by jlaine** [comment]
No response from submitter, closing.
