### ISSUE TITLE
File descriptors are not closed for `InputContainer`

### ISSUE THREAD

**Issue by pavloivanchyshyn** [mikeboers/PyAV#286]
When we try to open files using:

```
import av
streams = av.open('file.ts').streams
```
It doesn't close file descriptor for `file.ts`. This might raise an `Too many open files:` error.

P.S. OutputContainer works fine in this situation.

**Comment by willfrey** [comment]
This is also an issue for me!

**Comment by jlaine** [comment]
File descriptors should actually be closed by the destructor, can you confirm that the issue is still present in PyAV 6.0.0?

It would be nice to have an explicit `close` method though.

**Comment by mikeboers** [comment]
We did fix up the destructors, but I agree a `close` would be nice.

Closing this to make another one.
