### ISSUE TITLE
Allocate the primary maintainer's time.

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#293]
Hey folks.

This project, like most that I push onto GitHub, are born from needs at my paid jobs. This is 90% of the reason why my attention ebbs and flows, as it is driven by the needs of my clients. (This also explains my focus on video, as I'm generally a Pipeline TD at a VFX or animation company.)

I'm sorry I have not been an active maintainer for a few months now. Meat-space has been a cluster-fuck for me for quite a while now, and for a few months I've been under more financial pressure that normal. Unfortunately, maintaining PyAV doesn't pay the bills unless the client's needs has me do so.

I've been reading every notification GitHub sends me, and stuffing it all into a folder for when I feel I can put some time into this (there are 202 now). There have been a few messages on here in the last few days (and in direct emails) that pull my heartstrings.

I would like to be a more active maintainer, but there are only two ways I can manage it:

1. Pay me (so I can take time away from other paid work).

2. Help me manage my time here to be as effective as possible. I would like to be able to do a small thing here or there, and I would like it to be reasonably efficient. It would be a great help we could, together, prioritize the ~100 open issues, and break them down into reasonable (perhaps hour long) chunks.

Thank you for your understanding and support.

(Summoning recent issue participants: @notedit, @jd20, @willfrey, @pavloivanchyshyn, @czfhhh, @funkybob, @kirbyfan64, @MiguelFRomeroR, @tuxuser, @Schamper, @hhsprings, @koenvo, @adavoudi).

**Comment by notedit** [comment]
hi mike,  
thanks to your hard work.  maintain a open source project  take lots of time.  
i want to  donate,  please  leave some  account.

**Comment by funkybob** [comment]
I'll pile on this one... as a fellow maintainer of open source projects, I know you pain.

Your project has helped me professionally. In return, I will do what I can to help lighten your load (would rather get my client to pay you, but... that's unlikely ):

**Comment by notedit** [comment]
Hi  mike,  

can i be  one of the maintainer of PyAV,   i  do not have so much time, but i can  help with bug fix and pr  
merging.
