### ISSUE TITLE
We didn't find `avformat_open_input` in the libraries

### ISSUE THREAD

**Issue by notedit** [mikeboers/PyAV#294]
ubuntu 18.04    ffmpeg  latest snapshot.

```
looking for avformat_open_input... missing
looking for pyav_function_should_not_exist... missing
looking for av_calloc... found
looking for av_frame_get_best_effort_timestamp... found
looking for avformat_alloc_output_context2... missing
looking for avformat_close_input... missing
looking for avcodec_send_packet... missing
looking for AV_OPT_TYPE_INT...found
looking for PYAV_ENUM_SHOULD_NOT_EXIST...missing
looking for AV_OPT_TYPE_BOOL...found
looking for AVStream.index... found
looking for PyAV.struct_should_not_exist... missing
looking for AVFrame.mb_type... missing

We didn't find `avformat_open_input` in the libraries.
We look for it only as a sanity check to make sure the build
process is working as expected. It is not, so we must abort.

Please open a ticket at https://github.com/mikeboers/PyAV/issues
with the folowing information:

PyAV: 0.4.0.dev0 b'v0.3.3-138-g7d67c1a'
Python: b'3.6.4+ (default, Feb 12 2018, 08:25:03) \\n[GCC 7.3.0]'
platform: Linux-4.9.49-moby-x86_64-with-Ubuntu-18.04-bionic
extension_extra:
	include_dirs: [b'/usr/include', b'include', b'/usr/include/python3.6m']
	libraries: [b'SDL2', b'X11', b'Xext', b'Xv', b'asound', b'avcodec', b'avdevice', b'avfilter', b'avformat', b'avutil', b'bz2', b'crystalhd', b'fdk-aac', b'lzma', b'm', b'mp3lame', b'ogg', b'opus', b'postproc', b'sndio', b'swresample', b'swscale', b'theoradec', b'theoraenc', b'va', b'va-drm', b'va-x11', b'vdpau', b'vorbis', b'vorbisenc', b'vpx', b'x264', b'x265', b'xcb', b'xcb-shape', b'xcb-shm', b'xcb-xfixes', b'xvidcore', b'z', b'zmq']
	library_dirs: [b'/usr/lib']
config_macros:
	PYAV_COMMIT_STR="b'v0.3.3-138-g7d67c1a'"
	PYAV_HAVE_AVCODEC_SEND_PACKET=0
	PYAV_HAVE_AVFORMAT_ALLOC_OUTPUT_CONTEXT2=0
	PYAV_HAVE_AVFORMAT_CLOSE_INPUT=0
	PYAV_HAVE_AVFRAME__MB_TYPE=0
	PYAV_HAVE_AV_CALLOC=1
	PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=1
	PYAV_HAVE_AV_OPT_TYPE_BOOL=1
	PYAV_HAVE_LIBAVRESAMPLE=0
	PYAV_HAVE_LIBSWRESAMPLE=1
	PYAV_VERSION=0.4.0.dev0
	PYAV_VERSION_STR="0.4.0.dev0"
```

**Comment by notedit** [comment]
i  try many ffmpeg compile options on linux,  but still can not make it work. 
 any one has installed latest PyAV on linux?

**Comment by mikeboers** [comment]
If anyone sees this way after the fact, my guess is that there was a linking problem. Newer PyAVs have the ability to dump out more info so you can see what went wrong in the reflection process.

**Comment by yjaycha** [comment]
I'm getting the same error message 

PyAV: 0.4.6 b'v0.4.6'
  Python: b'3.9.2 (default, Feb 19 2021, 17:43:04) \\n[Clang 12.0.0 (clang-1200.0.32.29)]'
  platform: macOS-11.2.1-x86_64-i386-64bit
  extension_extra:
  	include_dirs: [b'/usr/local/Cellar/ffmpeg/4.3.2/include', b'include', b'/usr/local/include', b'/usr/local/opt/openssl@1.1/include', b'/usr/local/opt/sqlite/include', b'/usr/local/opt/tcl-tk/include', b'/Users/yoncha01/Project/git/pupil/pupil_venv/include', b'/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/include/python3.9']
  	libraries: [b'avcodec', b'avdevice', b'avfilter', b'avformat', b'avutil', b'swresample', b'swscale']
  	library_dirs: [b'/usr/local/Cellar/ffmpeg/4.3.2/lib', b'/usr/local/lib', b'/usr/local/opt/openssl@1.1/lib', b'/usr/local/opt/sqlite/lib', b'/usr/local/opt/tcl-tk/lib']
  config_macros:
  	PYAV_COMMIT_STR="b'v0.4.6'"
  	PYAV_HAVE_AVCODEC_SEND_PACKET=0
  	PYAV_HAVE_AVFORMAT_ALLOC_OUTPUT_CONTEXT2=0
  	PYAV_HAVE_AVFORMAT_CLOSE_INPUT=0
  	PYAV_HAVE_AVFRAME__MB_TYPE=0
  	PYAV_HAVE_AV_CALLOC=0
  	PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=0
  	PYAV_HAVE_AV_OPT_TYPE_BOOL=1
  	PYAV_HAVE_LIBAVRESAMPLE=0
  	PYAV_HAVE_LIBSWRESAMPLE=1
  	PYAV_VERSION=0.4.6
  	PYAV_VERSION_STR="0.4.6"
