### ISSUE TITLE
Document backwards incompatibilities

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#297]
Ripping this from #268 before closing it.

- [ ] Document everything backwards incompatible in changelog:
  - [ ] ``Stream.encode`` returns a list of packets, instead of a single packet.
  - [ ] ``AudioFifo`` and ``AudioResampler`` will raise ``ValueError`` if input frames
  inconsistant ``pts``.
  - [ ] ``CodecContext.rate`` has been removed, but proxied to ``VideoCodecContext.framerate``
  and ``AudioCodecContext.sample_rate``. The definition is effectively inverted from
  the old one (i.e. for 24fps it used to be ``1/24`` and is now ``24/1``).
  - [ ] Fractions (e.g. ``time_base``, ``rate``) will be ``None`` if they are invalid.
  - [ ] ``InputContainer.seek`` and ``Stream.seek`` will raise TypeError if given
  a float, when previously they converted it from seconds.

**Comment by jlaine** [comment]
I'm closing this, for the past couple of releases we have correctly documented all API changes.

**Comment by mikeboers** [comment]
Thanks. We don't need to be that held back.
