### ISSUE TITLE
RTSP support

### ISSUE THREAD

**Issue by simobrazz** [mikeboers/PyAV#300]
Hi,

I have some problems with RTSP streaming from an ip camera. The code I use is very simple:
```
container = av.open("rtsp://"+ipAddress+"/")

        for frame in container.decode(video=0):
            image = frame.to_image()
```
Unfortunately after a while it happens that `container.decode(video=0)` is unable to read the input frame. It seems that the image is broken.

It might be a stupid error (sorry in advance).

Any help will be appreciated.

**Comment by axmadjon** [comment]
this work for me 
 import av
 import cv2
 
 video = av.open('rtsp://192.168.10.210:554/', 'r')
 video_stream = next(s for s in video.streams if s.type == 'video') 

 try:
     for packet in video.demux():
         for frame in packet.decode():
             if packet.stream.type == b'video':
                 img = frame.to_nd_array(format='bgr24')
                 cv2.imshow("Test", img)
 
         if cv2.waitKey(1) & 0xFF == ord('q'):
             break
 except KeyboardInterrupt:
     pass

 cv2.destroyAllWindows()

**Comment by simobrazz** [comment]
@axmadjon It seems to work!Thank you!
