### ISSUE TITLE
Problem save mp4 (video/audio) from RTSP

### ISSUE THREAD

**Issue by axmadjon** [mikeboers/PyAV#302]
how can i save video mp4(video and audio) frame in rtsp(ip camera) 
please help

    import av
    import cv2
    
    video = av.open('rtsp://192.168.10.210:554/', 'r')
    video_stream = next(s for s in video.streams if s.type == 'video')
    stream = next(s for s in video.streams if s.type == 'audio')
    
    archive = av.open('archive.mp4', 'w')
    
    archive_stream = archive.add_stream('mpeg4')
    archive_audio_stream = archive.add_stream('mp3')
    
    archive_stream.height = video_stream.height
    archive_stream.width = video_stream.width
    
    for packet in video.demux(video_stream, stream):
        for frame in packet.decode():
            try:
                if packet.stream.type == b'video':
                    print ('show to opencv')
                    img = frame.to_nd_array(format='bgr24')
                    cv2.imshow("Test", img)
    
                    print ('encode to mux')
                    frame = av.VideoFrame.from_ndarray(img, format='bgr24')
                    archive.mux(archive_stream.encode(frame))
    
                elif packet.stream.type == b'audio':
                    archive.mux(archive_audio_stream.encode(frame))
            except Exception as e:
                print ('Error: {}'.format(e))
    
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    
    cv2.destroyAllWindows()
    archive.close()

**Comment by axmadjon** [comment]
when I run the code it first gives me

    Error: 'NoneType' object has no attribute 'update'

such errors!
but after a few cycles it disappears
I think you need to run the code always with the code

    archive_stream = archive.add_stream('mpeg4')
    archive_stream.options = {}
    archive_audio_stream = archive.add_stream('mp3')
    archive_audio_stream.options = {}

and after a few seconds
he shows me such errors
only during audio recording

    Error: Input frame pts 63368 != expected 56640; fix or set to None.
    Error: Input frame pts 63688 != expected 56640; fix or set to None.

and he sometimes stops by himself

    Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

or do not connect to the camera rtsp (ip camera)

OS Ubuntu 16.04
ip camera: hikVision

**Comment by jd20** [comment]
It would be helpful to have a full call stack for the `NoneType` error. The `No handlers could be found for logger` sounds like an environment setup issue, I've never seen that before. Might help to explain how you installed PyAV (what `pip` command, or if you built yourself).

As far as recording RTSP to a file, here's a sample code below that does exactly that. It works for me, tested with a Hikvision camera (my URL is slightly different from yours, because my camera has multiple streams, I don't know if your URL could be causing some of the issues you're seeing or not, I always find it best to sanity check the RTSP URL first with a tool like ffplay).

I'm doing this without audio, but if you can get video working, you should be able to add audio stream without much difficulty.

```python
import av

def encode(frame):
    try:
        pkt = ovstream.encode(frame)
    except Exception:
        return False
    if pkt is not None:
        try:
            output.mux(pkt)
        except Exception:
            print('mux failed: ' + str(pkt))
    return True

input_file = 'rtsp://192.168.10.210:554/Streaming/Channels/102?transportmode=unicast'
container = av.open(input_file)
video_st = container.streams.video[0]
output = av.open('archive.mp4', 'w')
ovstream = output.add_stream('libx264', video_st.rate)
ovstream.pix_fmt = 'yuv420p'
ovstream.width = video_st.width
ovstream.height = video_st.height

counter = 0
for packet in container.demux((video_st,)):
    for frame in packet.decode():
        new_frame = av.VideoFrame(width=frame.width, height=frame.height, format=frame.format.name)
        for i in range(len(frame.planes)):
            new_frame.planes[i].update(frame.planes[i])
        encode(new_frame)
        counter += 1
        print("Frames encoded:", counter)
    if counter > 200:
        break

while True:
    if not encode(None):
        break
output.close()
```

**Comment by axmadjon** [comment]
@jd20 thanks for your reply

as shown in the documentation

[PyAV ubuntu](http://mikeboers.github.io/PyAV/installation.html#ubuntu-14-04-lts)
    
    # General dependencies
    sudo apt-get install -y python-dev pkg-config

    # Library components
    sudo apt-get install -y \
        libavformat-dev libavcodec-dev libavdevice-dev \
        libavutil-dev libswscale-dev libavresample-dev libavfilter-dev

[PyAV PIP](http://mikeboers.github.io/PyAV/installation.html#pyav)
 
    pip install av

the solution is found in the following problems

This problem was solved with the help of
 
    problem
    Error: 'NoneType' object has no attribute 'update'

    solution
    stream.options = {}

in the tests was a proposal from the logs
    
    problem
    Error: Input frame pts 63368 != expected 56640; fix or set to None.
    Error: Input frame pts 63688 != expected 56640; fix or set to None.

    solution
    frame.pts = None


but could not find the following problems

    No handlers could be found for logger "libav.�"

and 

    Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by axmadjon** [comment]
one problem opened twice (duplicate)
The last two problems can be seen in more detail [this Isssue](https://github.com/mikeboers/PyAV/issues/305)

**Comment by alexhutnik** [comment]
@jd20 your code example is great! Is there a way to do it without decoding and re-encoding each frame? My Hikvision camera already outputs in h264 so wouldn’t it be more efficient to grab the packets as they come off the rtsp stream and put them directly in to the output file?

**Comment by mikeboers** [comment]
@alexhutnik You can take the packets from one container, and mux them into another container without decoding them.

There is an overly complex example at https://github.com/mikeboers/PyAV/blob/develop/scratchpad/remux.py

I just spent the last few hours writing code to remux the h.265 from my cameras. It works well. Let me know if you need a simple example (I’m not at my computer right now).

Mike

**Comment by alexhutnik** [comment]
Mike this is a great example! Thank you very much. One thing I want to do is write my camera stream to a file for an hour then roll to a new file so that I can create hour-long segments (just like the segments options in ffmpeg). I’m curious how or if the pts should be manipulated so that each segment file has sane seek behavior. 

Also, I would be happy to discuss this in a new issue or some other forum if you prefer.

**Comment by alexhutnik** [comment]
@mikeboers I've simplified your remux example to the following:

```
import av

source = av.open('rtsp://path/to/rtsp', metadata_encoding='utf-8')
output = av.open('test-2-temp.mp4', mode='w', format='h264')

in_to_out = {}

for i, stream in enumerate(source.streams):

    if (
            (stream.type == 'audio') or
            (stream.type == 'video') or
            (stream.type == 'subtitle') or
            (stream.type == 'data')
    ):
        in_to_out[stream] = ostream = output.add_stream(template=stream)
        ostream.options = {}

count = 0
for i, packet in enumerate(source.demux()):
    try:
        if packet.dts is None:
            continue

        packet.stream = in_to_out[packet.stream]
        output.mux(packet)
        count += 1
        if count > 200:
            break

    except InterruptedError:
        output.close()
        break

output.close()
```

So basically read from a stream until 200 packets are reached, then end. That way I can inspect the results.  And what I've found is that the video file seems unplayable in VLC.  I was able to "transcode" the output video into a better container.  You can see me inspecting the before and after here.

Before:

```
[~/Code/camerautils] [master *]$ ffmpeg -i test.mp4
ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-librsvg --enable-libtheora --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libsoxr --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-libjack --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libxcb --disable-libxcb-shm --disable-libxcb-xfixes --disable-indev=jack --enable-opencl --disable-outdev=xv --enable-audiotoolbox --enable-videotoolbox --enable-sdl2 --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/cc --arch=x86_64 --enable-x86asm --enable-libx265 --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid --enable-nonfree --enable-libfdk-aac
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[h264 @ 0x7fc5be812c00] error while decoding MB 121 14, bytestream -9
[h264 @ 0x7fc5be812c00] concealing 13536 DC, 13536 AC, 13536 MV errors in I frame
Input #0, h264, from 'test.mp4':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 2688x1520, 20 fps, 20 tbr, 1200k tbn, 40 tbc
At least one output file must be specified`
```

After:

```
[~/Code/camerautils] [master *]$ ffmpeg -i test-2.mp4
ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-librsvg --enable-libtheora --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libsoxr --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-libjack --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libxcb --disable-libxcb-shm --disable-libxcb-xfixes --disable-indev=jack --enable-opencl --disable-outdev=xv --enable-audiotoolbox --enable-videotoolbox --enable-sdl2 --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/cc --arch=x86_64 --enable-x86asm --enable-libx265 --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid --enable-nonfree --enable-libfdk-aac
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test-2.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 00:00:10.05, start: 0.000000, bitrate: 9485 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc), 2688x1520, 9482 kb/s, 20 fps, 20 tbr, 10240 tbn, 40 tbc (default)
    Metadata:
      handler_name    : VideoHandler
At least one output file must be specified
```

You'll notice in the after, there's a duration, bit rate, etc that are not in the before. Any ideas?

**Comment by alexhutnik** [comment]
@mikeboers Sorry for the multiple replies but I think I have figured this out for myself.  The trick is to set the output format to 'mp4' and to rewrite the pts and dts of the very first packet I get from my RTSP stream and let the output stream take care of rescaling them.  For some reason, the first packet has a dts and pts of 27000 and then the next packet resets to smaller but monotonically increasing values for those timestamps.  Additionally I patched pyav locally to deal with codec_context not having an options map.  All is right with the world now.

Here's what I have now:
```
import av

source = av.open('rtsp://path/to/stream', metadata_encoding='utf-8')
output = av.open('test-%s.mp4' % datetime.now(), mode='w', format='mp4')

in_to_out = {}

for i, stream in enumerate(source.streams):

    if (
            (stream.type == 'audio') or
            (stream.type == 'video') or
            (stream.type == 'subtitle') or
            (stream.type == 'data')
    ):
        in_to_out[stream] = ostream = output.add_stream(template=stream)

count = 0
first_packet = True
try:
    for i, packet in enumerate(source.demux()):
        if first_packet:
            packet.pts = 0
            packet.dts = 0
            first_packet = False

        if packet.dts is None:
            continue

        packet.stream = in_to_out[packet.stream]
        output.mux(packet)
        count += 1
        if count > 200:
            break

except KeyboardInterrupt:
    output.close()
except InterruptedError:
    output.close()

output.close()
```

**Comment by viskoo** [comment]
@alexhutnik when i split the file i had to rewrite all dts/pts, not just the first, in order to properly produce mp4 file.

**Comment by alexhutnik** [comment]
@viskoo I apologize - I was not very clear in my original comment.  I have to rewrite the pts/dts of the very first frame that comes in the stream because they are non-zero.  Then they become monotonically increasing after.  Then, when I split to a new file, I have to adjust down _all_ pts/dts to mimic ffmpeg's `reset_timestamps` flag.

**Comment by viskoo** [comment]
Can you please provide an example how do you do it?
