### ISSUE TITLE
Can not install PyAV on Win10 

### ISSUE THREAD

**Issue by FreemanZ** [mikeboers/PyAV#310]
```
 We didn't find `avformat_open_input` in the libraries.
    We look for it only as a sanity check to make sure the build
    process is working as expected. It is not, so we must abort.

    Please open a ticket at https://github.com/mikeboers/PyAV/issues
    with the folowing information:

    PyAV: 0.4.0 (unknown commit)
    Python: b'3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]'
    platform: Windows-10-10.0.16299-SP0
    extension_extra:
        library_dirs: [b'c:\\python35\\libs', b'c:\\python35\\PCbuild\\amd64']
        include_dirs: [b'include', b'c:\\python35\\include', b'c:\\python35\\include']
        extra_link_args: [b'/OPT:NOREF']
        libraries: [b'avformat', b'avcodec', b'avdevice', b'avutil', b'avfilter', b'swscale', b'swresample']
    config_macros:
        PYAV_COMMIT_STR="unknown-commit"
        PYAV_HAVE_AVCODEC_SEND_PACKET=0
        PYAV_HAVE_AVFORMAT_ALLOC_OUTPUT_CONTEXT2=0
        PYAV_HAVE_AVFORMAT_CLOSE_INPUT=0
        PYAV_HAVE_AVFRAME__MB_TYPE=0
        PYAV_HAVE_AV_CALLOC=0
        PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=0
        PYAV_HAVE_AV_OPT_TYPE_BOOL=0
        PYAV_HAVE_LIBAVRESAMPLE=0
        PYAV_HAVE_LIBSWRESAMPLE=1
        PYAV_VERSION=0.4.0
        PYAV_VERSION_STR="0.4.0"
        inline=__inline

    ----------------------------------------
Command "c:\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\axros\\AppData\\Local\\Temp\\pip-install-u8t4vvk5\\av\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\axros\AppData\Local\Temp\pip-record-sp93945n\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\axros\AppData\Local\Temp\pip-install-u8t4vvk5\av\

```

**Comment by FreemanZ** [comment]
ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100

**Comment by FreemanZ** [comment]
`C:\Users\axros\PyAV>python setup.py build --ffmpeg-dir=C:\Users\axros\ffmpeg
running build
running build_py
creating build\lib.win-amd64-3.5
creating build\lib.win-amd64-3.5\av
copying av\__init__.py -> build\lib.win-amd64-3.5\av
copying av\__main__.py -> build\lib.win-amd64-3.5\av
creating build\lib.win-amd64-3.5\av\audio
copying av\audio\__init__.py -> build\lib.win-amd64-3.5\av\audio
creating build\lib.win-amd64-3.5\av\codec
copying av\codec\__init__.py -> build\lib.win-amd64-3.5\av\codec
creating build\lib.win-amd64-3.5\av\container
copying av\container\__init__.py -> build\lib.win-amd64-3.5\av\container
creating build\lib.win-amd64-3.5\av\data
copying av\data\__init__.py -> build\lib.win-amd64-3.5\av\data
creating build\lib.win-amd64-3.5\av\filter
copying av\filter\__init__.py -> build\lib.win-amd64-3.5\av\filter
creating build\lib.win-amd64-3.5\av\subtitles
copying av\subtitles\__init__.py -> build\lib.win-amd64-3.5\av\subtitles
creating build\lib.win-amd64-3.5\av\video
copying av\video\__init__.py -> build\lib.win-amd64-3.5\av\video
running build_ext
running reflect
running config
looking for avformat_open_input... C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" /Tcbuild\temp.win-amd64-3.5\reflection\avformat_open_input.c /Fobuild\temp.win-amd64-3.5\reflection\avformat_open_input.obj
avformat_open_input.c
build\temp.win-amd64-3.5\reflection\avformat_open_input.c(3): warning C4013: “avformat_open_input”未定义；假设外部返回 int
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Users\axros\ffmpeg /LIBPATH:C:\Python35\libs /LIBPATH:C:\Python35\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" /LIBPATH:C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319 "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" avformat.lib avcodec.lib avdevice.lib avutil.lib avfilter.lib swscale.lib swresample.lib build\temp.win-amd64-3.5\reflection\avformat_open_input.obj /OUT:build\temp.win-amd64-3.5\reflection\avformat_open_input.out.exe
LINK : fatal error LNK1181: 无法打开输入文件“avformat.lib”
missing
looking for pyav_function_should_not_exist... C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" /Tcbuild\temp.win-amd64-3.5\reflection\pyav_function_should_not_exist.c /Fobuild\temp.win-amd64-3.5\reflection\pyav_function_should_not_exist.obj
pyav_function_should_not_exist.c
build\temp.win-amd64-3.5\reflection\pyav_function_should_not_exist.c(3): warning C4013: “pyav_function_should_not_exist”未定义；假设外部返回 int
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Users\axros\ffmpeg /LIBPATH:C:\Python35\libs /LIBPATH:C:\Python35\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" /LIBPATH:C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319 "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" avformat.lib avcodec.lib avdevice.lib avutil.lib avfilter.lib swscale.lib swresample.lib build\temp.win-amd64-3.5\reflection\pyav_function_should_not_exist.obj /OUT:build\temp.win-amd64-3.5\reflection\pyav_function_should_not_exist.out.exe
LINK : fatal error LNK1181: 无法打开输入文件“avformat.lib”
missing
looking for av_calloc... C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" /Tcbuild\temp.win-amd64-3.5\reflection\av_calloc.c /Fobuild\temp.win-amd64-3.5\reflection\av_calloc.obj
av_calloc.c
build\temp.win-amd64-3.5\reflection\av_calloc.c(3): warning C4013: “av_calloc”未定义；假设外部返回 int
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Users\axros\ffmpeg /LIBPATH:C:\Python35\libs /LIBPATH:C:\Python35\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" /LIBPATH:C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319 "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" avformat.lib avcodec.lib avdevice.lib avutil.lib avfilter.lib swscale.lib swresample.lib build\temp.win-amd64-3.5\reflection\av_calloc.obj /OUT:build\temp.win-amd64-3.5\reflection\av_calloc.out.exe
LINK : fatal error LNK1181: 无法打开输入文件“avformat.lib”
missing
looking for av_frame_get_best_effort_timestamp... C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" /Tcbuild\temp.win-amd64-3.5\reflection\av_frame_get_best_effort_timestamp.c /Fobuild\temp.win-amd64-3.5\reflection\av_frame_get_best_effort_timestamp.obj
av_frame_get_best_effort_timestamp.c
build\temp.win-amd64-3.5\reflection\av_frame_get_best_effort_timestamp.c(3): warning C4013: “av_frame_get_best_effort_timestamp”未定义；假设外部返回 int
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Users\axros\ffmpeg /LIBPATH:C:\Python35\libs /LIBPATH:C:\Python35\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" /LIBPATH:C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319 "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" avformat.lib avcodec.lib avdevice.lib avutil.lib avfilter.lib swscale.lib swresample.lib build\temp.win-amd64-3.5\reflection\av_frame_get_best_effort_timestamp.obj /OUT:build\temp.win-amd64-3.5\reflection\av_frame_get_best_effort_timestamp.out.exe
LINK : fatal error LNK1181: 无法打开输入文件“avformat.lib”
missing
looking for avformat_alloc_output_context2... C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" /Tcbuild\temp.win-amd64-3.5\reflection\avformat_alloc_output_context2.c /Fobuild\temp.win-amd64-3.5\reflection\avformat_alloc_output_context2.obj
avformat_alloc_output_context2.c
build\temp.win-amd64-3.5\reflection\avformat_alloc_output_context2.c(3): warning C4013: “avformat_alloc_output_context2”未定义；假设外部返回 int
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Users\axros\ffmpeg /LIBPATH:C:\Python35\libs /LIBPATH:C:\Python35\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" /LIBPATH:C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319 "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" avformat.lib avcodec.lib avdevice.lib avutil.lib avfilter.lib swscale.lib swresample.lib build\temp.win-amd64-3.5\reflection\avformat_alloc_output_context2.obj /OUT:build\temp.win-amd64-3.5\reflection\avformat_alloc_output_context2.out.exe
LINK : fatal error LNK1181: 无法打开输入文件“avformat.lib”
missing
looking for avformat_close_input... C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" /Tcbuild\temp.win-amd64-3.5\reflection\avformat_close_input.c /Fobuild\temp.win-amd64-3.5\reflection\avformat_close_input.obj
avformat_close_input.c
build\temp.win-amd64-3.5\reflection\avformat_close_input.c(3): warning C4013: “avformat_close_input”未定义；假设外部返回 int
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Users\axros\ffmpeg /LIBPATH:C:\Python35\libs /LIBPATH:C:\Python35\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" /LIBPATH:C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319 "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" avformat.lib avcodec.lib avdevice.lib avutil.lib avfilter.lib swscale.lib swresample.lib build\temp.win-amd64-3.5\reflection\avformat_close_input.obj /OUT:build\temp.win-amd64-3.5\reflection\avformat_close_input.out.exe
LINK : fatal error LNK1181: 无法打开输入文件“avformat.lib”
missing
looking for avcodec_send_packet... C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" /Tcbuild\temp.win-amd64-3.5\reflection\avcodec_send_packet.c /Fobuild\temp.win-amd64-3.5\reflection\avcodec_send_packet.obj
avcodec_send_packet.c
build\temp.win-amd64-3.5\reflection\avcodec_send_packet.c(3): warning C4013: “avcodec_send_packet”未定义；假设外部返回 int
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Users\axros\ffmpeg /LIBPATH:C:\Python35\libs /LIBPATH:C:\Python35\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" /LIBPATH:C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319 "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" avformat.lib avcodec.lib avdevice.lib avutil.lib avfilter.lib swscale.lib swresample.lib build\temp.win-amd64-3.5\reflection\avcodec_send_packet.obj /OUT:build\temp.win-amd64-3.5\reflection\avcodec_send_packet.out.exe
LINK : fatal error LNK1181: 无法打开输入文件“avformat.lib”
missing
looking for AV_OPT_TYPE_INT...C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iinclude -IC:\Users\axros\ffmpeg -IC:\Python35\include -IC:\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" /Tcbuild\temp.win-amd64-3.5\reflection\AV_OPT_TYPE_INT.c /Fobuild\temp.win-amd64-3.5\reflection\AV_OPT_TYPE_INT.obj
AV_OPT_TYPE_INT.c
c:\users\axros\ffmpeg\libavutil\common.h(45): fatal error C1083: 无法打开包括文件: “libavutil/avconfig.h”: No such file or directory
missing
looking for PYAV_ENUM_SHOULD_NOT_EXIST...C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iinclude -IC:\Users\axros\ffmpeg -IC:\Python35\include -IC:\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" /Tcbuild\temp.win-amd64-3.5\reflection\PYAV_ENUM_SHOULD_NOT_EXIST.c /Fobuild\temp.win-amd64-3.5\reflection\PYAV_ENUM_SHOULD_NOT_EXIST.obj
PYAV_ENUM_SHOULD_NOT_EXIST.c
c:\users\axros\ffmpeg\libavutil\common.h(45): fatal error C1083: 无法打开包括文件: “libavutil/avconfig.h”: No such file or directory
missing
looking for AV_OPT_TYPE_BOOL...C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iinclude -IC:\Users\axros\ffmpeg -IC:\Python35\include -IC:\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" /Tcbuild\temp.win-amd64-3.5\reflection\AV_OPT_TYPE_BOOL.c /Fobuild\temp.win-amd64-3.5\reflection\AV_OPT_TYPE_BOOL.obj
AV_OPT_TYPE_BOOL.c
c:\users\axros\ffmpeg\libavutil\common.h(45): fatal error C1083: 无法打开包括文件: “libavutil/avconfig.h”: No such file or directory
missing
looking for AVStream.index... C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iinclude -IC:\Users\axros\ffmpeg -IC:\Python35\include -IC:\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" /Tcbuild\temp.win-amd64-3.5\reflection\AVStream.index.c /Fobuild\temp.win-amd64-3.5\reflection\AVStream.index.obj
AVStream.index.c
c:\users\axros\ffmpeg\libavutil\common.h(45): fatal error C1083: 无法打开包括文件: “libavutil/avconfig.h”: No such file or directory
missing
looking for PyAV.struct_should_not_exist... C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iinclude -IC:\Users\axros\ffmpeg -IC:\Python35\include -IC:\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" /Tcbuild\temp.win-amd64-3.5\reflection\PyAV.struct_should_not_exist.c /Fobuild\temp.win-amd64-3.5\reflection\PyAV.struct_should_not_exist.obj
PyAV.struct_should_not_exist.c
c:\users\axros\ffmpeg\libavutil\common.h(45): fatal error C1083: 无法打开包括文件: “libavutil/avconfig.h”: No such file or directory
missing
looking for AVFrame.mb_type... C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iinclude -IC:\Users\axros\ffmpeg -IC:\Python35\include -IC:\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" /Tcbuild\temp.win-amd64-3.5\reflection\AVFrame.mb_type.c /Fobuild\temp.win-amd64-3.5\reflection\AVFrame.mb_type.obj
AVFrame.mb_type.c
c:\users\axros\ffmpeg\libavutil\common.h(45): fatal error C1083: 无法打开包括文件: “libavutil/avconfig.h”: No such file or directory
missing

We didn't find `AV_OPT_TYPE_INT` in the libraries.
We look for it only as a sanity check to make sure the build
process is working as expected. It is not, so we must abort.

Please open a ticket at https://github.com/mikeboers/PyAV/issues
with the folowing information:

PyAV: 0.4.1.dev0 (unknown commit)
Python: b'3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]'
platform: Windows-10-10.0.16299-SP0
extension_extra:
        include_dirs: [b'include', b'C:\\Users\\axros\\ffmpeg', b'C:\\Python35\\include', b'C:\\Python35\\include']
        extra_link_args: [b'/OPT:NOREF']
        library_dirs: [b'C:\\Users\\axros\\ffmpeg', b'C:\\Python35\\libs', b'C:\\Python35\\PCbuild\\amd64']
        libraries: [b'avformat', b'avcodec', b'avdevice', b'avutil', b'avfilter', b'swscale', b'swresample']
config_macros:
        PYAV_COMMIT_STR="unknown-commit"
        PYAV_HAVE_AVCODEC_SEND_PACKET=0
        PYAV_HAVE_AVFORMAT_ALLOC_OUTPUT_CONTEXT2=0
        PYAV_HAVE_AVFORMAT_CLOSE_INPUT=0
        PYAV_HAVE_AVFRAME__MB_TYPE=0
        PYAV_HAVE_AV_CALLOC=0
        PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=0
        PYAV_HAVE_AV_OPT_TYPE_BOOL=0
        PYAV_HAVE_LIBAVRESAMPLE=0
        PYAV_HAVE_LIBSWRESAMPLE=1
        PYAV_VERSION=0.4.1.dev0
        PYAV_VERSION_STR="0.4.1.dev0"
        inline=__inline`

**Comment by mikeboers** [comment]
If this were Linux, I'd say that it was very likely that PyAV was trying to link against the static libraries instead of dynamic.

I'm not familiar with Windows build problems. You closed the issue, which I hope means you solved it. What was it?

**Comment by joshferns** [comment]
@FreemanZ  how did you eventually solve this?
I'm stuck at the same error.

**Comment by tschoepflin** [comment]
I was able to get past this by downloading the correct version of FFMPEG ("dev"), which has folders "include" and "lib".  These are necessary to do the build.  

I got this error when I was pointing to a folder containing the static executable and looking back, of course that won't work.

**Comment by Res260** [comment]
With @tschoepflin 's comment, I was able to install `av` with `pip install av`. It can be downloaded here: https://ffmpeg.zeranoe.com/builds/

I needed to put the content of the include directory in `<PYTHON_DIRECTORY>/include` and the content of the `lib` directory in `<PYTHON_DIRECTORY>/libs` (don't forget the `s`). The build was then successful.

**Comment by quentin-dietz** [comment]
The zeranoe website appears to be offline, however archive.org has a copy which allows you to download the builds:

https://web.archive.org/web/20200918191847/https://ffmpeg.zeranoe.com/builds/
