### ISSUE TITLE
[question] How to set options to decoder?

### ISSUE THREAD

**Issue by animetosho** [mikeboers/PyAV#312]
Hi, sorry for the question, but I couldn't find the answer in the documentation.

I'm looking to set a libavcodec option, [this one in particular](https://github.com/mpv-player/mpv/blob/c15af6630f8ea7bc17d6041aec89bca59209814a/video/decode/vd_lavc.c#L632) but couldn't see how. I notice there's a `codec_context.options` dictionary, but my quick testing didn't seem to do it (also not sure if it's the same thing, as it seems to go to the last arg in `avcodec_open2`). Can this be currently done?  
Unfortunately, without this option, some videos [are horribly broken](https://github.com/mpv-player/mpv/issues/4559).

Also, is there an interface to catch decoder warnings? It seems like these just get dumped to stderr - this can be redirected, but was wondering if there was a nicer way of doing it built-in.  
My plan of action being that if specific warnings are generated (and the video has the right properties), retry decoding it using the flag above.

Thanks for reading and thanks for PyAV!

**Comment by animetosho** [comment]
I've spent some time looking at this now, and this is what I've found:

The `x264_build` option is only available in libavcodec58, but PyAV doesn't seem to compile against it (any interest in supporting it?). Forcing the build through (by essentially deleting lines giving compile errors), I'm able to set the option with existing functionality in PyAV, something like the following seems to work for me:

~~~
container = av.open('video.mkv', options={'x264_build': '150'})
video = container.streams[0]

# specifying x264_build above doesn't seem to be necessary, but does suppress an error; the following is what seems to be needed to get it to work
video.close()
video.codec_context.options = {'x264_build':'150'}
video.open()
~~~

So I guess the issues I'm now interested in:

* would you be able to add support for compiling against libav*58?
* is there any way to capture warnings without redirecting stderr?

**Comment by mikeboers** [comment]
The options are there, but currently quite awkward to work with. Seems like you forced though it.

There is an FFmpeg 4.0 now?! I'd like to support that. I think our tests currently only pass in 3.3, so we're behind a bit.

About the warnings: FFmpeg's logs are passed through the Python logging system, so you could add a custom log handler to catch them. The [`feature/dump_format`](https://github.com/mikeboers/pyav/tree/feature/dump_format) branch has some machinery to directly capture FFmpeg logs. That could be merged in without a lot of trouble.

**Comment by animetosho** [comment]
That sounds great! Thanks for the info.

**Comment by mikeboers** [comment]
I've made a pair of tickets to continue the tangential discussions, and am closing this. Re-open if we haven't addressed what we need to. Thanks!
