### ISSUE TITLE
Unplayable MKV files

### ISSUE THREAD

**Issue by mic159** [mikeboers/PyAV#313]
I'm having some trouble writing a valid MKV file when inside docker.

I have a sample script, and it works fine on ubuntu, but in a debian docker container the output video file isnt playable.
Mediainfo reports no streams, and says `IsTruncated: Yes`.
VLC wont play it, neither will gstreamer.

Sample script:

```python
import av

input = av.open('rtsp://10.10.1.19/unicast', mode='r')
output = av.open('test_docker.mkv', mode='w')

video_stream = input.streams.video[0]
output_video_stream = output.add_stream(template=video_stream)
output_video_stream.options = {}
output.start_encoding()

for packet in input.demux(video=0):
    output.mux(packet)
```

Dockerfile (`python:3.6-stretch` based):

```
FROM python:3.6-stretch

ENV PYTHONUNBUFFERED 1

RUN apt-get -qq update
RUN apt-get install -q -y python-dev pkg-config
RUN apt-get install -q -y \
    libavformat-dev libavcodec-dev libavdevice-dev \
    libavutil-dev libswscale-dev libavresample-dev libavfilter-dev

# Requirements have to be pulled and installed here, otherwise caching won't work
RUN pip install pipenv
COPY ./Pipfile /Pipfile
COPY ./Pipfile.lock /Pipfile.lock

RUN pipenv install --deploy --system

RUN groupadd -r django && useradd -r --uid 1000 --create-home -g django django
ADD . /app

WORKDIR /app
```

mediainfo output:

```
General
Complete name                            : test_docker.mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 1 018 KiB
IsTruncated                              : Yes
```

Versions:

Ubuntu 17.10
Docker version 18.03.0-ce, build 0520e24

Dependency | Ubuntu (working) | Docker (broken)
----------------- | ---------------------- | ---------------------
libavformat-dev | 7:3.3.4-2 | 7:3.2.10-1~deb9u1
libavcodec-dev | 7:3.3.4-2 | 7:3.2.10-1~deb9u1
libavdevice-dev | 7:3.3.4-2 | 7:3.2.10-1~deb9u1
libavutil-dev | 7:3.3.4-2 | 7:3.2.10-1~deb9u1
libswscale-dev | 7:3.3.4-2 | 7:3.2.10-1~deb9u1
libavresample-dev | 7:3.3.4-2 | 7:3.2.10-1~deb9u1
libavfilter-dev | 7:3.3.4-2 | 7:3.2.10-1~deb9u1
python | 3.6.3 | 3.6.5
pyav | 0.4.0 | 0.4.0

Let me know what else you need (like a sample video file?).

**Comment by mic159** [comment]
Interesting, google seems to be able to preview video, even if VLC and gstreamer cant.

Here is an example video that wont play: https://drive.google.com/open?id=1UP8eiQif7CA0n6hUz2B3suM1VvAcdKjC
The google preview works, but if you download the file, I cant get it to play in VLC.

**Comment by mikeboers** [comment]
What does including an explicit `output.close()` do?

**Comment by mic159** [comment]
Damn, your right, adding a .close makes the file playable.
