### ISSUE TITLE
Problem install

### ISSUE THREAD

**Issue by tgptec** [mikeboers/PyAV#318]
Hi, i'm try install in my virtualenv on Windows but this error appears:

PyAV: 0.4.0 (unknown commit)
    Python: b'3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]'
    platform: Windows-10-10.0.16299-SP0
    extension_extra:
        include_dirs: [b'include', b'c:\\program files (x86)\\microsoft visual studio\\shared\\python36_64\\include', b'c:\\program files (x86)\\microsoft visual studio\\shared\\python36_64\\include']
        libraries: [b'avformat', b'avcodec', b'avdevice', b'avutil', b'avfilter', b'swscale', b'swresample']
        library_dirs: [b'c:\\program files (x86)\\microsoft visual studio\\shared\\python36_64\\Libs', b'z:\\@hands-on\\_virtualenvironments\\microsoftcognitiveservices\\libs', b'z:\\@hands-on\\_virtualenvironments\\microsoftcognitiveservices\\PCbuild\\amd64']
        extra_link_args: [b'/OPT:NOREF']
    config_macros:
        PYAV_COMMIT_STR="unknown-commit"
        PYAV_HAVE_AVCODEC_SEND_PACKET=0
        PYAV_HAVE_AVFORMAT_ALLOC_OUTPUT_CONTEXT2=0
        PYAV_HAVE_AVFORMAT_CLOSE_INPUT=0
        PYAV_HAVE_AVFRAME__MB_TYPE=0
        PYAV_HAVE_AV_CALLOC=0
        PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=0
        PYAV_HAVE_AV_OPT_TYPE_BOOL=0
        PYAV_HAVE_LIBAVRESAMPLE=0
        PYAV_HAVE_LIBSWRESAMPLE=1
        PYAV_VERSION=0.4.0
        PYAV_VERSION_STR="0.4.0"
        inline=__inline

Thanks.

**Comment by mikeboers** [comment]
Can you describe the error?

**Comment by jlaine** [comment]
No response from the submitter for 5 months, I'd say close it.

**Comment by mikeboers** [comment]
Yarp.
