### ISSUE TITLE
how can install the latest version?

### ISSUE THREAD

**Issue by mengban** [mikeboers/PyAV#320]
i install the av by conda commad 'conda install av -c conda-forge'. The default version is  0.4.0.
But when i use av in  my project, there are some issues, however when i read the source code in the develop branch,the issue has been resolved. I read the [doc](http://mikeboers.github.io/PyAV/index.html) carefully. But i can't find anything userful ,so how can i update the av to the latest version? thx.

**Comment by mikeboers** [comment]
I'm personally only vaguely aware of how the conda stuff works, but if you can get to the point where `pip install av` works, then `pip install -e git+git@github.com:mikeboers/PyAV.git#egg=av` also works (or running `python setup.py install` in a copy of the source).

Anyone have a shortcut for conda?

**Comment by jlaine** [comment]
With the 0.5.1 version published to pypi, can we close this?

**Comment by mikeboers** [comment]
Lol yes. Thanks.
