### ISSUE TITLE
"Failed with error code 1" during pip install

### ISSUE THREAD

**Issue by ckcampbell248** [mikeboers/PyAV#321]
I'm getting the following error trying to run 'pip install av' in Windows 10. This is a new installation of Python 36 x64. I have been able to install other packages (pandas, numpy) successfully. I am trying from an administrative command prompt.  The install process listed several missing components and suggested opening an issue with the following information: 

    PyAV: 0.4.0 (unknown commit)
    Python: b'3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]'
    platform: Windows-10-10.0.17134-SP0
    extension_extra:
        include_dirs: [b'include', b'c:\\python36\\include', b'c:\\python36\\include']
        libraries: [b'avformat', b'avcodec', b'avdevice', b'avutil', b'avfilter', b'swscale', b'swresample']
        library_dirs: [b'c:\\python36\\libs', b'c:\\python36\\PCbuild\\amd64']
        extra_link_args: [b'/OPT:NOREF']
    config_macros:
        PYAV_COMMIT_STR="unknown-commit"
        PYAV_HAVE_AVCODEC_SEND_PACKET=0
        PYAV_HAVE_AVFORMAT_ALLOC_OUTPUT_CONTEXT2=0
        PYAV_HAVE_AVFORMAT_CLOSE_INPUT=0
        PYAV_HAVE_AVFRAME__MB_TYPE=0
        PYAV_HAVE_AV_CALLOC=0
        PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=0
        PYAV_HAVE_AV_OPT_TYPE_BOOL=0
        PYAV_HAVE_LIBAVRESAMPLE=0
        PYAV_HAVE_LIBSWRESAMPLE=1
        PYAV_VERSION=0.4.0
        PYAV_VERSION_STR="0.4.0"
        inline=__inline

    ----------------------------------------
Command "c:\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\chrcam\\AppData\\Local\\Temp\\pip-install-pwh_lv4x\\av\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\chrcam\AppData\Local\Temp\pip-record-jzrv3kdg\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\chrcam\AppData\Local\Temp\pip-install-pwh_lv4x\av\

**Comment by mikeboers** [comment]
I'm sorry to have left this for so long, but there are a few changes to the build (mostly to give more information during a failure).

If you come back to this, take a look at the new build debugging information.
