### ISSUE TITLE
Reading from UDP, PyAv is blocked?

### ISSUE THREAD

**Issue by SkytreeRom** [mikeboers/PyAV#325]
We read source file from UDP using `av.open()` function, and then decode each frame with `container.decode()`. It works well when UDP stream is stable. But when UDP stream stops, the program will get blocked at the `decode` line forever.  Moreover, if we `open` a wrong UDP stream, the program will also get blocked.
Can someone give us some suggestions about this problem? THANKS!
P.S. We have thought about using python's decorator by setting a fixed time to terminate the blocked process, but it doesn't meet our need. We want dynamically terminate the blocked process, which input UDP stream has stopped.

**Comment by mikeboers** [comment]
You're opening with something like `av.open('udp://foo')`?

If you look at [the FFmpeg docs](https://ffmpeg.org/ffmpeg-protocols.html#udp) there is a `timeout` option. Perhaps that could be set quite low. Maybe even zero.

I wonder if there is a way to nicely know how much data is has received.

**Comment by DFjackdaw** [comment]
We do use `av.open('udp://foo')` to connect a nonexistent udp address, it will get blocked.

We try `av.open('udp://foo?timeout=0')` , it seems not work . Still blocked. So is there another way to jump out? Or we just write the wrong codes?

And how about  `container.decode（）`？When the sender stop udp stream, it blocked.  Any option or parameter to terminate the blocked process？

**Comment by SkytreeRom** [comment]
THANKS! @mikeboers 
We have fixed this problem with the latest version (0.4.1). Using a simple parameter timeout, PyAv will automatically handle all possible problems when you `decode()` or `open()`.
