### ISSUE TITLE
How to improve decode performance?

### ISSUE THREAD

**Issue by gemfield** [mikeboers/PyAV#326]
The hardware platform info: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (48 processors) & 251G RAM.
The input is  RTMP protocol with h264 video format and aac audio format.
And the PyAV is compiled with the latest source code cloned from this Repo.

Now, after demux the packet from RTMP protocol, I do following operation:
`for frame in packet.decode()`
and the decode() API cost about 0.03 seconds(for video).

So, here are the 2 questions:
1, is 0.03 seconds reasonable? (If not reasonable, then what should it be on such platform?)
2, how to improve the decode performance(for video part)?

Thanks very much.

**Comment by notedit** [comment]
@gemfield   there  is a hardware acceleration   https://github.com/mikeboers/PyAV/pull/331

**Comment by mikeboers** [comment]
There is also more aggressive threading via #303 and #322.

**Comment by gemfield** [comment]
@notedit Thanks very much.

**Comment by gemfield** [comment]
@mikeboers After remove these config parameters "--disable-optimizations --disable-mmx --enable-debug=3", I got the huge performance improve. Don't know why they are there...? For cross platform?

**Comment by mikeboers** [comment]
Those are for the development build of FFmpeg. PyAV doesn't require those, but I do when debugging sometimes.

**Comment by gemfield** [comment]
@mikeboers Thanks.
