### ISSUE TITLE
frame index of video frame

### ISSUE THREAD

**Issue by mkassner** [mikeboers/PyAV#33]
Since frame.pts is often only by coincidence equal to frame index in video stream (and will ultimately fail with non constant frame rates), I was hoping for frame.index to represent the frame index in the steam.

However, it appears that frame index == encoded frame count on frame creation. This mean that after a seek the index become -at least the way I understand it- false.

Any ideas on how to fix that?

**Comment by funkybob** [comment]
In my own code, after much painful and tedious research :) I have the following:

```
'''
        PTS (Presentation Time Stamp), which indicates when this frame should
        be shown, is expressed according to stream.time_base.

        We can compare the PTS to frame numbers if we scale by:
            (stream.average_rate / stream.time_base)
'''
pts_scale = video_stream.average_rate * video_stream.time_base

frame_pts = int(frame_index / pts_scale)

```

I'm not certain how portable this is, as we only use MP4 video streams.

**Comment by jlaine** [comment]
I'm going to close this issue, as the following time-related attributes are properly documented nowadays:

- dts
- pts
- time_base
