### ISSUE TITLE
Require newest Cython, or don't include Cython source?

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#335]
Yesterday's release uses a feature of Cython that was introduced in 0.27 (see response in #323).

To combat this, we should either require a minimum version of Cython, or just not ship the Cython source in the source on PyPI.

Anyone have a preference?

**Comment by jlaine** [comment]
Cython 0.27 is almost a year old I'd vote for a versioned dependency, vendoring code is a problem waiting to happen!

**Comment by mikeboers** [comment]
We don't include Cython itself, but we do ship PyAV's Cython code in the source distribution.

If you have Cython installed, installing PyAV in this manner usually results in it being "cythonized", despite shipping the C code (that my machine generated).

So... if you have an old Cython, then it will re-cythonize it badly. Thus, this issue.

**Comment by mikeboers** [comment]
Today's release only uses Cython if >= 0.27.
