### ISSUE TITLE
RTMP live stream, timestamps?

### ISSUE THREAD

**Issue by dimitrievgs** [mikeboers/PyAV#352]
Hello, the question is about live stream via RTMP.
I have several parallel threads, in one I capture frames (Mat) from usb camera by OpenCV, in another (lower) I get each frame and write to output.
I need this construction to have an ability to run 3rd thread where I write frames with detected motion into a video file.

1st question: what is happened with timestamps? Is this code correct and shouldn't I specify timestamps for each frame? If I ```print(str(frame.time) + " " + str(frame.pts) + " " + str(frame.time_base))``` after av.VideoFrame.from_ndarray(...) or self.encode(frame) I get just "None, None, None"
capturedFrame and processedFrame in OpenCV's Mat, as I understand.

If I run translation and stop, than again run and stop, and again, video translations are mixed in live video (one time first, then second then again first or third and so on). By this run and stop I simulate connection loss, which take place, as I checked it in java. 
How to fix this?

2nd question: how can I add audiostream with silence to this? 
The server side complains and refuses to broadcast from time to time with error "the stream uses an unsupported audio codec" (it wants 'aac')

```python
    def encode(self, frame):
        try:
            pkt = self.ovstream.encode(frame)
        except Exception:
            return False
        if pkt is not None:
            try:
                self.output.mux(pkt)
            except Exception:
                print('mux failed: ' + str(pkt))
        return True

    def RTMP_Job(self):
        self.activities.append('RTMP')

        self.url = 'rtmp://...'
        self.key = '...'

        url_key = self.url + '/' + self.key

        self.output = av.open(url_key, mode='w', format='flv')
        self.ovstream = self.output.add_stream('libx264', self.FRAME_RATE) 
        self.ovstream.options = {}
        self.ovstream.pix_fmt = 'yuv420p'
        self.ovstream.width = self.frameSize[0]
        self.ovstream.height = self.frameSize[1]

        thread_LastFrame_Timestamp = -1
        self.Wait_for_CapturerStart()

        # self.time_base = 1.0 / self.FRAME_RATE * 1000000.0

        while (self.Capture_Works()):
            capturedFrame, processedFrame = self.Wait_ForFrame(thread_LastFrame_Timestamp)
            thread_LastFrame_Timestamp = self.LastFrame_TimeStamp

            frame = av.VideoFrame.from_ndarray(processedFrame, format='bgr24')

            #frame.pts = self.LastFrame_TimeStamp / self.time_base
            #frame.time_base = self.time_base

            self.encode(frame)

        self.output.close()

        self.activities.remove('RTMP')
```

Python 3.5.2
av: 0.4.1

**Comment by jlaine** [comment]
`VideoFrame.from_ndarray` cannot populate any timestamps, where would it get this information from? OpenCV's capture API lacks any timing information, so I would suggest you rethink your code, maybe as follows:

- use `av.open('/dev/video0')` or the equivalent for your platform to acquire your video frames. This will output `av.VideoFrame` instances which *will* have timing information on them

- perform your video processing, and restore the timing information from the original VideoFrame
