### ISSUE TITLE
packet.decode() sometimes returns None

### ISSUE THREAD

**Issue by orf** [mikeboers/PyAV#353]
Hello,
We have come across a video that appears to make `packet.decode()` return None instead of a list. When run with the simple code below it fails with a `Nonetype object is not iterable` error.  As far as I can tell several packets at the end of the video return None. I can't post the video publicly, but I may be able to send it privately if you wish to reproduce. This happens on the latest master, as well as the latest release.

As far as I can tell no documentation or examples say that `packet.decode()` may return `None`? I'm guessing it's something to do with the 3rd and 4th streams with no data in the file.

Script:

```
container = av.open('test.mov')

for packet in container.demux():
    for frame in packet.decode():
        pass
```

FFMPeg video information:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mov':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    creation_time   : 2018-06-28T16:29:39.000000Z
    com.apple.quicktime.location.ISO6709: +38.7235-009.1497+067.471/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 6
    com.apple.quicktime.software: 11.4
    com.apple.quicktime.creationdate: 2018-06-28T17:15:03+0100
  Duration: 00:00:06.74, start: 0.000000, bitrate: 3357 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 99 kb/s (default)
    Metadata:
      creation_time   : 2018-06-28T16:29:39.000000Z
      handler_name    : Core Media Data Handler
    Stream #0:1(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709), 360x640 [SAR 1:1 DAR 9:16], 3223 kb/s, 29.99 fps, 29.97 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      creation_time   : 2018-06-28T16:29:39.000000Z
      handler_name    : Core Media Data Handler
      encoder         : H.264
    Stream #0:2(und): Data: none (mebx / 0x7862656D), 22 kb/s (default)
    Metadata:
      creation_time   : 2018-06-28T16:29:39.000000Z
      handler_name    : Core Media Data Handler
    Stream #0:3(und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2018-06-28T16:29:39.000000Z
      handler_name    : Core Media Data Handler
```

**Comment by mikeboers** [comment]
My apologies for taking so long.

I can imagine how a data stream would do something like this, but reading through the code I'm not seeing it.

Do you think you can provide a small chunk of the sample, or find another one (perhaps somewhere in the FATE suite)?

**Comment by orf** [comment]
Hey @mikeboers, I have sent you the small video that triggers this to the email in your profile if that is OK? It's only 6 seconds long or so.

**Comment by mikeboers** [comment]
Thanks for the sample.

Unfortunately (but reasonably), FFmpeg represents data streams as NULL codecs. PyAV generally assumes that there is always a codec, so there are a TON of places where handling data streams just won't work.

However, as long as you don't interact with the objects, it is likely okay; I'm able to iterate across all video/audio frames in your sample with this:

```
import sys

import av

container = av.open(sys.argv[1])
for packet in container.demux(video=0, audio=0):
    print(packet)
    for frame in packet.decode():
        print(frame)
```

**Comment by mikeboers** [comment]
Assuming that deals with your problem, I'm going to close this and leave #368 to continue to be about data codecs.

**Comment by Tuan-Hang** [comment]
I am having issue about decode packet by PyAV.
size of packet >0 but when call frame = codec.decode(paket) then len(frame) =0.
who can explain help me?

**Comment by orf** [comment]
Yourself, read the comments above and the related issues/pull requests?
