### ISSUE TITLE
`avformat_open_input` not found

### ISSUE THREAD

**Issue by luswangl2013** [mikeboers/PyAV#355]
Hello, I am following the guideline in https://docs.pupil-labs.com/#windows-pupil-labs-python-libs-from-source when building pyav. I got this error as a result.

> We didn't find `avformat_open_input` in the libraries.
> We look for it only as a sanity check to make sure the build
> process is working as expected. It is not, so we must abort.
> 
> Please open a ticket at https://github.com/mikeboers/PyAV/issues
> with the folowing information:
> 
> PyAV: 0.4.1.dev0 b'v0.4.1-3-gcaee136'
> Python: b'3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)]'
> platform: Windows-10-10.0.16299-SP0
> extension_extra:
>         include_dirs: [b'include', b'D:\\pupil_v1.8\\ffmpeg-20180809-eb1860e-win64-dev\\ffmpeg-20180809-eb1860e-win64-dev\\include', b'D:\\python3\\include', b'D:\\python3\\include']
>         libraries: [b'avformat', b'avcodec', b'avdevice', b'avutil', b'avfilter', b'swscale', b'swresample']
>         library_dirs: [b'D:\\pupil_v1.8\\ffmpeg-20180809-eb1860e-win64-dev\\ffmpeg-20180809-eb1860e-win64-dev\\lib', b'D:\\python3\\libs', b'D:\\python3\\PCbuild\\win32']
>         extra_link_args: [b'/OPT:NOREF']
> config_macros:
>         PYAV_COMMIT_STR="b'v0.4.1-3-gcaee136'"
>         PYAV_HAVE_AVCODEC_SEND_PACKET=0
>         PYAV_HAVE_AVFORMAT_ALLOC_OUTPUT_CONTEXT2=0
>         PYAV_HAVE_AVFORMAT_CLOSE_INPUT=0
>         PYAV_HAVE_AVFRAME__MB_TYPE=0
>         PYAV_HAVE_AV_CALLOC=0
>         PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=0
>         PYAV_HAVE_AV_OPT_TYPE_BOOL=1
>         PYAV_HAVE_LIBAVRESAMPLE=0
>         PYAV_HAVE_LIBSWRESAMPLE=1
>         PYAV_VERSION=0.4.1.dev0
>         PYAV_VERSION_STR="0.4.1.dev0"
>         inline=__inline
>

**Comment by mikeboers** [comment]
This error is overwhelmingly because FFmpeg was build static instead of shared. The new `setup.py` advises to run `python setup.py reflect --force --debug` to get insights into the build process.

Re-open this if running that doesn't provide a clear answer.
