### ISSUE TITLE
Build problem on Windows 10.

### ISSUE THREAD

**Issue by rompur** [mikeboers/PyAV#361]
Hi,

I'm trying to install the av module on Windows 10 (Python 3.7).

I downloaded the ffmpeg shared and dev packages to `C:\ffmpeg`. If i do `python setup.py build --ffmpeg-dir=C:\ffmpeg` it cant find the ffmpeg libraries (I get the 'avformat_open_input' missing Error). But if i do `python setup.py reflect --force --debug --ffmpeg-dir=C:\ffmpeg` it does find them. If i do the build again after, it works but if i want to use the package i get following Error:
 
```
import av
File "C:/Users/Roman/Documents/python skripts/PyAV-develop\av\__init__.py", line 9, in <module>
    from av._core import time_base, pyav_version as __version__
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
```

**Comment by mikeboers** [comment]
The error is roughly "The specified module was not found.", right?

Anyone here with experience building on Windows have an idea?

**Comment by jlaine** [comment]
We could try and give appveyor a shot to add Windows to CI. I noticed ffmpeg provides binary builds of ffmpeg for Windows, which is a relief as I didn't fancy building from source.

**Comment by mikeboers** [comment]
AppVeyor is there, but I've been so hands-off the Windows side of things it is kinda funny.

**Comment by mikeboers** [comment]
I'm closing due to lack of feedback from original poster. Open this back up if you're still struggling.

**Comment by DeltaProg** [comment]
I had the same problem on Win10 with ffmpeg 4.0.2. 
I've reinstalled av with --ffmpeg-dir pointing to ffmpeg 3.2.4 and it works.

**Comment by DiPaolo** [comment]
I faced with the same issue on Windows 10. My solution that helped me - add to PATH environment variable a path to FFMpeg's bin folder - like ...\ffmpeg-3.2.4-win32-dev\bin (where DLLs placed).

**Comment by sayadrameez** [comment]
> I faced with the same issue on Windows 10. My solution that helped me - add to PATH environment variable a path to FFmpeg's bin folder - like ...\ffmpeg-3.2.4-win32-dev\bin (where DLLs placed).

Just to add to the above, restart the computer once for the ENVIRONMENT variables to reflect

**Comment by mafanwei** [comment]
Windows 10（Python 3.8） I have same question. I'm sure added PATH.
Anyone can help?

**Comment by mafanwei** [comment]
![image](https://user-images.githubusercontent.com/25474810/77623188-9aaddc00-6f7a-11ea-8374-9078a5af6ccd.png)

**Comment by mafanwei** [comment]
![image](https://user-images.githubusercontent.com/25474810/77623279-c7fa8a00-6f7a-11ea-8aad-07bed3579944.png)
ENVIRONMENT has taken effect.

**Comment by mafanwei** [comment]
I fix it.
Use python 3.7 instead 3.8.

**Comment by lp-c** [comment]
I fix it 
Uninstall av==9.1.1, install av==9.1.0
