### ISSUE TITLE
Can get timestamp of frame in video

### ISSUE THREAD

**Issue by thanhnt1995** [mikeboers/PyAV#364]
How can I get timestamp of a frame in a video or rtmp stream from pts and time_base or duration? Thanks a lot!

**Comment by mikeboers** [comment]
`pts` the time in units of `time_base`. So time is `pts * time_base`.

**Comment by thanhnt1995** [comment]
Thank you mike!
But ``` time  =  frame.pts * frame.time_base``` return fail result. I try with rtsp :```"rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov"``` and print ```frame.pts*frame.time_base``` for each frame but it is not exact. Here is my code and result:
```
import av
def init_input(file_name):
    container = av.open(file_name)
    return container.decode(video=0)
url = "rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov"
stream = init_input(url)
for frame in stream:
    print(float(frame.pts*frame.time_base))
```
The duration of rtsp is only 9m59s = 599s but code return very large result.
Can you help me,pls? Thank you very much

**Comment by mikeboers** [comment]
I can see that for some reason the code in `CodecContext._setup_decoded_frame()` isn't being triggered to copy the right `time_base`. Stay tuned!

**Comment by mikeboers** [comment]
It seems like the frame `time_base` was never going to get set properly. That is now fixed in the develop branch.
