### ISSUE TITLE
 first two keyframes can not be decoded successfully even the is_keyframe is TRUE.

### ISSUE THREAD

**Issue by liu666666** [mikeboers/PyAV#369]
Thanks for your wonderful job！@mikeboers
I  observe that many videos lost the first two keyframes. It means that the first two keyframes can not be decoded successfully even the is_keyframe is TRUE.

**Comment by mikeboers** [comment]
This is something that @liu666666 emailed me privately first with some samples. I can confirm the behavior, but I don't have a good reason for it.

I don't think this is a PyAV "issue".

If you can show that `ffmpeg` or `ffprobe` does better, let us know and we can maybe sort it out.
