### ISSUE TITLE
manually teardown rtsp connection

### ISSUE THREAD

**Issue by choice17** [mikeboers/PyAV#370]
* System :
window7
anaconda 3.4
python 3.5
conda-forge av 0.4.0

* Description :
I use av.open to access a stream and able to select the stream type and parsing to image. However, when I exit the program, I check with wireshark. pyav does not help to send RTSP 'TEARDOWN' request to the server. Server is then keep sending packets till timeout.
```
url = 'rtsp://url'
video = av.open(url, options)
for packet in video.demux(video.streams):
    for frame in packet.decode():
         if packet.stream.type == 'video':
                img = frame.to_nd_array( format='bgr24' )

```
While in C, libav can close the input properly by closing the context and free the buf. How should I do that in pyav? 
```
       av_free_packet(&packet);
        av_init_packet(&packet);
    }
    av_free(pic);
    av_free(picrgb);
    av_free(picture_buf);
    av_free(picture_buf2);

    av_read_pause(context);
    avio_close(oc->pb);
    avformat_free_context(oc);
```
Thank you for maintaining the library!

**Comment by mikeboers** [comment]
I'm on the verge of a push to make sure everything is being closed properly, as I'm pretty sure there is a ~250B leak with every output container not being cleaned up.

**Comment by jlaine** [comment]
Does a simple `video.close()` help?

**Comment by choice17** [comment]
> Does a simple `video.close()` help?
As i cannot use `pip install av` successfully in Window anaconda. I am currently using conda-forge av 0.4.0, it does not have this close function for input container.
```
video.close()
AttributeError: 'av.container.input.InputContainer' object has no attribute 'close'
```
Does newer version of av lib have this close function for input container?

**Comment by jlaine** [comment]
Hm you're right, I don't see a close() on input containers. How come @mikeboers ?

**Comment by mikeboers** [comment]
I guess it never came up before somehow.

It must be closing stuff, but maybe on the destructor.

**Comment by choice17** [comment]
I have some workaround solution.
Just simply exit the program while putting the input container to one thread and mark it as daemon thread. Main thread then helps to send termination signal to pyav input container.
May be thread join can help but I have not tried it.
I believe pyav itself has some signal interrupt handling scheme.

**Comment by jlaine** [comment]
Does this do anything for you:

```
container = None
gc.collect()
````

**Comment by rodrhern** [comment]
I had a similar question, that later I answered my self

https://github.com/mikeboers/PyAV/issues/366

As @mikeboers  said the destructor is also closing the ffmpeg connection

```
import av
container = av.open('/dev/video0')
```
then

`del container` or `container=None` will release the usb camera and probably the rtsp connection.

probably here

https://github.com/mikeboers/PyAV/blob/41a0598a4e7703eff3374d7764d45a56892e5427/av/stream.pyx#L85

**Comment by choice17** [comment]
> Does this do anything for you:
> 
> ```
> container = None
> gc.collect()
> ```

it works, thanks.

**Comment by jlaine** [comment]
Awesome, thanks for getting back to us on this!
