### ISSUE TITLE
CRF flag seems to have no effect

### ISSUE THREAD

**Issue by jimmy-zendar** [mikeboers/PyAV#371]
I want to set the video quality through the crf flag and it seems the quality of the encoded video does not change with the setting. It seems that the quality of the video is entirely governed by manually setting the bit_rate. My code snippet looks like

```
options = {'crf': '51'}
container = av.open(self.output_file, mode='w', options=options)
stream = container.add_stream('libx264', rate=24)
stream.width = 1024
stream.height = 800
stream.pix_fmt = 'yuv444p'
stream.bit_rate = 8000000
```

Thank you so much in advance for looking at my problem.

**Comment by jlaine** [comment]
Out of curiosity, does it make any difference if instead you do the following after adding the stream:

```stream.options = {'crf': '51'}```

**Comment by jlaine** [comment]
I'm closing this issue as the submitter has not responded in over a month.

**Comment by rsomani95** [comment]
@jlaine I can confirm that setting `stream.options = {'crf': '51'}` works.

If I set it via `container = av.open(out_file, mode='w', options={'crf': '51'})`, I get a message saying:
```bash
Some options were not used: {'crf': '10'}
```

**Comment by altave-gabriel-viana** [comment]
> @jlaine I can confirm that setting `stream.options = {'crf': '51'}` works.
> 
> If I set it via `container = av.open(out_file, mode='w', options={'crf': '51'})`, I get a message saying:
> 
> ```shell
> Some options were not used: {'crf': '10'}
> ```

I am using like that, but it doesn't seem to have any effect. My code:

```py
    input_container = av.open(temporary_output_file)
    output_container = av.open(output_file, mode='w')

    input_stream = input_container.streams.video[0]
    fps = input_stream.average_rate

    stream = output_container.add_stream("libvpx-vp9", rate=fps)
    stream.width = input_stream.width
    stream.height = input_stream.height
    stream.pix_fmt = "yuv420p"
    stream.options = {"crf": str(crf_value)}

    for frame in input_container.decode(video=0):
        for packet in stream.encode(frame):
            output_container.mux(packet)

    for packet in stream.encode():
        output_container.mux(packet)

    input_container.close()
    output_container.close()
```
When I vary the CRF value, the size of the output video does not change and the quality appears to be the same. If I remove the line `stream.options = {"crf": str(crf_value)}` the results are the same, nothing changes.
I am trying to recreate this ffmpeg command using PyAV:
```bash
ffmpeg -i input.avi -c:v libvpx-vp9 -crf 63 -b:v 0 libopus output_crf_63.webm
```
