### ISSUE TITLE
[ERROR] undefined symbol: av_packet_clone

### ISSUE THREAD

**Issue by KiyomiHan** [mikeboers/PyAV#374]
- when I import av , I get an error
python3.6/site-packages/av/container/output.cpython-36m-x86_64-linux-gnu.so: undefined symbol: av_packet_clone

- I need use cuda, so I've compile FFmpeg3.4

'''
ffmpeg version n3.4.4-2-gc50dc77 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
configuration: --enable-cuda --enable-cuvid --enable-nvenc --enable-nonfree --enable-libnpp --extra-cflags=-I/<path to>/cuda/cuda-8.0/cuda/include --extra-ldflags=-L/<path to>/cuda/cuda-8.0/cuda/lib64/stubs
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
'''

- I have no idea about it , cloud you help me?

**Comment by viskoo** [comment]
I had the same problem and i solved it like this: #348, but i had ton of problems to make it work (for some, unknown reason)

**Comment by KiyomiHan** [comment]
> I had the same problem and i solved it like this: #348, but i had ton of problems to make it work (for some, unknown reason)
Thanks,
I've read it， but  I need the ffmpeg3.4 , because it supported cuvid

**Comment by jlaine** [comment]
To my knowledge av_packet_clone is present in ffmpeg 3.x but not in 2.x, so I'm wondering whether you are actually building PyAV against the right ffmpeg version.

**Comment by KiyomiHan** [comment]
> To my knowledge av_packet_clone is present in ffmpeg 3.x but not in 2.x, so I'm wondering whether you are actually building PyAV against the right ffmpeg version.

emmm, I'm just use the pip3 install av

**Comment by jlaine** [comment]
My point is you say "I've compiled ffmpeg 3.6", but I am pretty sure that when you "pip3 install av", PyAV is not being built against the ffmpeg libraries / headers you built. How did you build and where did you install ffmpeg?

**Comment by KiyomiHan** [comment]
I build ffmpeg3.4 with such command:

PKG_CONFIG_PATH="/usr/local/lib/pkgconfig" ./configure --enable-cuda --enable-cuvid --enable-nvenc --enable-nonfree --enable-libnpp --extra-cflags=-I/<path to>/cuda-8.0/cuda/include --extra-ldflags=-L//<path to>/cuda/cuda-8.0/cuda/lib64/stubs

make -j 4

sudo make install

**Comment by KiyomiHan** [comment]
> My point is you say "I've compiled ffmpeg 3.6", but I am pretty sure that when you "pip3 install av", PyAV is not being built against the ffmpeg libraries / headers you built. How did you build and where did you install ffmpeg?


I build ffmpeg3.4 with such command:

PKG_CONFIG_PATH="/usr/local/lib/pkgconfig" ./configure --enable-cuda --enable-cuvid --enable-nvenc --enable-nonfree --enable-libnpp --extra-cflags=-I//cuda-8.0/cuda/include --extra-ldflags=-L///cuda/cuda-8.0/cuda/lib64/stubs

make -j 4

sudo make install

**Comment by jlaine** [comment]
OK, so your custom ffmpeg lives in /usr/local. Can you run the following and post the output:

`ldd python3.6/site-packages/av/container/output.cpython-36m-x86_64-linux-gnu.so`

**Comment by jlaine** [comment]
PyAV requires ffmpeg 3.0 or higher, av_packet_clone doesn't exist in ffmpeg 2.8.x

**Comment by kbehouse** [comment]
> As documented in the README PyAV requires ffmpeg 3.0 or higher, av_packet_clone doesn't exist in ffmpeg 2.8.x

It works, thank you!! 
(by building ffmpeg 3.4)

**Comment by jlaine** [comment]
@mikeboers we can close this I think
