### ISSUE TITLE
Number of frames in packet

### ISSUE THREAD

**Issue by viskoo** [mikeboers/PyAV#375]
Hi,
Is it possible, in any way, found out how many frames are there in packet without decoding it?

Thanks.

**Comment by mikeboers** [comment]
I don't think so, but I wish there was.

I can't even figure out how to get FFmpeg to always even give me all of the contents of a packet reliably. It will just hold onto some in a buffer for no reason that I can tell.

My feeling, though I can't prove it, is that there is never more than one video frame in a packet.

**Comment by mikeboers** [comment]
I don't think anyone will have anything more definitive, and it isn't really a PyAV "issue", so I'm closing this. Someone please let me know if you learn more.
