### ISSUE TITLE
How to link decoded frames back to a stream?

### ISSUE THREAD

**Issue by jlaine** [mikeboers/PyAV#378]
I am currently working on some code to play out audio + video in a synchronized fashion, and I'm having trouble understanding how to know which stream the decoded frames belong to. The code looks like:

```
for frame in container.decode():
    if isinstance(frame, av.AudioFrame):
        handle_audio_frame(frame)
    elif isinstance(frame, av.VideoFrame):
        handle_video_frame(frame)
```

However using the frame type like this means I can only handle a single audio and single video stream. 
Is there any way to get the stream which the frame belongs to, or do I have to iterate separately on the different streams with `container.decode(streams=..)`?

**Comment by mikeboers** [comment]
Frames don't currently retain the stream they came from, but that seems like something we could do to no ill effect.

Packets do have a `stream` attribute.

If you instead:

```
for packet in container.demux():
    for frame in packet.decode():
      # something with packet.stream and frame
```

**Comment by jlaine** [comment]
Thanks that answers my question!
