### ISSUE TITLE
Many build warnings.

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#379]
- [ ] ```src/av/stream.c:2094:29: warning: 'codec' is deprecated [-Wdeprecated-declarations]
  switch (__pyx_v_c_stream->codec->codec_type) {```
- [ ] ```src/av/stream.c:2855:15: warning: assigning to 'struct AVCodec *' from 'const struct AVCodec *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    __pyx_t_7 = __pyx_v_self->_codec_context->codec;```
- [x] ```src/av/packet.c:2394:9: warning: 'av_free_packet' is deprecated [-Wdeprecated-declarations]
        av_free_packet((&__pyx_v_self->__pyx_struct));```
- [ ] ```src/av/_core.c:1574:3: warning: 'av_register_all' is deprecated [-Wdeprecated-declarations]
  av_register_all();```
- [ ] ```src/av/_core.c:1601:3: warning: 'avcodec_register_all' is deprecated [-Wdeprecated-declarations]
  avcodec_register_all();```
- [ ] ```src/av/_core.c:1610:3: warning: 'avfilter_register_all' is deprecated [-Wdeprecated-declarations]
  avfilter_register_all();```
- [ ] ```src/av/format.c:1634:28: warning: 'av_oformat_next' is deprecated [-Wdeprecated-declarations]
      __pyx_v_self->optr = av_oformat_next(__pyx_v_self->optr);```
- [ ] ```src/av/format.c:3353:32: warning: 'av_iformat_next' is deprecated [-Wdeprecated-declarations]
    __pyx_v_2av_6format_iptr = av_iformat_next(__pyx_v_2av_6format_iptr);```
- [ ] ```src/av/logging.c:3694:20: warning: assigning to 'char *' from 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
      __pyx_v_name = __pyx_v_cls->item_name(__pyx_v_ptr);```
- [ ] ```src/av/descriptor.c:1578:13: warning: assigning to 'struct AVOption *' from 'const struct AVOption *const' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  __pyx_t_1 = __pyx_v_self->ptr->option;```
- [ ] ```src/av/video/codeccontext.c:2559:21: warning: 'avcodec_encode_video2' is deprecated [-Wdeprecated-declarations]
    __pyx_t_5.res = avcodec_encode_video2(__pyx_v_self->__pyx_base.ptr, (&__pyx_v_packet->__pyx_struct), __pyx_v_vframe->__pyx_base.ptr, (&__pyx_v_got_packet));```
- [ ] ```src/av/video/codeccontext.c:2848:26: warning: 'avcodec_decode_video2' is deprecated [-Wdeprecated-declarations]
        __pyx_v_result = avcodec_decode_video2(__pyx_v_self->__pyx_base.ptr, __pyx_v_self->next_frame->__pyx_base.ptr, (&__pyx_v_completed_frame), __pyx_v_packet);```
- [ ] ```src/av/video/format.c:1856:21: warning: assigning to 'struct AVPixFmtDescriptor *' from 'const AVPixFmtDescriptor *' (aka 'const struct AVPixFmtDescriptor *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  __pyx_v_self->ptr = av_pix_fmt_desc_get(__pyx_v_pix_fmt);```
- [x] ```src/av/video/format.c:3418:57: warning: 'depth_minus1' is deprecated [-Wdeprecated-declarations]
  __pyx_t_1 = __Pyx_PyInt_From_long((__pyx_v_self->ptr->depth_minus1 + 1)); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 131, __pyx_L1_error)```

And so on. Just build it to see.

**Comment by jlaine** [comment]
The deprecation warnings are tricky as we need to separate what was deprecated pre-3.0 and post-3.0. I suggest we focus on making builds against 3.0 clean first, then look at the remaining ones.

**Comment by mikeboers** [comment]
This issue isn't serving us anymore after jlaine took care of a lot of it.
