### ISSUE TITLE
`AudioFormat` vs `SampleFormat`

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#383]
In https://github.com/mikeboers/PyAV/commit/ae764a4fb168705ae1a859a337d59307543454af @jlaine finished up `Codec.video_formats` and `Codec.audio_formats`. At somepoint we dicussed why these were `audio` formats instead of `sample` formats.

In isolation, I like `sample_formats` better... but the class is called `AudioFormat`.

This reminds me of the "we don't need to mimick the underlying project structure as much as we do" point from the `HACKING.rst` docs. I wrote that point a long time ago, and my feeling has slowly been that when it comes to 1:1 mappings of PyAV:FFmpeg, maybe we ought to stick with their names (unless they are really horribly wrong).

I don't think PyAV should be responsible for wrapping the FFmpeg documentation, but instead augmenting it where we are different. If we keep the same names then it is easier to map from one to the other.

I'm not 100% on this, but I propose changing the edict to be to stick to the FFmpeg names as much as possible.

We could as far as providing synonyms where we feel they should be named separately. Perhaps that is bad API design. I don't know.

I've written a pile of fun tools for deprecating moved modules, classes, and attributes. We could use that so that they at least signal for a few years before removing them.

**Comment by jlaine** [comment]
I'd say close this issue, it's just cluttering up the issue track, and `AudioFormat` is really nice.

**Comment by mikeboers** [comment]
Yeah...

Let it linger for a day so that I can write something into the `HACKING.rst` about it.

I'd do it now, but... it is supposed to be a holiday and I'm at the cottage. I should go look at the stars or something. 😉

**Comment by mikeboers** [comment]
Done. See http://docs.mikeboers.com/pyav/develop/hacking.html
