### ISSUE TITLE
Can we copy parts of the FFmpeg docs?

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#384]
Does the FFmpeg license ([L]GPL) allow us to copy parts of the docs into our docs?

If we could somewhat automatically copy struct attribute docs, that could be extremely helpful.

**Comment by mikeboers** [comment]
I don't think we can. But we can certainly link to them.

**Comment by jlaine** [comment]
To be honest I'm not sure the struct attribute docs help very much, as they make references to very C-specific things, like the sentinel values for arrays, etc..
