### ISSUE TITLE
Embed library versions into build product.

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#393]
Either:

1. use `compile_check` (or similar) to build a tiny library which gives us the versions we link against, or
2. import `av._core` as soon as we can, and use its functions to get the library versions.

Write that into a `LIBRARY.txt` or similar in the package, and read it at runtime. Issue a warning if it is very different.

**Comment by jlaine** [comment]
I don't think this is something we should / need to do. When you link against the ffmepg libraries', the SONAME is captured by the linker, guaranteeing you will only ever load an ABI-compatible library, e.g.:

```
$ ldd av/format.cpython-36m-x86_64-linux-gnu.so
        [...]
        libavcodec.so.58 => /usr/lib/x86_64-linux-gnu/libavcodec.so.58 (0x00007fae996f9000)
```

**Comment by mikeboers** [comment]
Yeah, I hear you. It does the same on macOS:

```
$ otool -L av/_core.cpython-37m-darwin.so
av/_core.cpython-37m-darwin.so:
	/Users/mikeboers/Documents/PyAV/vendor/build/ffmpeg-4.0/lib/libavfilter.7.dylib (compatibility version 7.0.0, current version 7.16.100)
	/Users/mikeboers/Documents/PyAV/vendor/build/ffmpeg-4.0/lib/libswresample.3.dylib (compatibility version 3.0.0, current version 3.1.100)
	/Users/mikeboers/Documents/PyAV/vendor/build/ffmpeg-4.0/lib/libavdevice.58.dylib (compatibility version 58.0.0, current version 58.3.100)
	/Users/mikeboers/Documents/PyAV/vendor/build/ffmpeg-4.0/lib/libavutil.56.dylib (compatibility version 56.0.0, current version 56.14.100)
	/Users/mikeboers/Documents/PyAV/vendor/build/ffmpeg-4.0/lib/libavformat.58.dylib (compatibility version 58.0.0, current version 58.12.100)
	/Users/mikeboers/Documents/PyAV/vendor/build/ffmpeg-4.0/lib/libswscale.5.dylib (compatibility version 5.0.0, current version 5.1.100)
	/Users/mikeboers/Documents/PyAV/vendor/build/ffmpeg-4.0/lib/libavcodec.58.dylib (compatibility version 58.0.0, current version 58.18.100)
```

How about adding a shim with macro checking that will `#error` if it is too early of an FFmpeg, just so that we can have it print a message about it? Otherwise we're going to get issues opened about functions not existing.

**Comment by mikeboers** [comment]
Closing this in favour of #401.
