### ISSUE TITLE
Silence some warnings.

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#396]
There are some warnings, e.g. those related to #222, which keep popping up in issues here.

Those warnings are to the developers, not the users. Perhaps we should add to the logging machinery a few things that it can ignore, starting with messages that start with `"Using AVStream.codec to pass codec parameters to muxers is deprecated"`.

**Comment by jlaine** [comment]
I'd say close this issue and let's fix #222 now that we only support FFmpeg >= 3.2

**Comment by mikeboers** [comment]
It is likely about the same amount of effort, and I don't have another use case on the top of my head, so I agree.

**Comment by ru1996** [comment]
Excuse me, how can I ignore the warnings now that the official not support the feature. 

eg.

 `Estimating duration from bitrate, this may be inaccurate`

`Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.`
