### ISSUE TITLE
Packet "time_base" manipulations are tricky

### ISSUE THREAD

**Issue by jlaine** [mikeboers/PyAV#397]
While trying to encode frames (with a correct PTS)  to an H.264 stream I kept encountering problems when I submit the "flush" packets to the muxer, complaining that the packets had non-monotonically increasing PTS.

After some digging around I have come to the conclusion that PyAV's storing of a "time_base" associated with packets and its attempts to manipulate the pts / dts / duration are harmful.

The root of the problem comes from how PyAV attempts to associate a "time_base" with a packet (a concept that ffmpeg's AVPacket does not have) during encoding. In essence CodecContext.encode works like this:

- send a frame to the encoder
- check if it has some packets for us
- if it does, try to put either the frame's time_base or the stream's into the packet (setup_encoded_packet)
- return the packets

The underlying assumption here is that the packets we received are related to the frame we just submitted, but *this is not necessarily the case*. The reason there is a "flushing" mechanism is precisely because the codec may be performing buffering.

H.264 is a good example here : if you look at the timeline you will see there is clearly some buffering going on. You get no packets for a long time even though you're submitting frames, and conversely the flushing produces packets even though you didn't submit a frame.. so setup_encoded_packet is working on a wrong assumption.

Also it's not clear to me why setup_encoded_packet isn't crashing when given a "None" frame, as we reach into frame._time_base?

**Comment by jlaine** [comment]
My conclusion at this stage are that:

- at the very least setup_encoded_packet should not be looking at "frame" at all. This is doubly true as CodecContext.encode accepts a single frame a list of frames or None, and reassigns the "frame" variable while iterating

- I am not convinced we are helping users at all by mangling pts/dts by default. As far as I can tell the only use case where this makes sense is when transferring packets between streams, which is definitely an advanced topic

**Comment by jlaine** [comment]
Here is a sample piece of code for tests:

```python
output = av.open('some.mov', 'w')
  
stream = output.add_stream('h264', 24)
stream.width = WIDTH
stream.height = HEIGHT
stream.pix_fmt = 'yuv420p'

for i in range(DURATION):
    frame = VideoFrame(WIDTH, HEIGHT, 'rgb24')
    frame.pts = i * 2000
    frame.time_base = Fraction(1, 48000)

    print('frame time_base', frame.pts, 'pts', frame.pts)
    for packet in stream.encode(frame):
        print('stream time_base', stream.time_base)
        print('packet time_base', packet.time_base, 'pts', packet.pts)
        output.mux(packet)

print('-- flush --')
for packet in stream.encode(None):
    print('stream time_base', stream.time_base)
    print('packet time_base', packet.time_base, 'pts', packet.pts)
    output.mux(packet)

output.close()
```

And the corresponding output:

```
-------------------- >> begin captured stdout << ---------------------
frame time_base 1/48000 pts 0
frame time_base 1/48000 pts 2000
frame time_base 1/48000 pts 4000
frame time_base 1/48000 pts 6000
frame time_base 1/48000 pts 8000
frame time_base 1/48000 pts 10000
frame time_base 1/48000 pts 12000
frame time_base 1/48000 pts 14000
frame time_base 1/48000 pts 16000
frame time_base 1/48000 pts 18000
frame time_base 1/48000 pts 20000
frame time_base 1/48000 pts 22000
frame time_base 1/48000 pts 24000
frame time_base 1/48000 pts 26000
frame time_base 1/48000 pts 28000
frame time_base 1/48000 pts 30000
frame time_base 1/48000 pts 32000
frame time_base 1/48000 pts 34000
frame time_base 1/48000 pts 36000
frame time_base 1/48000 pts 38000
frame time_base 1/48000 pts 40000
frame time_base 1/48000 pts 42000
frame time_base 1/48000 pts 44000
frame time_base 1/48000 pts 46000
frame time_base 1/48000 pts 48000
frame time_base 1/48000 pts 50000
frame time_base 1/48000 pts 52000
frame time_base 1/48000 pts 54000
frame time_base 1/48000 pts 56000
frame time_base 1/48000 pts 58000
frame time_base 1/48000 pts 60000
frame time_base 1/48000 pts 62000
frame time_base 1/48000 pts 64000
frame time_base 1/48000 pts 66000
frame time_base 1/48000 pts 68000
frame time_base 1/48000 pts 70000
frame time_base 1/48000 pts 72000
frame time_base 1/48000 pts 74000
frame time_base 1/48000 pts 76000
frame time_base 1/48000 pts 78000
frame time_base 1/48000 pts 80000
frame time_base 1/48000 pts 82000
stream time_base None
packet time_base 1/24 pts 0
frame time_base 1/48000 pts 84000
stream time_base 1/12288
packet time_base 1/24 pts 1
frame time_base 1/48000 pts 86000
stream time_base 1/12288
packet time_base 1/24 pts 2
frame time_base 1/48000 pts 88000
stream time_base 1/12288
packet time_base 1/24 pts 3
frame time_base 1/48000 pts 90000
stream time_base 1/12288
packet time_base 1/24 pts 4
frame time_base 1/48000 pts 92000
stream time_base 1/12288
packet time_base 1/24 pts 5
frame time_base 1/48000 pts 94000
stream time_base 1/12288
packet time_base 1/24 pts 6
-- flush --
stream time_base 1/12288
packet time_base None pts 7

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
libav.mov: WARNING: Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
libav.mov: WARNING: Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
libav.mov: ERROR: Application provided invalid, non monotonically increasing dts to muxer in stream 0: 2048 >= NOPTS
--------------------- >> end captured logging << ---------------------
```

**Comment by jlaine** [comment]
Some interesting points:

- even though it's not apparent from the output, the frame pts are getting altered into a 1/24 timebase at https://github.com/mikeboers/PyAV/blob/9ccd37824e24022439cf69c5f445b1dc77eca0c9/av/codec/context.pyx#L323 and 1/24 was put into `CodecContext.ptr.time_base` by https://github.com/mikeboers/PyAV/blob/9ccd37824e24022439cf69c5f445b1dc77eca0c9/av/container/output.pyx#L92

-  `stream.time_base` is not immediately populated. It only get sets when the first packet is muxed via `OutputContainer.mux` -> `OutputContainer.start_encoding` -> `Stream._finalize_for_output`

- all packets produced as part of the flush have a bogus timebase. The reason for this is that "frame" is None, so we are reading garbage memory (some additional prints showed values like 436/0 for the timebase)

- when these packets get muxed, they are sent through `packet._rebase_time` which clobbers the pts / dts / duration since the source timebase is bogus

**Comment by mikeboers** [comment]
I can't digest this all at once. Getting kinda cross-eyes after a long day of code misbehaving.

Random thoughts:

- I'm also surprised that `_setup_encoded_packet` isn't crashing.
- I've felt for a while that we might need to end up allowing to fully take over time handling, or allow the user handle everything. Something in the middle doesn't quite work. The only thing the `Packet.time_base` was supposed to be for was to be the source of truth of which of the `Stream.time_base` or `CodecContext.time_base` was the one for the circumstance.
- What about doing in completely another direction and embracing floating time? 😝

**Comment by mikeboers** [comment]
From the `HACKING.rst` file, on encoding:

> You then prepare ``AVFrame.pts`` in ``AVCodecContext.time_base``. The encoded ``AVPacket.pts`` is simply copied from the frame by the library, and so is still in the codec's time base. You must rescale it to ``AVStream.time_base`` before muxing (as all stream operations assume the packet time is in stream time base).

And decoding:

> ...everything is in ``AVStream.time_base`` because we don't have to rebase it into codec time base (as it generally seems to be the case that ``AVCodecContext`` doesn't really care about your timing; I wish there was a way to assert this without reading every codec).

I'm wondering if and hoping that `pts` may always be in `Stream.time_base`, and `CodecContext.time_base` should not exist at all. Is this something we can confirm? If it is... then everything can get simpler.

**Comment by mikeboers** [comment]
It seems like [MPEG4](<https://ffmpeg.org/doxygen/4.0/mpeg4videoenc_8c_source.html#l00883>) and [FLV](https://ffmpeg.org/doxygen/4.0/libavcodec_2flvenc_8c_source.html#l00027) do. There are more...

**Comment by mikeboers** [comment]
Another thing is that you set `time_base` on both of them, and FFmpeg only takes them as suggestions. Once encoding starts, it may change them both, and you need to respect it.

I'm not keen on actually making the argument for floating time, but my understanding is that there is more than enough precision in the 53 mantissa.

e.g. You can have 142k years at 1000fps before you lose precision.

**Comment by jlaine** [comment]
I think the current situation is consistent, I'll close this and we can open more issues if/when we identify more problems.
