### ISSUE TITLE
Assert compatible FFmpeg

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#401]
Check that we support the given FFmpeg during build, and runtime.

**Comment by jlaine** [comment]
At build time my preferred option would be something along the lines of doing an "import av" and checking it doesn't bomb..

**Comment by mikeboers** [comment]
Lol.

One idea I had was to split up the `build_ext` command into `build_ext_version` and `build_ext_main`, which are exactly the same except that one of them builds a `av._version` module, and the other builds the rest.

The `_version` module burns in the compile-time versions (via macros), and has the runtime versions (via functions).

We can then import it before building the rest of them, check the versions are reasonable, complain if they aren't, and then go on building the rest of them.

**Comment by jlaine** [comment]
Keep it simple, we should not be re-inventing the compiler / linker / dynamic linker's jobs.

**Comment by mikeboers** [comment]
I just want something that is verbose in the case that the user's FFmpeg is too old, as it will save us a lot of GitHub issues.

**Comment by jlaine** [comment]
In that case I'd vote for an #if on LIBAVCODEC_VERSION for example which spews an explicit #error

**Comment by jlaine** [comment]
Haha, I just saw your comment on #393 suggesting exactly the #if / #error combo, nice :)

**Comment by mikeboers** [comment]
You can grab it via `pkg-config`?! Madness.

Will you let me do both? lol

**Comment by jlaine** [comment]
I'd much rather have a single source of truth (the LIB*_VERSION_INT), much easier to maintain.

**Comment by mikeboers** [comment]
_grumble grumble_ You're right.
