### ISSUE TITLE
Rethink the build/runtime strategy.

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#410]
Now that we're only using FFmpeg, we could do all of the function detection implicitly at runtime by inspecting version numbers.

We could, potentially, ship a PyAV that can link against arbitrary FFmpeg's at runtime. You could update your FFmpeg, or use `*LD_LIBRARY_PATH` to change it.

We could then go so far as to ship wheels of PyAV, and (if we really really wanted to) wheels of FFmpeg for PyAV to use.

**Comment by mikeboers** [comment]
@jlaine was pitching that this would be more likely achieved by "manually" loading the libraries and functions at runtime, and that would turn into a clustercuss.

Since we're generating source code, that really isn't that horrible of an idea. I was personally thinking that we build with the compiler ignoring unknown symbols, and be very careful at runtime to not trigger ones that will not exist (as they should then be loaded at call time).

This could all be a bad idea, and we just accept that PyAV is built only for the installed FFmpeg, and warn the user when the runtime versions have diverged from the build ones.

**Comment by jlaine** [comment]
As mentioned in another ticket, the *generated* C code is now independent of the FFmpeg version, since we don't use "reflect" anymore. The only thing that is dependent on the FFmpeg version is what gets *compiled* (#if), and this is captured in the SONAME, so PyAV will always load the compatible FFmpeg. I think this can be closed.

**Comment by mikeboers** [comment]
To be fair, the generated C code was always independent. `setup.py` did (and still does) generate a header file which used to include the feature detection macros.

You are technically correct, and it brings us to the same level that every other compiled Python package has. But we do still end up dealing with GitHub issues about build problems, and making the build process "smarter" might help there.

But we won't know till we try, so I'll close this until we start seeing what the new issues are, and what we can do to mitigate them at that point.
