### ISSUE TITLE
Strip the `reflect` setup.py command.

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#416]
We no longer have a use for it, and I suspect that the build-time version checking will be done another way.

We could/should strip out that functionality, and everything in `setup.py` that existed to support it.

I think that we should, for a while, leave a `reflect` command that does nothing except indicate that it is deprecated. I think this because I've left quite a few messages around about running the reflect command, and I'd like it not to fail hard on people.

**Comment by jlaine** [comment]
With reflect out of the way, we may actually be able to support builds against a static ffmpeg - which would be my preferred option for distributing a binary wheel.

**Comment by mikeboers** [comment]
That would be wacky!

My past experience with that sort of things is with [PyTomCrypt](https://github.com/mikeboers/pytomcrypt) (which was my first Cython-wrapping project). It compiles LibTomCrypt itself, and links it into the `_core` module. At first import, it [uses ctypes to assert that symbols are resolved globally](https://github.com/mikeboers/PyTomCrypt/blob/master/tomcrypt/__init__.py#L14-L20) (or something something).
