### ISSUE TITLE
Homebrew ffmpeg too modern for pyav

### ISSUE THREAD

**Issue by davidavdav** [mikeboers/PyAV#442]
I've landed myself in version-hell by upgrading ffmpeg (macos `brew install ffmpeg`), not really intentionally, but hey, it happened. 

ffmpeg on brew now is version 4.0.2_1, with libraries like
```
usr/local/Cellar/ffmpeg/4.0.2_1/lib/libavcodec.58.18.100.dylib
```
which are all 1 version number higher than pyav expects. 
```
import av
Library not loaded: /usr/local/opt/ffmpeg/lib/libavcodec.57.dylib
```

Unfortunately, brew ffmpeg@3.3.4 which provides these versions, is gone.  I've tried manually linking newer to older versions of the ffmpeg libraries but that of course doesn't work either. 

Is there any way that pyav can be built against the +1 version numbers of the ffmpeg libraries?

**Comment by mikeboers** [comment]
PyAV is tightly tied to the version of FFmpeg that was installed at build time. You should be able to re-install PyAV against the new one.

I'm building 4.0.2 now just to be sure.

**Comment by mikeboers** [comment]
My tests just passed. I'm calling PyAV compatible with 4.0.2, but seems like it needs an irritating re-install.

**Comment by davidavdav** [comment]
Thanks, but how do you build/install pyav your way?  I just install using `pip install pyav`, but that gave me the old library dependencies, i.e., the pip version doesn't seem to be building anything.

**Comment by davidavdav** [comment]
No, that doesn't build anything for me.  I might try to pip install directly from github.

**Comment by aleksandergurin** [comment]
Maybe we should reopen this issue and fix it?

Although last comment from @davidavdav works, I suppose, that simple `pip install av` should work on modern mac os.

**Comment by mikeboers** [comment]
IIRC I wasn't able to directly reproduce the problem with pip not rebuilding. If you can do that I encourage you to open a new issue. 👍
