### ISSUE TITLE
how to extract key frames by pyAV？

### ISSUE THREAD

**Issue by kli-nlpr** [mikeboers/PyAV#447]
``
ffmpeg -v quiet -skip_frame nokey -i video.mp4 -vsync passthrough img_%04d.jpg
``

**Comment by kli-nlpr** [comment]
@mikeboers  Can you help me? I really need this feature, after googling several days I can not find the solution. thanks.

**Comment by mikeboers** [comment]
Do the [typical decode loop](http://docs.mikeboers.com/pyav/develop/index.html#basic-demo), check [VideoFrame.key_frame](http://docs.mikeboers.com/pyav/develop/api/video.html#av.video.frame.VideoFrame.key_frame), and save it [via pillow](http://docs.mikeboers.com/pyav/develop/api/video.html#av.video.frame.VideoFrame.to_image):


```
import av

container = av.open('video.mp4')

for frame in container.decode(video=0):
    if frame.key_frame:
        frame.to_image().save('img_%04d.jpg' % frame.index)
```

(Note that I've not actually run this.)

**Comment by jlaine** [comment]
I just tried running the suggested code and can confirm it works. The numbering scheme will be slightly different though, as ffmpeg will generate consecutive (1-based) image numbers (img_0001.jpg, img_0002.jpg), while the suggested code with ffmpeg will use the frame's original (0-based) index.

**Comment by kli-nlpr** [comment]
@mikeboers  @jlaine  Thanks，this really works, but it is much slower than the ffmpeg commond

**Comment by kli-nlpr** [comment]
So how to ``-skip_frame nokey``

**Comment by jlaine** [comment]
The reason it's slower is that all frames are decoded, and then we check whether they are keyframes. Looking at the FFmpeg code, it would seem it uses AVCodecContext.skip_frame to discard frames as early as possible.

The PyAV equivalent would be:

```
import av
  
container = av.open('video.mp4')

stream = container.streams.get(video=0)[0]
stream.codec_context.skip_frame = 'NONKEY'

for frame in container.decode(video=0):
    frame.to_image().save('img_%04d.jpg' % frame.index)
```

**Comment by kli-nlpr** [comment]
@jlaine  Thank you very much，I will try it out.

**Comment by kli-nlpr** [comment]
@jlaine perfect, it runs much faster now, thanks
