### ISSUE TITLE
straming

### ISSUE THREAD

**Issue by sbeneduce** [mikeboers/PyAV#449]
Can i use to stream to youtube?

ffmpeg \ -f alsa -ac 2 -i hw:1,0 \ -f v4l2 -r 10 -i /dev/video0 \ -c:v libx264 -pix_fmt yuv420p -preset ultrafast -g 20 -b:v 2500k \ -c:a aac -ar 44100 \ -threads 0 -bufsize 512k \ -f flv rtmp://a.rtmp.youtube.com/live2/YOURSTREAM

**Comment by jlaine** [comment]
Just to be clear : PyAV is not meant the ffmpeg command line. If your ffmpeg command works for you - that might just be the right solution. PyAV's strength resides in its deep integration with libav* which allow you to do more domain-specific operations using Python code.
