### ISSUE TITLE
SIGBUS Crash occurred when stream search with special MXF(SONY F55RAW)

### ISSUE THREAD

**Issue by KengoSawa2** [mikeboers/PyAV#450]
Hello.

I love PyAV. Thank you for a wonderful library:)

I found a problem.
If you open a special MXF with PyAV, SIGBUS will occur.

As far as I've seen, it seems that some function becomes an infinite loop and destroys the stack frame.
The problem data and reproduction code, Mac crash report data are summarized below.
https://lespa.firestorage.jp/download/f80da205bc2e84ae0cb6e17f2025db6684484c9c

I am glad that this problem is solved.
(I am making software to search all folders and create a shotlist)
Thank you.

Environment:
PyAV 6.0.0
macOS 10.11.6
ffmpeg 4.0.2
Python3.4

**Comment by jlaine** [comment]
Could you please provide a sample file and some code?

**Comment by jlaine** [comment]
OK I'm also getting a crash. It looks as though this is happening while parsing the stream's metadata, I'll try digging into it.

The file seems to be an odd one in anycase, ffprobe also gives me plenty of warnings.

**Comment by jlaine** [comment]
@mikeboers the problem seems to be due to the `Stream.__getattr__` magic : if the stream contains an unknown codec, `self.codec_context` does not exist, and so calling something as basic as `stream.type` leads to an infinite loop:

- `__getattr__('type')`
- `__getattr__('codec_context')`
- `__getattr__('codec_context')`
...

**Comment by jlaine** [comment]
@mikeboers I have a fix for the crash, but I'd like to lock it down with a unit test. Does the FATE suite contain examples of unsupported codecs?

**Comment by mikeboers** [comment]
@jlaine I've never found one.
