### ISSUE TITLE
Add InputContainer.close()

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#456]
Continuing from #286:

We should have an explicit `InputContainer.close()`. Pretty much move the logic we can from the destructor to the new method, and have a `closed` property to be a gateway.

**Comment by jlaine** [comment]
I'd be happy to give this a shot, but would appreciate your insights on #438 : do we want these "strict" options at all?

**Comment by jlaine** [comment]
There is a PR for this in #513
