### ISSUE TITLE
LINK: fatal error LNK1181 - In Insulation

### ISSUE THREAD

**Issue by mariofraga** [mikeboers/PyAV#466]
I'm trying to install PYAV in Windows 10
Python Version 3.6.0

follows the error:

 LINK : fatal error LNK1181: não foi possível abrir o arquivo de entrada 'swresample.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181

**Comment by mariofraga** [comment]
python setup.py build --ffmpeg-dir=C:\ffmpeg
running build
running build_py
running build_ext
running config
writing build\temp.win-amd64-3.6\Release\include\pyav\config.h
running cythonize
building 'av.buffer' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

**Comment by mikeboers** [comment]
I'm not sure what the error is even supposed to be here.

Is it complaining that you need v14 of the compiler... from v14 of the compiler? 😛

**Comment by kesaroid** [comment]
@mikeboers I am having the same issue. Even after installing Visual C++ Build tools, it gives an error with exit code 1181. I even tried building PyAV from source with ffmpeg. It doesn't seem to work.
Please Help

**Comment by JackD83** [comment]
You need Visual Studio 2015 (not 2017 or 2019!) 
It worked for me after I put ffmpeg\lib and ffmpeg\bin into the PATH

**Comment by jlaine** [comment]
That's kind of annoying, any idea why we are stuck with VS 2015?

**Comment by JackD83** [comment]
I suspect it has something to do with pythons setuptools, but I'm not sure.

**Comment by dustsigns** [comment]
I managed to make `pip install av` work on Windows 10 with Visual Studio 2019 by setting compiler and linker variables. I described the steps in [this gist](https://gist.github.com/dustsigns/978f505cd190b7e64f140d6295faf62a). It works for me and multiple of my coworkers. I can create a pull request for the `docs` folder to include the steps, if this is desired.

**Comment by leemon323** [comment]
It works for me with the method by copy the lib files into the python "libs" directory and the include directories into the "includes" directory, which can also be seen in this site, https://github.com/mikeboers/PyAV/issues/467

**Comment by jlaine** [comment]
Since release 8.0.0, binary wheels are provided on PyPI so installing `PyAV` on Windows no longer requires any compilation.
