### ISSUE TITLE
Error installing on windows 10

### ISSUE THREAD

**Issue by mariofraga** [mikeboers/PyAV#467]
ERROR 1:
LINK : fatal error LNK1181: cannot open input file 'avcodec.lib'
  error: command 'C:\\Users\\mario\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1181

  ----------------------------------------
  Failed building wheel for av

ERROR 2:
LINK : fatal error LNK1181: cannot open input file 'avcodec.lib'
    error: command 'C:\\Users\\mario\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1181

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\mario\\appdata\\local\\temp\\pip-install-wbsmzo\\av\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\mario\appdata\local\temp\pip-record-jc7tqc\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\mario\appdata\local\temp\pip-install-wbsmzo\av\

Can anyone help?

**Comment by kesaroid** [comment]
I am facing the exact same problem and I have tried everything. Conda install works fine, but installing PyAV through pip and source. I have zero luck with the same exit status 1181. [follow more](https://github.com/hanyazou/TelloPy/issues/40#issuecomment-460593026)

**Comment by aspen1135** [comment]
Is there any resolution to this? I am having the same issue. I have downloaded the latest windows tool kit, and VS 2015. IDK what I am missing.

**Comment by jlaine** [comment]
As I don't have access to a Windows machine, I can't directly test this. I think our only hope is using appveyor to trigger this issue, but it uses a convoluted build setup relying on conda.

**Comment by jmiles2irvine** [comment]
I was able to make it work by copy the lib files into the python "libs" directory and the include directories into the "includes" directory. You could also modify the path for both file types.

**Comment by leemon323** [comment]
It works for me with the method by @jmiles2irvine ，thanks very much!
