### ISSUE TITLE
av.AVError: [Errno 22] Invalid argument (16: libmp3lame)

### ISSUE THREAD

**Issue by cdhcrs** [mikeboers/PyAV#470]
Can you tell me the correct way to write it?
`pa=PyAudio()`
`stream=pa.open(format = paInt16,channels=1,
rate=8000,input=True,
frames_per_buffer=1152)`
`container=av.open('2.mp3','w')`
`audiostream= container.add_stream('mp3',rate=8000)`
`audiostream.format='s16'`
`print(audiostream)`
`string_audio_data = stream.read(1152)`
`dt=np.dtype('<i2')`
`a=np.fromstring(string_audio_data,dtype=dt)`
`a.shape=(1,1152)`
`frame=av.AudioFrame.from_ndarray(a)`
`container.mux(audiostream.encode(frame))`
`print(audiostream.encode(frame))`

`audiostream.format='s16'`
So if I delete this line of code, `audiostream.encode(frame)` returns []

**Comment by jlaine** [comment]
I'm going to close this issue, feel free to re-open it if the provided snippet doesn't solve your problem.
