### ISSUE TITLE
decode, annotate, re-encode with PyAV and OpenCV?

### ISSUE THREAD

**Issue by alexhutnik** [mikeboers/PyAV#473]
I'm sure this is pretty straightforward but I'm looking for some advice on how to efficiently do this.  I want to read a video file, convert each frame to a numpy array, use the numpy array in some OpenCV drawing functions, and then re-encode the frame in to a new output stream.

The thing I'm specifically unsure of is how to go back and forth between PyAV frames and OpenCV and then how to re-encode the numpy array as a frame.

**Comment by jlaine** [comment]
The `VideoFrame.to_ndarray` and `VideoFrame.from_ndarray` functions will handle the conversion to / from OpenCV for you. The one piece of information you will need to carry over yourself is frame timing, as OpenCV has no equivalent concept: all it manipulates are arrays of pixels.

You code will look something like this:

```python
import av
import cv2


# open input and find video stream
input_container = av.open('input.mp4', 'r')
input_stream = input_container.streams.get(video=0)[0]

# open output and add a video stream
output_container = av.open('output.mp4', 'w')
output_stream = output_container.add_stream('h264', rate=input_stream.rate)

for frame in input_container.decode(input_stream):
    # perform edge detection
    img = frame.to_ndarray(format='bgr24')
    img = cv2.cvtColor(cv2.Canny(img, 100, 200), cv2.COLOR_GRAY2BGR)

    # rebuild a VideoFrame, preserving timing information
    new_frame = av.VideoFrame.from_ndarray(img, format='bgr24')
    new_frame.pts = frame.pts
    new_frame.time_base = frame.time_base

    # encode and mux
    for packet in output_stream.encode(new_frame):
        output_container.mux(packet)

# flush and close output
for packet in output_stream.encode(None):
    output_container.mux(packet)
output_container.close()
```

**Comment by jlaine** [comment]
@mikeboers would you consider including this code in an example?
