### ISSUE TITLE
Cluelessness with codecs / Video-pixelation

### ISSUE THREAD

**Issue by TheRedCupDude** [mikeboers/PyAV#483]
Hi guys, 

i have a problem in my code and i think its caused by the codec (or probably by me).

    codec = 'libx264'
    images = [img for img in os.listdir(plots_path) if img.endswith(".png")]
    images.sort()
    frame = cv2.imread(os.path.join(plots_path, images[0]))
    height, width, layers = frame.shape 

    video_name = video_path + os.path.sep + str(name) + ".mp4"

    video_file = av.open(video_name, 'w')
    stream = video_file.add_stream(codec,fps)
    stream.time_base = Fraction(1,1000)
    stream.pix_fmt = 'yuv420p'
    for i,image in enumerate(images):
        img=Image.open("plots/"+str(image))
        frame= av.VideoFrame.from_image(img)
        frame.pts=frame_time[i]
        packet = stream.encode(frame)
        video_file.mux(packet)

        os.remove(plots_path + os.path.sep + str(image))

    video_file.close()`

I will briefly describe my code: 
It will take a list of images and turn them into a video-file.
'frame_time' is an array with the specific time (in ms) at which the frame should be shown.
Therefore im setting the stream.time_base to Fraction(1,1000) that one time_base-unit should be 1ms right?
If im using some functions wrong etc. please feel free to correct me :)

But now to my problem:

When i use the codec 'mpeg4' the video will lose quality the longer it goes and at the end it will have a very pixelated quality but the video will render till the end.
But when i use the codec 'libx264' the quality will stay super sharp, but the video won't render till the end. The last 0.5 seconds won't be in the video.

I will appreciate every help i'd get and im sorry for the inconvenience.

Thanks guys

//Edit: 
i added this at the end:
`    for packet in stream.encode():
              video_file.mux(packet)`

and now the libx264 is working (the video is playing until the end).
But the mpeg4 version is still getting very pixelated (which is probably a mistake of mine?!)

Its working for me now so this thread could be closed, unless the pixelation of mpeg4 isnt my fault.

PS: Im fairly new to PyAv, so if you see ways to improve my code or give me tips in any way, im more than happy to hear it ;) 

Greets TheRedCupDude

**Comment by jlaine** [comment]
Why would you use OpenCV + PyAV to read frames when `ffmpeg` has built-in support for them?

This doesn't look like a usecase where PyAV is the best tool for the job, I'd suggest you experiment with:

`ffmpeg -r INPUT_FPS -i somename%04d.png -r OUTPUT_FPS somename.mp4`

The pixelisation has about 0% chance of being due to PyAV.

**Comment by mikeboers** [comment]
My guess with the "pixelation" problem is the default settings for `mpeg4` are not great.

My takeaway from this issue is that an `av.flush()` or something that deals with the boilerplate of muxing the final packets would be great.

Unless there is something else, shall we close?

**Comment by jlaine** [comment]
@mikeboers yup, closing
