### ISSUE TITLE
Error when connecting to RTSP stream from Docker container

### ISSUE THREAD

**Issue by frantgn90** [mikeboers/PyAV#486]
It seems that some thing is failing when I try to connect to an rtsp stream from a docker container using pyav. The error that I've got by calling `av.logging.get_last_error()`is:
```
(1, (16, 'rtsp', u'method SETUP failed: 455 Method Not Valid in this State\n'))
```
Additionally I have the next message when calling the `av.open("rtsp://...")`
```
No handlers could be found for logger "libav.rtsp"
```
Could anybody give me a clue?

Just mention I've installed all the dependencies in the docker image according to your documentation for Ubuntu18.04. I have it working out of docker so my guess is that I am missing some dependency or something. Does it make sense?

Thanks!

**Comment by frantgn90** [comment]
I want to mention. Out of docker I am having this by executing `cam.streams.video`:
`<av.VideoStream #0 h264, yuvj420p 1280x720 at 0x7fa741126668>`
In the other way arround, in docker I am having:
`<av.VideoStream #0 h264, None 0x0 at 0x7f3d68197cf8>`

**Comment by mikeboers** [comment]
Try running `logging.basicConfig()` so you get the logs. Maybe there are more helpful things in there.

**Comment by frantgn90** [comment]
Nice clue! By doing what you suggested I've seen the next error:
```
WARNING:libav.rtsp:UDP timeout, retrying with TCP
ERROR:libav.rtsp:method SETUP failed: 455 Method Not Valid in this State
WARNING:libav.rtsp:Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
```
I fixed that by enforce rtsp over tcp:
```
av.open(camera_uri, options={"rtsp_transport":"tcp"})
```
Thanks!

**Comment by jlaine** [comment]
Thanks for letting us know how you solved your issue!
