### ISSUE TITLE
Win10: ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by FlorentGia** [mikeboers/PyAV#490]
Hello,
I'm trying to install PyAv:
- I downloaded FFmpeg dev version
- I installed requirements with pip
- I built last PyAV version with 'python setup.py build --ffmpeg-dir="..."'
- and finally I installed with 'python setup.py install --ffmpeg-dir="..."'

but when I try to import av I have this error:

>>> import av
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\av-6.1.3.dev0-py3.6-win-amd64.egg\av\__init__.py", line 9, in <module>
    from av._core import time_base, pyav_version as __version__
ImportError: DLL load failed: The specified module could not be found.

Do you know what I did wrong ?

**Comment by jlaine** [comment]
If you installed FFmpeg in some unusual location you'll need to help PyAV find it at runtime. Can you try adding the directory where the .dll lives to your PATH and try again to import `av`?

**Comment by jlaine** [comment]
No response from submitter, closing.

**Comment by michen00** [comment]
How does one find the correct .dll? I am having trouble finding the right directory and file name.

**Comment by lbourdois** [comment]
I had the same error, I could fix it with `pip install av==9.1.0`

**Comment by jlaine** [comment]
> I had the same error, I could fix it with `pip install av==9.1.0`

That's a different issue, see #952
