### ISSUE TITLE
Custom ffmpeg location

### ISSUE THREAD

**Issue by jhnbyrn** [mikeboers/PyAV#492]
How does pyav determine the location of the ffmpeg libraries? I have built ffmpeg from source, and I'd like to use that build for pyav. By default, _make install_ has installed the libraries in /usr/local/lib/. I'm not sure where the older version is. I'm using Raspbian Stretch. 

Is there a way I can:

1. See the location of the libraries that pyav is using, and
2. Make it use my newly built libraries?

**Comment by jlaine** [comment]
PyAV uses pkg-config to find ffmpeg. You can use `PKG_CONFIG_PATH` to override where pkg-config looks for `.pc` files:

https://linux.die.net/man/1/pkg-config
