### ISSUE TITLE
average_rate is None

### ISSUE THREAD

**Issue by frantgn90** [mikeboers/PyAV#494]
Hello,

I am using pyav to decode RTSP streams. My end is to subsample the decoded frames in order to store video at a given low FPS rate. In order to do so I need the actual FPS of the stream so what I do is:
```
self._connection = av.open(camera_uri, options={"rtsp_transport":"tcp"})
self._video_stream = self._connection.streams.video[0]
self._camera_fps = self._video_stream.average_rate
```
It turns out that it is always returning None. Do I need to do something extra to have this data?
Thanks!!

**Comment by jlaine** [comment]
Could you try running `ffprobe` on your RTSP stream and paste what it reports?

**Comment by jlaine** [comment]
Closing, no response from submitter.
