### ISSUE TITLE
How I create video with transparency by frames in RGBA?

### ISSUE THREAD

**Issue by JulienLeal** [mikeboers/PyAV#500]
Hi people,

I'm trying to create video with transparency by the frames that I read in .MOV with transparency.
I know it need as .MOV and the codecs that I can do it is "png" and "dxv3" for example.
But i can't do it.

I tried like it, but doesn't works:
 output = av.open('output_av.MOV', 'w')
 stream = output.add_stream('dxv', '30') ???

It works, but without transparency, because mp4 doesn't supports:
output = av.open('output.mp4', 'w')
stream = output.add_stream('mpeg4', '28')

What's my stream in that case? What's codec can I use using PyAv?

Thanks

**Comment by jlaine** [comment]
Can you please provide the MOV file you are working on?

**Important**: ensure you have the copyright for this file!

**Comment by ArtanisCV** [comment]
Maybe too late...You can use prores_ks:

```python
outp_stream = container.add_stream("prores_ks", rate=rate)
outp_stream.pix_fmt = "yuva444p10le"
```

You still need mov as the container. MP4 doesn't support transparency, unfortunately.

**Comment by mikeboers** [comment]
Closing due to lack of response from OP.

**Comment by robinechuca** [comment]
The python libray 'cutcutcodec' is able to manage and to write video with alpha channel.
