### ISSUE TITLE
Missing tag for 6.1.2

### ISSUE THREAD

**Issue by scarabeusiv** [mikeboers/PyAV#506]
There is no tag for the release in the github repo, could  you please add it?

**Comment by jlaine** [comment]
@mikeboers is it just a matter of you doing a `git push --tags`?

**Comment by mikeboers** [comment]
_looks around bashfully_

Yes.

**Comment by jlaine** [comment]
I'm re-opening this: the v6.1.2 tag seems to point to the wrong version?

**Comment by mikeboers** [comment]
I also noticed they were in the wrong order. I did miss a few tags as there were releases, and it seems like GitHub puts them in order of when they were actually created, rather than commit order.

**Comment by mikeboers** [comment]
I retagged the last 6 of them. Looks good now.
