### ISSUE TITLE
Error with `pip install av` "pkg-config returned flags we don't understand: -pthread -pthread"

### ISSUE THREAD

**Issue by gdavidmac** [mikeboers/PyAV#510]
Trying to install PyAV in a virtualenv with FFMPEG built from source.

`PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" pip install av` fails with:

```
  running config
  pkg-config returned flags we don't understand: -pthread -pthread
  ----------------------------------------
  ERROR: Failed building wheel for av
  Running setup.py clean for av
```

FFMPEG 4.1.3 was built from source according to the usual FFMPEG build instructions. Specific configure and build command was:

```
cd ~/ffmpeg_source && \
wget -O ffmpeg-4.1.3.tar.bz2 https://ffmpeg.org/releases/ffmpeg-4.1.3.tar.bz2 && \
tar xjvf ffmpeg-4.1.3.tar.bz2 && \
cd ffmpeg-4.1.3 && \
PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
  --prefix="$HOME/ffmpeg_build" \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$HOME/ffmpeg_build/include" \
  --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
  --extra-libs="-lpthread -lm" \
  --bindir="$HOME/bin" \
  --enable-gpl \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libopus \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-nonfree && \
PATH="$HOME/bin:$PATH" make -j$((`nproc` - 1)) && \
make install && \
hash -r
```

**Comment by jlaine** [comment]
Static builds are currently not supported by PyAV's build system.

**Comment by jlaine** [comment]
Modifying PyAV's setup.py to support `-pthread` is fairly trivial.

However, after many attempts I have been unable to successfully link against statically compiled ffmpeg libraries. AFAICT ffmpeg has multiple symbols which would need a `visibility` attribute for a static ffmpeg build to be usable in a shared library such as a Python module.

That being the case I'm not sure it's worth modifying setup.py..

**Comment by mikeboers** [comment]
I'll make my periodic ask: anyone know how to detect that it will link against a static library and stop it? So many GitHub issues would be resolved if the build system would just say "We can't link to static FFmpeg."

**Comment by gregory-whaley** [comment]
I have a similar error also when trying to install onto Raspbian Jesse.  I too had compiled ffmpeg from source.  Any suggestions?

**Comment by jlaine** [comment]
The suggestion is: don't create a static ffmpeg build. Also if you use Raspbian Stretch, you should already have a pre-compiled PyAV, courtesy of piwheels: https://www.piwheels.org/project/av/

**Comment by hsharrison** [comment]
I'm trying to compile PyAv in order to use the hwaccel branch, and I'm having trouble. I started with a clean VM and didn't compile anything myself besides running `scripts/build-deps`. It compiled succesfuly but now I'm getting `No module named 'av._core'`. Any ideas what went wrong?

**Comment by ramoncaldeira** [comment]
I have this error trying to use the av package with an ffmpeg build configured to use h264_cuvid as a hardware decoder. It is not a static build.

```Installing collected packages: av
  Running setup.py install for av: started
    Running setup.py install for av: finished with status 'error'
    ERROR: Complete output from command /apps/conda/ramon.caldeira/.envs/av/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-ajt1foa1/av/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_ksbgq8i/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/av
    copying av/__main__.py -> build/lib.linux-x86_64-3.7/av
    copying av/__init__.py -> build/lib.linux-x86_64-3.7/av
    copying av/datasets.py -> build/lib.linux-x86_64-3.7/av
    copying av/deprecation.py -> build/lib.linux-x86_64-3.7/av
    creating build/lib.linux-x86_64-3.7/av/codec
    copying av/codec/__init__.py -> build/lib.linux-x86_64-3.7/av/codec
    creating build/lib.linux-x86_64-3.7/av/video
    copying av/video/__init__.py -> build/lib.linux-x86_64-3.7/av/video
    creating build/lib.linux-x86_64-3.7/av/subtitles
    copying av/subtitles/__init__.py -> build/lib.linux-x86_64-3.7/av/subtitles
    creating build/lib.linux-x86_64-3.7/av/container
    copying av/container/__init__.py -> build/lib.linux-x86_64-3.7/av/container
    creating build/lib.linux-x86_64-3.7/av/filter
    copying av/filter/__init__.py -> build/lib.linux-x86_64-3.7/av/filter
    creating build/lib.linux-x86_64-3.7/av/data
    copying av/data/__init__.py -> build/lib.linux-x86_64-3.7/av/data
    creating build/lib.linux-x86_64-3.7/av/audio
    copying av/audio/__init__.py -> build/lib.linux-x86_64-3.7/av/audio
    running build_ext
    running config
    pkg-config returned flags we don't understand: -pthread -pthread
```

**Comment by Fruchtzwerg94** [comment]
I hat the same problem. For me the following solution worked:

1. Building ffmpeg with the flag `--enable-shared`
2. Check ffmpeg is running, maybe the lib path is missing (add `/usr/local/lib` to `LD_LIBRARY_PATH`)
3. Clone PyAV
4. Comment out [line 95 in setup.py](https://github.com/mikeboers/PyAV/blob/develop/setup.py#L95)
5. source scripts/activate.sh
6. make
7. Add the directory to `PYTHONPATH` if you are not installing the package

**Comment by VirtualAirwaves** [comment]
@Fruchtzwerg94 -- did you have to add -fPIC to cflags when building the ffmpeg you're linking to?  I'm getting a linker error and I don't want to be running down a rathole. (Trying it though!)

**Comment by Fruchtzwerg94** [comment]
> 
> 
> @Fruchtzwerg94 -- did you have to add -fPIC to cflags when building the ffmpeg that PyAV is linking to? I'm getting a linker error and I don't want to be running down a rathole. (Trying it though!)

No, I didn't specify any other linker flags.

**Comment by VirtualAirwaves** [comment]
I'm getting these errors. I tried -fPIC, too, and still got it. I need to check to see if they really were compiled right.

```
/bin/ld: /usr/local/lib/libavdevice.a(fbdev_common.o): relocation R_X86_64_32 against `.rodata' can not be used when ma
king a shared object; recompile with -fPIC
/bin/ld: /usr/local/lib/libavdevice.a(oss.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when maki
ng a shared object; recompile with -fPIC
/bin/ld: /usr/local/lib/libavdevice.a(v4l2-common.o): relocation R_X86_64_32 against symbol `ff_fmt_conversion_table' c
an not be used when making a shared object; recompile with -fPIC
```

**Comment by jkurdzieko** [comment]
I have same errors, too. Did you find solution.

**Comment by VirtualAirwaves** [comment]
> I have same errors, too. Did you find solution.

Yes, I had to take a private copy and comment out the line in the setup.py that calls exit(0) if it sees this flag.

**Comment by jlaine** [comment]
As of PyAV 8.0.0, binary wheels are provided which will greatly simplify installation and should solve your issue.
