### ISSUE TITLE
WARNING:libav.libmp3lame:4 frames left in the queue on closing

### ISSUE THREAD

**Issue by mephi42** [mikeboers/PyAV#511]
I'm trying to encode audio using the following code:

```
        for frame in input_.decode(audio=0):
            # https://github.com/mikeboers/PyAV/issues/221#issuecomment-304858333
            frame.pts = None
            for packet in mp3_audio.encode(frame):
                mp3_container.mux(packet)
        for packet in mp3_audio.encode():
            mp3_container.mux(packet)
```

It works fine, but prints the following warnings:

```
WARNING:libav.mp3:Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
WARNING:libav.libmp3lame:4 frames left in the queue on closing
```

The first one looks harmless, but should I worry about the second one? Can this be a problem in ffmpeg, pyav or my code?

**Comment by jlaine** [comment]
Do you still get the warning if you add the following at the end:

```python
for packet in mp3_audio.encode(None):
    mp3_container.mux(packet)
```

**Comment by mephi42** [comment]
I tried changing the existing `mp3_audio.encode()` to `mp3_audio.encode(None)`, but unfortunately that did not help.

**Comment by jlaine** [comment]
Ah sorry I missed your second call to `encode()`. Can you try to add a second such call?

This example makes me think more than one flush might be needed:

https://github.com/mikeboers/PyAV/blob/03d9b78a7117e443e39fbff1daeaf9995899e15b/scratchpad/encode.py#L72

**Comment by jlaine** [comment]
To have a valid comparison could you try performing the same transcoding using `ffmpeg` on the command line and report whether it gives you any warnings?

**Comment by mephi42** [comment]
Calling `encode()+mux()` multiple times unfortunately did not help.

I tried using the following command, and it did not print any warnings:

```
$ ffmpeg -y -i "$mp4" -vn -acodec mp3 -ar 16000 -b:a 64k "$mp3"
```

**Comment by jlaine** [comment]
Damn, in that case it does look like a PyAV issue. Do you have a *freely licensed* example input file I can use ?

**Comment by mephi42** [comment]
Code and .mp4 file: [PyAV-511.tar.gz](https://github.com/mikeboers/PyAV/files/3144862/PyAV-511.tar.gz)

**Comment by jlaine** [comment]
It looks as though the problem comes from our use of `AudioFifo.read_many`.

When we are flushing the output, we write pass a `None` frame to:

https://github.com/mikeboers/PyAV/blob/21388b7a678bd68633cf4d580df8b7295da1722c/av/audio/codeccontext.pyx#L27

which in turn calls:

https://github.com/mikeboers/PyAV/blob/21388b7a678bd68633cf4d580df8b7295da1722c/av/audio/codeccontext.pyx#L50

However if we look at the code for `read_many` we see that it "swallows" the flush frame:

https://github.com/mikeboers/PyAV/blob/21388b7a678bd68633cf4d580df8b7295da1722c/av/audio/fifo.pyx#L167

The following patch eliminates the warning for me:

```diff
diff --git a/av/audio/codeccontext.pyx b/av/audio/codeccontext.pyx
index 5eb3e36..4db0ef7 100644
--- a/av/audio/codeccontext.pyx
+++ b/av/audio/codeccontext.pyx
@@ -49,6 +49,8 @@ cdef class AudioCodecContext(CodecContext):
                 self.fifo.write(frame)
             frames = self.fifo.read_many(self.ptr.frame_size, partial=is_flushing)
 
+            if is_flushing:
+                frames.append(None)
         else:
             frames = [frame]
 
```
