### ISSUE TITLE
Can't create an AudioFrame from_ndarray

### ISSUE THREAD

**Issue by morrolinux** [mikeboers/PyAV#523]
Hello,
I'm trying to generate silence in wav format:
```
silence = np.zeros((2, 1152))
frame = av.AudioFrame.from_ndarray(silence)
```
But it crashes with:
```  
File "av/audio/frame.pyx", line 120, in av.audio.frame.AudioFrame.from_ndarray
AssertionError 
```

**Comment by mikeboers** [comment]
There are a number of asserts in there that ought to be more descriptive.

In the meantime, I'd advise that you specify an audio format (it defaults to `s16`) and numpy dtype, e.g.:

```
>>> silence = np.zeros((2, 1152), dtype='int16')
>>> frame = av.AudioFrame.from_ndarray(silence, 's16p')
```

**Comment by morrolinux** [comment]
Thanks for the answer! that was it. 
I now seem to have succesfully encoded the frame via ``` out_pack = out_stream.encode(frame) ``` but just discovered that doing that in a loop fails on the second iteration, so I probably lack some background here, why can't I just generate and encode an `AudioFrame` like so?
```
        for _ in range(10):
            frame = av.AudioFrame.from_ndarray(silence, 's16p')
            frame.pts = None
            out_pack = out_stream.encode(frame)
            if out_pack:
                out_container.mux(out_pack)
            else:
                break   # It does break on second iteration
```
Thanks again for your time

**Comment by jlaine** [comment]
If you want to generate silence, you don't even need to use numpy at all.

```python
import av
  

with av.open('test.wav', 'w') as out_container:
    out_stream = out_container.add_stream('pcm_s16le')

    for _ in range(100):
        frame = av.AudioFrame(samples=1152)
        frame.pts = None
        frame.rate = 48000
        for packet in out_stream.encode(frame):
            out_container.mux(packet)

    for packet in out_stream.encode(None):
        out_container.mux(packet)
```

**Comment by magicgoose** [comment]
This isn't helpful at all. I'm pretty sure that the silence is created only for simplicity purpose and the actual goal is to be able to use it with some real audio data.
The answer, while technically true, doesn't help to figure out the cause of the issues with numpy usage.

**Comment by chugunovyar** [comment]
Hello everyone, I also faced this problem. Did someone manage to fill in the data array correctly with real sound? share your experience please.

**Comment by Jackiexiao** [comment]
frame = av.AudioFrame.from_ndarray(audio_chunk, layout='mono', format='s16p')
            frame.sample_rate = ori_sr
