### ISSUE TITLE
Color values and dimensions read from frame are wrong?

### ISSUE THREAD

**Issue by slhck** [mikeboers/PyAV#525]
I am generating two videos, one all white, one all black, using libx264 with a yuv420 pixel format:

```
ffmpeg -f lavfi -i color=color=black:d=1:s=32x32 black.mp4
ffmpeg -f lavfi -i color=color=white:d=1:s=32x32 white.mp4
```

I want to read the pixel values from the luma plane only. So I do:

```python
#!/usr/bin/env python3
import numpy as np
import av
import sys

input_file = sys.argv[1]
container = av.open(input_file)
for packet in container.demux():
    for frame in packet.decode():
        if isinstance(frame, av.video.frame.VideoFrame):
            frame_data_raw = np.frombuffer(frame.planes[0], np.uint8)
            print(np.mean(frame_data_raw))
            sys.exit(1)
```

This is what I get:

```
➜ ./test_av.py black.mp4
4.0
➜ ./test_av.py white.mp4
58.75
```

Surely, this cannot be right. I would expect the average value for the black video to be 0, and the average value for the white video to be 255.

When I inspect the data returned, I see:

```
> np.shape(frame_data_raw)
(4096,)
```

But the video is 32⨉32, so that should be 1024. In fact, there are some values as 0, and some as 16, as if there was extra data in the plane. What am I doing wrong here?

NB, with scikit-video, I am getting the correct results:

```python
import numpy as np
import skvideo.io
import sys
for frame in skvideo.io.vreader(sys.argv[1], as_grey=True):
    width = frame.shape[-2]
    height = frame.shape[-3]
    frame_data_raw = frame.reshape((height, width))
    print(np.mean(frame_data_raw))
```

This gives `0.0` and `255.0`, as expected.

**Comment by jlaine** [comment]
You are comparing apples and pears here :)

Your PyAV-based code prints the mean luminance (Y component of the YUV frame) and `skvideo` based code prints the value of a grayscale frame. If you modify your first code to first convert the frame to grayscale you'll get the same results. Add:

```python
frame = frame.reformat(format='gray')
```

Also note there is a helper to convert frames to numpy arrays: `VideoFrame.to_ndarray`, which will help you handle tricky cases such as padding on video frames.

**Comment by slhck** [comment]
Thanks for the pointers! I wasn't aware of all these helper functions, perhaps since I couldn't find any examples online back when I wrote the initial code.

scikit-video documentation states that if `as_grey=True` is set, it "only load(s) the luminance channel of the input video." So I was expecting *both* code fragments to print the mean luminance channel value, ignoring chrominance components. In a completely white or black video, the average value of the luminance plane should be 255 and 0, respectively, no?

What other values am I seeing then in `frame.planes[0]`?

**Comment by slhck** [comment]
I can confirm I'm getting the same results now, thanks! Still curious about what apples (or pears) I was measuring though…

**Comment by jlaine** [comment]
I'm pretty sure you were bitten by a combination of two factors:

- comparing YUV vs grayscale

I'm not an expert on colourspaces, so I'd recommend looking at some more authoritative sources for this.

- using `np.frombuffer(frame.planes[0], np.uint8)`

Beware : this does not return the *useful* part of the frame's buffer, but the *whole* buffer, which may include padding for performance reasons.

**Comment by slhck** [comment]
> comparing YUV vs grayscale

No, using the Y component is the same as "grayscale". The FFmpeg pixel format `gray` is, in fact, [just the Y component](http://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavutil/pixfmt.h;hb=HEAD). I just didn't understand the need for converting using the `.format()` method, since just taking the Y values as-is would (should) have given the same results.

The padding seems to be the real issue then. Thanks for your help!

**Comment by jlaine** [comment]
Ok, thanks for correcting me I've learned something here!

**Comment by slhck** [comment]
I had to revisit this and change my answer above. It seems that you were right and comparing Y from YUV is not the same as first converting YUV to gray.
