### ISSUE TITLE
to_ndarray() changes shape of frame by appending 128's

### ISSUE THREAD

**Issue by MaximilianHoffmann** [mikeboers/PyAV#530]
Like this:

```
print(frame.height)  
print(frame.width)  
print(frame.to_ndarray().shape)  
print(frame.to_ndarray(width=frame.width,height=frame.height).shape)  
```
Out:
>2500
>2500
>(3750, 2500)
>(3750, 2500)

The values form 2501 to 3750 are filled with 128's 

Is there an easy explanation?

**Comment by ArtanisCV** [comment]
The most common pixel format for x264 is yuv420p. Thus, a 2500x2500 frame is composed of three channels:
1. Y channel, size 2500x2500;
2. U channel, size 1250x1250;
3. V channel, size 1250x1250.

When you invoke to_ndarray(), the returned result is a plane consisting of the aforementioned channels, and thus has 3750x2500 pixels.

If you need an RGB image, you can try something like frame.to_ndarray(format="rgb24").

**Comment by MaximilianHoffmann** [comment]
Thanks!
