### ISSUE TITLE
`pts` starts at zero after seek

### ISSUE THREAD

**Issue by MaximilianHoffmann** [mikeboers/PyAV#538]
If I use the container seek function the pts's are, as I see it, starting from zero afterwards. How can I get the timepoint to which I was seeking (when using frame number and any_frame=False)?

Thanks!

**Comment by mikeboers** [comment]
Hi @MaximilianHoffmann.

There are 2 things I could see going on here:

1. The specific format/codec/file that is causing `pts` to come out wrong. Please give it a try with other formats/codecs and see what happens.

2. The specific format/codec/file does not support seeking by frame number. IIRC most don't. Please check what frame you're getting back after the seek where `pts == 0`; my guess is it is the first frame.

**Comment by MaximilianHoffmann** [comment]
Thanks for answering. It was indeed the first frame...so the seek  via frame number just silently failed.
