### ISSUE TITLE
Regression: decoding webm audio inserts spurious bytes in recent versions of pyav

### ISSUE THREAD

**Issue by davidavdav** [mikeboers/PyAV#539]
Hello, 

In pyav version 0.3.3 (I realize this is old), linked against debian-8 libav libraries (libavcodec56, libavformat56, I realize this is really, really old) we can correctly decode/resample webm audio (as it is sent by chrome and firefox), using the boilerplate code 
```python
#!/usr/bin/env python

import av
import logging

logger = logging.getLogger(__name__)

def use_packet():
    container = av.open("in.webm", format="webm")
    resampler = av.AudioResampler(
        format=av.AudioFormat("s16p").packed,
        layout=int(1),
        rate=16000,
    )
    out = open("out.raw", "wb")
    audio = container.streams[0]
    for packet in container.demux(audio):
        logger.debug("packet %r", packet)
        if not packet:
            break
        try:
            for frame in packet.decode():
                frame.pts = None
                frame = resampler.resample(frame)
                logger.debug("frame %r", frame)
                for i, plane in enumerate(frame.planes):
                    logger.debug("plane %d %r", i, plane)
                    bytes = plane.to_bytes()
                    out.write(bytes)
        except Exception as e:
            print('Error', e, 'data', packet)
    out.close()

if __name__ == "__main__":
    use_packet()
```
However, in a more recent environment (pyav 6.2.0, ffmpeg 3.2, with libavcodec.so.57 libavformat.so.57) the decoded output contains blocks of spurious bytes, audible as regular loud clicks.  The output also does not seem to reproduce from one invocation to another.

The correct output file size is 94700 bytes, the incorrect output files size is 96032 bytes. 

Decoding using the same ffmpeg 3.2 command line tools `ffmpeg -i in.webm -ar 16000 out.wav` works fine.  

It is possible that the above boilerplate code is incorrect, specifically, I had to add the line `frame.pts = None` for the more recent pyav version, but I don't know if that is appropriate here. 

I've attached a zip that contains the `in.webm` file (github doesn't accept all file types).  

[in.zip](https://github.com/mikeboers/PyAV/files/3392118/in.zip)

**Comment by davidavdav** [comment]
I've done some more analysis:

If I look at the difference in output between two successive runs in the code above, with the same input `in.webm`, I get stretches of 6 samples that can be different, roughly every 650--660 samples (it varies a bit).  

And also: 

If I leave out the`rate=16000` option in `av.AudioResampler`, the problem disappears (but I am left with the wrong sample rate...)  Still, `ffmpeg` can do the resampling correctly.

Further debugging revealed: 
 - most packets contain 320 samples (640 bytes)
 - most `plane.to_bytes()`, however, are of length 652 bytes, so this is likely to contain the spurious 6 samples.  

So now I can fix this problem by changing the `write` statement to
```python
                    out.write(bytes[0:(frame.samples*2)])
```
This fixes the problem for me, but I still think there is some error in `AudioPlane.to_bytes()`.

**Comment by mikeboers** [comment]
This is exactly the same as #572. Lets keep talking there!
