### ISSUE TITLE
how can i install av for support hardware acceleration

### ISSUE THREAD

**Issue by junedgar** [mikeboers/PyAV#547]
Which branch do i need to install?
Do you have some document to describe it?
I followed [nvidia instruction](https://developer.nvidia.com/FFmpeg) to install ffmpeg(4.1), and tested the decode used the cuda successfully.
Then I install av from   rvillalba-novetta:hwaccel branch. 
But when i create 'h264_cuvid' demux, like blew:
> ctx = av.Codec('h264_cuvid', 'r').create()

I got error:
> File "av/codec/codec.pyx", line 67, in av.codec.codec.Codec.__cinit__
    self._init(name)
>  File "av/codec/codec.pyx", line 76, in av.codec.codec.Codec._init
    raise UnknownCodecError(name) av.codec.codec.UnknownCodecError: h264_cuvid

**Comment by jlaine** [comment]
Currently support for hardware acceleration has not been merged, I suggest you contact the author of the branch.
