### ISSUE TITLE
Error import av

### ISSUE THREAD

**Issue by thekhieu** [mikeboers/PyAV#548]
> [root@98271f8a30ce data]# python3.6 -c "import av"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/av/__init__.py", line 9, in <module>
    from av._core import time_base, pyav_version as __version__
ImportError: /lib64/libavcodec.so.57: undefined symbol:opus_multistream_surround_encoder_create

how to slove it?
i use ffmpeg 3.2.4, av 6.2

**Comment by jlaine** [comment]
There seems to be an issue with your ffmpeg, try compiling ffmpeg from source.
