### ISSUE TITLE
Using PyAV with a video preloaded into a buffer.

### ISSUE THREAD

**Issue by Nomad145** [mikeboers/PyAV#55]
Greetings,

Not an issue, but I'm curious if you might know an easy way to use PyAV with a buffer instead of directly from a file.  I've looked through the wiki and through a lot of the source code, but I haven't found anything of use.  Basically, I have a UDP video transport protocol that I pull in with Python where I sort the network frames and append them to a variable.  Once they reach a certain number of network frames, I dump them to an ffmpeg pipe to get encoded.  What I would really like to do is pass the variable to PyAV and have it do work on the video.  I've read some things on the LibAV/ffmpeg mailing lists and I know that it's relatively simple with libav, but I'm sure its not easily ported to PyAV (at least not for me).  I wondered if perhaps you had any ideas.  Any and all help is appreciated.

I would also be willing to assist in implementing such a feature, but I'm not anywhere near experienced enough with Cython to do it on my own.

**Comment by easuncion** [comment]
Is there a sample code related to this enhancement? Encountered the stream (VideoStream)'s format set to None & packet.decode() is failing. Any help is greatly appreciated. Thanks in advance.

**Comment by GoelBiju** [comment]
I am not sure if I am contributing to this or not but solving this might just find a solution for  #155 partially as we could feed potential data though and decode it.

**Comment by doender** [comment]
I would be interested in this as well

**Comment by mikeboers** [comment]
I'll re-open this to flag as documentation.
