### ISSUE TITLE
Can`t get access to webcam`s microphone audio stream.

### ISSUE THREAD

**Issue by Glunky** [mikeboers/PyAV#556]
Im sorry if question might be seems simple but i didnt find answer to it and i dont know what to do.
Im trying getting an audio stream from my webcams microphone. For example function `open("file.mp4")` returns video and audio streams, `open("file.wav")` returns audio stream. And string `open("/dev/video0")` returns only video stream. It is logical but is there any way to get audio stream from webcam? thanks for your help and understanding)

**Comment by mikeboers** [comment]
I don't have any experience with this. Maybe something like <https://askubuntu.com/a/986189>?

Seems like you'll have to open the audio/video separately. I don't know what the deal will be with syncing them.

I'm going to close this as it isn't a PyAV issue. Feel free to keep posting here if you want and I can try to help, or you can go over to the Gitter for a different audience.

**Comment by Glunky** [comment]
Just i found [this issue](https://github.com/mikeboers/PyAV/issues/182) and thought that it is possible, because first part of code working, as he said. But i tried to replace "none:0" to my microphone address and it doesnt work for me.
