### ISSUE TITLE
Release v7.0.0

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#571]
I'm on the verge of cutting off v7.0.0.

The questionable things remaining to me are:

- Should I remove the ability to disable the logging system? That whole thing turned out to be folly. Or at least it is for now; maybe in the future Cython will let us do that.
- Quickly rushing in a few other merges... but I think I don't care about hitting 7.1 even the same day. 😛

**Comment by NullYing** [comment]
I test in the same code, v7.0.0 more slowly than v6.2.0, I don't kown why?
