### ISSUE TITLE
Is FFmpeg HLS Segmenting start time available through PyAV?

### ISSUE THREAD

**Issue by farleylai** [mikeboers/PyAV#575]
When streaming over HLS, the absolute `EXT-X-PROGRAM-DATE-TIME` information is essential for real-time applications. However, I cannot find this information after `av.open(hls_url)`. The `start_time` is set to 0. Is this HLS Segmenting start time available through PyAV?

## Research

`ffmpeg` seems to recognizes this tag as follows:

```
‘program_date_time’
Generate EXT-X-PROGRAM-DATE-TIME tags.
```

**Comment by mikeboers** [comment]
As far as I can tell from grepping through the FFmpeg source, they don't expose arbitrary tags, so PyAV can't.

Maybe you can download the `m3u8` and parse it yourself?
