### ISSUE TITLE
Python3 install

### ISSUE THREAD

**Issue by Hashlime** [mikeboers/PyAV#58]
I tried to install with python3.4 on debian (testing) but the setup failed to detect the libraries 
I think the problem comes from the line 39 in setup.py:

    for chunk in str(raw_config).strip().split():

the type of raw_config is _bytes_ and str(raw_config) doesn't return the same thing with python3 or python2

Python 2

    str(b'test') # Ouput : "test"

Python 3

    str(b'test') # Output : "b'test'"

I fixed this by replacing the line 39 with 

    for chunk in raw_config.decode().strip().split():

**Comment by malc0** [comment]
I can confirm this issue.  Changing line 39 to `for chunk in raw_config.decode('utf-8').strip().split():` works for me.

**Comment by mikeboers** [comment]
Done. Sorry to take so long on this one. =S
