### ISSUE TITLE
how to get directshow device

### ISSUE THREAD

**Issue by gemark** [mikeboers/PyAV#594]
in cli, i can use 'ffmpeg -list_devices true -f dshow -i dummy' command

but in pyav, what should i do?  i want  get video/audio pin name

```python
av.open(format='dshow', file='dummy' options={'list_devices':'true'})
```
cant work...

i dont want use  subproess  run ffmpeg cmd...

**Comment by jlaine** [comment]
`av.open` is only for actually opening files / devices. There is currently no method for retrieving available devices using PyAV.

FYI this would require using `avdevice_list_input_sources`, feel free to submit a PR.

**Comment by gemark** [comment]
thx
