### ISSUE TITLE
Performance of the frame conversion to PIL.Image

### ISSUE THREAD

**Issue by Edelbert** [mikeboers/PyAV#598]
Hello! I found out the difference in the performance of different ways of frame conversion to PIL image. For example, I want to convert frame to PIL image and I can do it like this:
```        
for packet in cap.demux(video_stream):
            for frame in packet.decode():
                img = frame.to_rgb().to_ndarray()
                img = Image.fromarray(img)
```
Another way is to use to_image function:
```        
for packet in cap.demux(video_stream):
            for frame in packet.decode():
                img = frame.to_image()
```
I tried to extract 300 frames from video and the first script took ~1.25s, while the second took ~1.80s. Am I missing something? 
I have:
```
 av 7.0.0.dev0 version (build from commit 90e334f)
ffmpeg version n4.2
numpy                         1.18.1
Pillow                        7.0.0
```

**Comment by jlaine** [comment]
You seem to have found which code path is best for your usage, great! I'm going to close this issue as I don't see what's expected from the PyAV maintainers.
