### ISSUE TITLE
to_ndarray gives array of correct shape but filled only with 0's for a rgb format frame after covration using to_rgb()

### ISSUE THREAD

**Issue by PHDPeter** [mikeboers/PyAV#602]
So I have made some sample code that shows the problem (see below).
it is taken from the cython code given here (it is just easier to debug).
You will need to load av and numpy as well as change the video_path variable to any random video you have to hand (I have tried it with a few videos).
Otherwise running the code should give you "b" array with is a fine "yuv420" format of the first frame and "a" witch, if you get the same error as me, should be an "rgb" format of the same frame but ends up giving an array of the correct shape but filled only with 0's

I have tried this code on different machines and with different videos.
As far as I can see it is likely an issue with the np.frombuffer() or more particle the plane that is given to it.
I am using numpy ==1.18.1 but I have tried it with a few versions and it is the same thing making me think it is the VideoPlane give to it.
I was thinking it might be the to_rgb method but I tested that and found that the image was fine after the format change.

`def useful_array(plane,bytes_per_pixel=1,rgb=None):
    """
    Return the useful part of the VideoPlane as a single dimensional array.
    We are simply discarding any padding which was added for alignment.
    """
    import numpy as np
    total_line_size = abs(plane.line_size)
    useful_line_size = plane.width * bytes_per_pixel
    #if rgb==None:
    arr = np.frombuffer(plane, dtype=np.uint8)
    #else:
    #    arr = np.frombuffer('RGB',plane, dtype=np.uint8)
    if total_line_size != useful_line_size:
        arr = arr.reshape(-1, total_line_size)[:, 0:useful_line_size].reshape(-1)
    return arr

`def to_ndarray_try(frame):
    """Get a numpy array of this frame.
    Any ``**kwargs`` are passed to :meth:`.VideoReformatter.reformat`.
    .. note:: Numpy must be installed.
    """
    #cdef
    #VideoFrame
    #frame = self.reformat(**kwargs)

    import numpy as np

    if frame.format.name == 'yuv420p':
        assert frame.width % 2 == 0
        assert frame.height % 2 == 0
        return np.hstack((
            useful_array(frame.planes[0]),
            useful_array(frame.planes[1]),
            useful_array(frame.planes[2])
        )).reshape(-1, frame.width)
    elif frame.format.name == 'yuyv422':
        assert frame.width % 2 == 0
        assert frame.height % 2 == 0
        return useful_array(frame.planes[0], 2).reshape(frame.height, frame.width, -1)
    elif frame.format.name in ('rgb24', 'bgr24'):
        return useful_array(frame.planes[0], 3).reshape(frame.height, frame.width, -1)
    elif frame.format.name in ('argb', 'rgba', 'abgr', 'bgra'):
        return useful_array(frame.planes[0], 4).reshape(frame.height, frame.width, -1)
    elif frame.format.name in ('gray', 'gray8'):
        return useful_array(frame.planes[0]).reshape(frame.height, frame.width)
    else:
        raise ValueError('Conversion to numpy array with format `%s` is not yet supported' % frame.format.name)`

`def test_main():
    import av
    video_path = '/home/tim/Downloads/Shooting054_x264.mp4' #'/media/peter/Maxtor/UCF_Crimes/Videos/Vandalism/Vandalism048_x264.mp4'
    container = av.open(video_path,metadata_errors='ignore')
    frames_y = []
    frames_r = []
    for frame in container.decode(**{'video': 0}):
        frame_rgb = frame.to_rgb()
        frames_r.append(frame_rgb)
        frames_y.append(frame)

    b_p=frames_y[0].planes
    a_p=frames_r[0].planes

    print(type(b_p))
    print(type(a_p))

    b = to_ndarray_try(frames_y[0])
    a = to_ndarray_try(frames_r[0])
    print("worked")

if __name__ == "__main__":
    test_main()`

## Versions

- OS ubuntu 18.0.4
- ffmpeg - 4.0.1
 numpy ==1.18.1
```
PyAV v6.2.0
git origin: git@github.com:mikeboers/PyAV
git commit: unknown-commit
library configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
library license: GPL version 2 or later
libavcodec     57.107.100
libavdevice    57. 10.100
libavfilter     6.107.100
libavformat    57. 83.100
libavutil      55. 78.100
libswresample   2.  9.100
libswscale      4.  8.100

**Comment by tcdalton** [comment]
Why not use `image = frame.to_ndarray(format='rgb24')` to get your color ndarray?

**Comment by jlaine** [comment]
I fail to understand the bug description: you state there is an issue with `to_ndarray`, can we please have some code which backs up this claim?
