### ISSUE TITLE
I can't install pyAv on raspbian stretch 

### ISSUE THREAD

**Issue by GiannisDorokidis** [mikeboers/PyAV#603]
I am Using av for a Project called mpradio-py
I talked with the developer of the Project and he led me to your github Page 
here is the installation process
https://pastebin.com/xMTDcagw

**Comment by GiannisDorokidis** [comment]
Then this https://pastebin.com/nNBu5Yr1

**Comment by mikeboers** [comment]
There is a issue template named "build bug report". Normally, I would close this and request you use it, but since this is so close to the release of v7.0.0 (this morning) I will ask one question:

What version of FFmpeg do you have?

**Comment by guyver2** [comment]
we're having probably the same issue. I made a full report here https://github.com/mikeboers/PyAV/issues/604

**Comment by GiannisDorokidis** [comment]
https://pastebin.com/rCi5Z9Bn

**Comment by mikeboers** [comment]
PyAV v7 no longer supports FFmpeg v3. You'll have to stick with PyAV v6 or upgrade your FFmpeg.

Good luck!
