### ISSUE TITLE
not able to install the library !

### ISSUE THREAD

**Issue by sushansapaliga** [mikeboers/PyAV#606]
## Overview
was trying to install the library but im getting this error.
pip install av

## Expected behavior

Collecting av
  Using cached av-7.0.0.tar.gz (2.3 MB)
Installing collected packages: av
    Running setup.py install for av ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Sushan Sapaliga\\AppData\\Local\\Temp\\pip-install-rsudmj0y\\av\\setup.py'"'"'; __file__='"'"'C:\\Users\\Sushan Sapaliga\\AppData\\Local\\Temp\\pip-install-rsudmj0y\\av\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Sushan Sapaliga\AppData\Local\Temp\pip-record-_s5tlw6t\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\python38\Include\av'
         cwd: C:\Users\Sushan Sapaliga\AppData\Local\Temp\pip-install-rsudmj0y\av\
    Complete output (38 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\av
    copying av\datasets.py -> build\lib.win-amd64-3.8\av
    copying av\deprecation.py -> build\lib.win-amd64-3.8\av
    copying av\__init__.py -> build\lib.win-amd64-3.8\av
    copying av\__main__.py -> build\lib.win-amd64-3.8\av
    creating build\lib.win-amd64-3.8\av\audio
    copying av\audio\__init__.py -> build\lib.win-amd64-3.8\av\audio
    creating build\lib.win-amd64-3.8\av\codec
    copying av\codec\__init__.py -> build\lib.win-amd64-3.8\av\codec
    creating build\lib.win-amd64-3.8\av\container
    copying av\container\__init__.py -> build\lib.win-amd64-3.8\av\container
    creating build\lib.win-amd64-3.8\av\data
    copying av\data\__init__.py -> build\lib.win-amd64-3.8\av\data
    creating build\lib.win-amd64-3.8\av\filter
    copying av\filter\__init__.py -> build\lib.win-amd64-3.8\av\filter
    creating build\lib.win-amd64-3.8\av\sidedata
    copying av\sidedata\__init__.py -> build\lib.win-amd64-3.8\av\sidedata
    creating build\lib.win-amd64-3.8\av\subtitles
    copying av\subtitles\__init__.py -> build\lib.win-amd64-3.8\av\subtitles
    creating build\lib.win-amd64-3.8\av\video
    copying av\video\__init__.py -> build\lib.win-amd64-3.8\av\video
    running build_ext
    running config
    writing build\temp.win-amd64-3.8\Release\include\pyav\config.h
    running cythonize
    building 'av.buffer' extension
    creating build\temp.win-amd64-3.8\Release\src
    creating build\temp.win-amd64-3.8\Release\src\av
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude -Ic:\python\python38\include -Ibuild\temp.win-amd64-3.8\Release\include -Ic:\python\python38\include -Ic:\python\python38\include -Ibuild\temp.win-amd64-3.8\Release\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc\av\buffer.c /Fobuild\temp.win-amd64-3.8\Release\src\av\buffer.obj
    buffer.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\python\python38\libs /LIBPATH:c:\python\python38\PCbuild\amd64 /LIBPATH:c:\python\python38\libs /LIBPATH:c:\python\python38\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft
Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" avutil.lib avcodec.lib avfilter.lib avformat.lib swresample.lib avdevice.lib swscale.lib /EXPORT:PyInit_buffer build\temp.win-amd64-3.8\Release\src\av\buffer.obj /OUT:build\lib.win-amd64-3.8\av\buffer.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\src\av\buffer.cp38-win_amd64.lib /OPT:NOREF
    LINK : fatal error LNK1181: cannot open input file 'avutil.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Sushan Sapaliga\\AppData\\Local\\Temp\\pip-install-rsudmj0y\\av\\setup.py'"'"'; __file__='"'"'C:\\Users\\Sushan Sapaliga\\AppData\\Local\\Temp\\pip-install-rsudmj0y\\av\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Sushan Sapaliga\AppData\Local\Temp\pip-record-_s5tlw6t\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\python38\Include\av' Check the logs for full command output.

**Comment by mikeboers** [comment]
I'm sorry to say I don't have Windows build experience, and there isn't an obvious error in there for me. Hopefully someone else has ideas.

**Comment by FlowBYRN** [comment]
Got the same Problem :/

**Comment by iscsrl** [comment]
Same problem on Linux 18.4 .
It is broken since version 7.0.0
Installing with "pip3 install av==6.2.0" worked for me.

**Comment by iscsrl** [comment]
My error was:

```
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-sz1dte73/av/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-knt6xduz-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-sz1dte73/av/

```

**Comment by dalisoft** [comment]
@iscsrl If there was possible thank you BILLION times, i like to do that. You saved my week

**Comment by jlaine** [comment]
As of PyAV 8.0.0, binary wheels are provided which will greatly simplify installation and should solve your issue.
