### ISSUE TITLE
An exception occured during compiling

### ISSUE THREAD

**Issue by DaQirui** [mikeboers/PyAV#608]
**Environment:**

Windows10 x64

Python 3.5.0

The versions of pip and setuptools are the latest.

FFmpeg-4.0-x64 shared and dev ("\bin" has already insert into PATH)

All libraries in requirements.txt were installed. 

**Installation:**

Library: av-7.0.0 (Other versions also tried)

**Tried Method:**

1. PyPI

`pip install av==7.0.0`

2. setuptools

`python setup.py build --ffmpeg-dir=D:\ffmpeg`

**Exception Occured:**

Two method returned the same error.

```
...（leave out）
running cythonize
building 'av.buffer' extension
error: [WinError 2] The system cannot find the file or directory specified.
```

**Comment by jlaine** [comment]
As of PyAV 8.0.0, binary wheels are provided which will greatly simplify installation and should solve your issue.
