### ISSUE TITLE
FOO does not build.

### ISSUE THREAD

**Issue by vdmrweh** [mikeboers/PyAV#612]
<snip>

**Comment by vdmrweh** [comment]
Running setup.py install for av ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0kohx1yi/av/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0kohx1yi/av/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l8wzivsu/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/av
         cwd: /tmp/pip-install-0kohx1yi/av/
    Complete output (134 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/av
    copying av/deprecation.py -> build/lib.linux-x86_64-3.6/av
    copying av/__main__.py -> build/lib.linux-x86_64-3.6/av
    copying av/datasets.py -> build/lib.linux-x86_64-3.6/av
    copying av/__init__.py -> build/lib.linux-x86_64-3.6/av
    creating build/lib.linux-x86_64-3.6/av/codec
    copying av/codec/__init__.py -> build/lib.linux-x86_64-3.6/av/codec
    creating build/lib.linux-x86_64-3.6/av/audio
    copying av/audio/__init__.py -> build/lib.linux-x86_64-3.6/av/audio
    creating build/lib.linux-x86_64-3.6/av/subtitles
    copying av/subtitles/__init__.py -> build/lib.linux-x86_64-3.6/av/subtitles
    creating build/lib.linux-x86_64-3.6/av/container
    copying av/container/__init__.py -> build/lib.linux-x86_64-3.6/av/container
    creating build/lib.linux-x86_64-3.6/av/video
    copying av/video/__init__.py -> build/lib.linux-x86_64-3.6/av/video
    creating build/lib.linux-x86_64-3.6/av/data
    copying av/data/__init__.py -> build/lib.linux-x86_64-3.6/av/data
    creating build/lib.linux-x86_64-3.6/av/sidedata
    copying av/sidedata/__init__.py -> build/lib.linux-x86_64-3.6/av/sidedata
    creating build/lib.linux-x86_64-3.6/av/filter
    copying av/filter/__init__.py -> build/lib.linux-x86_64-3.6/av/filter
    running build_ext
    running config
    PyAV: 7.0.1 (unknown commit)
    Python: 3.6.9 (default, Nov  7 2019, 10:44:02) \n[GCC 8.3.0]
    platform: Linux-4.15.0-20-generic-x86_64-with-Ubuntu-18.04-bionic
    extension_extra:
        include_dirs: [b'include', b'/usr/include/x86_64-linux-gnu']
        libraries: [b'avformat', b'avcodec', b'avdevice', b'avutil', b'avfilter', b'swscale', b'swresample']
        library_dirs: []
        define_macros: []
        runtime_library_dirs: []
    config_macros:
        PYAV_COMMIT_STR="unknown-commit"
        PYAV_VERSION=7.0.1
        PYAV_VERSION_STR="7.0.1"
    writing build/temp.linux-x86_64-3.6/include/pyav/config.h
    running cythonize
    building 'av.logging' extension
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/src/av
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/logging.c -o build/temp.linux-x86_64-3.6/src/av/logging.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/logging.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/logging.cpython-36m-x86_64-linux-gnu.so
    building 'av.bytesource' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/bytesource.c -o build/temp.linux-x86_64-3.6/src/av/bytesource.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/bytesource.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/bytesource.cpython-36m-x86_64-linux-gnu.so
    building 'av.utils' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/utils.c -o build/temp.linux-x86_64-3.6/src/av/utils.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/utils.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/utils.cpython-36m-x86_64-linux-gnu.so
    building 'av.plane' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/plane.c -o build/temp.linux-x86_64-3.6/src/av/plane.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/plane.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/plane.cpython-36m-x86_64-linux-gnu.so
    building 'av.packet' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/packet.c -o build/temp.linux-x86_64-3.6/src/av/packet.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/packet.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/packet.cpython-36m-x86_64-linux-gnu.so
    building 'av._core' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/_core.c -o build/temp.linux-x86_64-3.6/src/av/_core.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/_core.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/_core.cpython-36m-x86_64-linux-gnu.so
    building 'av.stream' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/stream.c -o build/temp.linux-x86_64-3.6/src/av/stream.o
    src/av/stream.c: In function ‘__pyx_f_2av_6stream_wrap_stream’:
    src/av/stream.c:2279:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
       switch (__pyx_v_c_stream->codec->codec_type) {
       ^~~~~~
    In file included from /usr/include/x86_64-linux-gnu/libavdevice/avdevice.h:51:0,
                     from src/av/stream.c:671:
    /usr/include/x86_64-linux-gnu/libavformat/avformat.h:893:21: note: declared here
         AVCodecContext *codec;
                         ^~~~~
    src/av/stream.c: In function ‘__pyx_f_2av_6stream_6Stream__init’:
    src/av/stream.c:2889:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
       __pyx_t_1 = __pyx_v_stream->codec;
       ^~~~~~~~~
    In file included from /usr/include/x86_64-linux-gnu/libavdevice/avdevice.h:51:0,
                     from src/av/stream.c:671:
    /usr/include/x86_64-linux-gnu/libavformat/avformat.h:893:21: note: declared here
         AVCodecContext *codec;
                         ^~~~~
    src/av/stream.c:3012:15: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
         __pyx_t_7 = __pyx_v_self->_codec_context->codec;
                   ^
    src/av/stream.c: In function ‘__pyx_f_2av_6stream_6Stream__finalize_for_output’:
    src/av/stream.c:3698:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
       __pyx_t_8 = __pyx_f_2av_5error_err_check(avcodec_parameters_from_context(__pyx_v_self->_stream->codecpar, __pyx_v_self->_stream->codec), 0, NULL); if (unlikely(__pyx_t_8 == ((int)-1))) __PYX_ERR(0, 142, __pyx_L1_error)
       ^~~~~~~~~
    In file included from /usr/include/x86_64-linux-gnu/libavdevice/avdevice.h:51:0,
                     from src/av/stream.c:671:
    /usr/include/x86_64-linux-gnu/libavformat/avformat.h:893:21: note: declared here
         AVCodecContext *codec;
                         ^~~~~
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/stream.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/stream.cpython-36m-x86_64-linux-gnu.so
    building 'av.format' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/format.c -o build/temp.linux-x86_64-3.6/src/av/format.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/format.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/format.cpython-36m-x86_64-linux-gnu.so
    building 'av.error' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/error.c -o build/temp.linux-x86_64-3.6/src/av/error.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/error.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/error.cpython-36m-x86_64-linux-gnu.so
    building 'av.frame' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/frame.c -o build/temp.linux-x86_64-3.6/src/av/frame.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/frame.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/frame.cpython-36m-x86_64-linux-gnu.so
    building 'av.option' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/option.c -o build/temp.linux-x86_64-3.6/src/av/option.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/option.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/option.cpython-36m-x86_64-linux-gnu.so
    building 'av.dictionary' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/dictionary.c -o build/temp.linux-x86_64-3.6/src/av/dictionary.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/dictionary.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/dictionary.cpython-36m-x86_64-linux-gnu.so
    building 'av.descriptor' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/descriptor.c -o build/temp.linux-x86_64-3.6/src/av/descriptor.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/descriptor.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/descriptor.cpython-36m-x86_64-linux-gnu.so
    building 'av.buffer' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/buffer.c -o build/temp.linux-x86_64-3.6/src/av/buffer.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/buffer.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/buffer.cpython-36m-x86_64-linux-gnu.so
    building 'av.enum' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/enum.c -o build/temp.linux-x86_64-3.6/src/av/enum.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/av/enum.o -lswscale -lavcodec -lavformat -lswresample -lavfilter -lavdevice -lavutil -o build/lib.linux-x86_64-3.6/av/enum.cpython-36m-x86_64-linux-gnu.so
    building 'av.codec.codec' extension
    creating build/temp.linux-x86_64-3.6/src/av/codec
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -Iinclude -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/codec/codec.c -o build/temp.linux-x86_64-3.6/src/av/codec/codec.o
    src/av/codec/codec.c: In function ‘__pyx_pymod_exec_codec’:
    src/av/codec/codec.c:6061:36: error: ‘AV_CODEC_CAP_HARDWARE’ undeclared (first use in this function); did you mean ‘AV_CODEC_CAP_DR1’?
       __pyx_t_7 = __Pyx_PyInt_From_int(AV_CODEC_CAP_HARDWARE); if (unlikely(!__pyx_t_7)) __PYX_ERR(0, 124, __pyx_L1_error)
                                        ^~~~~~~~~~~~~~~~~~~~~
                                        AV_CODEC_CAP_DR1
    src/av/codec/codec.c:6061:36: note: each undeclared identifier is reported only once for each function it appears in
    src/av/codec/codec.c:6082:36: error: ‘AV_CODEC_CAP_HYBRID’ undeclared (first use in this function); did you mean ‘AV_CODEC_CAP_DR1’?
       __pyx_t_7 = __Pyx_PyInt_From_int(AV_CODEC_CAP_HYBRID); if (unlikely(!__pyx_t_7)) __PYX_ERR(0, 128, __pyx_L1_error)
                                        ^~~~~~~~~~~~~~~~~~~
                                        AV_CODEC_CAP_DR1
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0kohx1yi/av/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0kohx1yi/av/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l8wzivsu/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/av Check the logs for full command output.



SO if i do a pip3 install av, I get the above. 
I was able to install v 6.2 without any issue. I even followed the manual install on https://docs.mikeboers.com/pyav/develop/overview/installation.html (this worked) but then aiortc still tries to install av and pip3 install av still fails.

Could you please help. Running ubuntu 18.04 desktop

**Comment by mikeboers** [comment]
PyAV only supports FFmpeg >= 4.0
