### ISSUE TITLE
setuptools and cythonize

### ISSUE THREAD

**Issue by markreidvfx** [mikeboers/PyAV#62]
I've been using a older version of pyav for a while, any reason distutils was [changed][a] to setuptools? I couldn't seem to build pyav on my mavericks system the latest master a9cdab75794f7e18406734294e53a733193dc82f without reverting setup.py [back][c] to distutils. on my system the cythonize function isn't working correctly on setuptools Extensions objects, (setuptools is replacing all the sources .pyx extensions with .c). All the cythonize examples seem to use [distutils][b].

[a]: https://github.com/mikeboers/PyAV/commit/73b32cc048c1a190aff8c83fb3ec8cd3764ec0d2#diff-2eeaed663bd0d25b7e608891384b7298L2

[b]: http://docs.cython.org/src/reference/compilation.html#compiling-with-distutils

[c]: https://github.com/markreidvfx/PyAV/commit/7737ef6e9e7307c40f326e61cc9291047540bc49

**Comment by mikeboers** [comment]
@markreidvfx Can you tell me what version of setuptools you had at the time?
