### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by jonassmedegaard** [mikeboers/PyAV#621]
Newest release on PyPI is 7.0.1 whereas newest git tag is v6.2.0.

Tagging in git aids those (like me, for Debian) who wants to redistribute this project and want to keep track of not only the released tarball but also correlate that with git development.

Thanks for considering.

**Comment by mikeboers** [comment]
I do tag them, just forgot that I have to manually `git push --tags`. 😉 

Thanks for the reminder.
