### ISSUE TITLE
source contains images with embedded non-free ICC profile

### ISSUE THREAD

**Issue by jonassmedegaard** [mikeboers/PyAV#622]
Hi,

These two images contain an ICC profile owned by Hewlett Packard and not freely licensed:
docs/_static/favicon.png
docs/_static/logo-250.png

Please strip the ICC profile from those images, (if nothing else then) to ease redistribution.

Hint (because it has become an FAQ): A tool that can detect such layered metadata is command-line tool `exiftool`, on Debian-basd systems shipped in the package `libimage-exiftool-perl` and alternatively had with the command `cpanm Image::ExifTool`.

Thanks for considering.

**Comment by mikeboers** [comment]
Huh. Okay. I'm not entirely sure what I'm doing, so do the images in the above commit look good?

**Comment by jonassmedegaard** [comment]
Quoting Mike Boers (2020-04-15 21:49:12)
> Huh. Okay. I'm not entirely sure what I'm doing, so do the images in the above commit look good?

Yes, they are good. Thanks!

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by mikeboers** [comment]
Cool. I'll push that to develop in a minute.
