### ISSUE TITLE
How to Encode Wav Numpy Array to File

### ISSUE THREAD

**Issue by tigerite** [mikeboers/PyAV#64]
Hi Mike

If I have a wav audio data as an numpy array, how can I encode it to file? Say to MP3 or OGG?

**Comment by tigerite** [comment]
Hey Mike

Was this feature added yet?

If not, I'd like to contribute my implementation. What is the best way to send you the files?

**Comment by jlaine** [comment]
A tentative solution for this is available in #422

**Comment by jlaine** [comment]
I'm closing this issue as #422 introduced AudioFrame <-> ndarray converters for all supported formats.
