### ISSUE TITLE
Document features enabled in binary wheel

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#641]
It would be keen to be able to point to a list of what we have enabled in FFmpeg in the binary wheel.

**Comment by jlaine** [comment]
Hi Mike!

The Windows builds of FFmpeg have this configuration:

https://ffmpeg.zeranoe.com/builds/readme/win64/shared/ffmpeg-4.2.2-win64-shared-readme.txt

The Linux and Mac builds we generate ourselves, the current configuration is here:

https://github.com/jlaine/pyav-ffmpeg/blob/25f5e191fa6d45364372be0d8323c64c3f7f8001/scripts/build-ffmpeg#L159

**Comment by jlaine** [comment]
Ideally I'd like to align Linux and Mac on the Windows builds, that way we'll have a consistent feature set.

I'm currently working on getting AV1 support in our FFmpeg builds (with libaom and libdav1d).

**Comment by jlaine** [comment]
@mikeboers where were you thinking of putting the documentation for this?

**Comment by mikeboers** [comment]
Under a new section about the binary wheels [somewhere here](http://docs.mikeboers.com/pyav/develop/overview/about.html#bring-your-own-ffmpeg).
