### ISSUE TITLE
example on how to use AC3 audio?

### ISSUE THREAD

**Issue by paulskinau** [mikeboers/PyAV#71]
Is there an example on how to use AC3 audio? 

The AC3 audio codec is experimental in ffmpeg and pyav falls over with an appropriate error

For example:

output_audio_stream = output.add_stream("aac") 
returns:
av.AVError: [Errno 733130664] Experimental feature

**Comment by mikeboers** [comment]
This will be a fun one. On my machine, that codec is marked experimental, but my trivial tests don't seem to care (on "aac", "vorbis", or any of the others which do self-identify as experimental).

Can you tell us about your OS and FFmpeg/LibAV version?

**Comment by paulskinau** [comment]
Hi,

Its CentOS release 6.6 (Final)

ffmpeg is version 2.3.3
libavcodec.so.54   Version 1.2.6

**Comment by jlaine** [comment]
I'm going to close this issue, in the FFmpeg versions currently supported by PyAV, both `aac` and `ac3` streams seem to work fine.
