### ISSUE TITLE
Wrap H264 video stream in MP4 container

### ISSUE THREAD

**Issue by munnerz** [mikeboers/PyAV#72]
Hi

Sorry in advance that this is such a basic question:-

I have raw H264 data, stored in a python string object (or temporary file in memory) that I need to wrap in an MP4 container. I've looked at the remux example, however I specifically want to use the '-vcodec copy' flag, so no re-encoding is done.

How am I best to achieve this with PyAV? I'm currently calling FFmpeg through a subprocess, but want to switch to using your module

Thanks!

**Comment by mikeboers** [comment]
I'm sorry to say that this is something we are struggling on and off with already (see #47). Unfortunately the "copy" codec is a lot more complicated underneath than it seems, and we have yet to be able to get our heads around it.

**Comment by mikeboers** [comment]
This is close enough to #143 that we should consider it merged there.
