### ISSUE TITLE
Expose ability to set number of encode threads

### ISSUE THREAD

**Issue by malc0** [mikeboers/PyAV#73]
Being able to use more than one thread makes encoding much faster.  With the ffmpeg binary adding `-threads 2' to the command line uses two threads, for instance.

I have been able to get a similar speed-up by adding an `int thread_count` member to struct AVCodecContext in include/libavcodec/avcodec.pxd, and adding `codec_context.thread_count = 2` to add_stream in av/container.pyx.  Doubtless this would need to be exposed as a parameter when properly implemented.

**Comment by mikeboers** [comment]
I've added the property `Stream.thread_count`. This is the immediately obvious place to put it, but it feels a little strange to me conceptually, so I'm going to leave this issue open for now.

Cheers!
