### ISSUE TITLE
How to make VideoFrame.to_nd_array() return an ndarray of the correct shape and dtype?

### ISSUE THREAD

**Issue by ksze** [mikeboers/PyAV#77]
Again, working with my FFV1 16-bit grayscale videos, which have, of course, only one grayscale channel.

If I do this:

```
In [25]: container = av.open('/home/ksze/16-bit grayscale ffv1.avi')

In [26]: _break = False

In [27]: for p in container.demux():
    for f in p.decode():
        if isinstance(f, av.VideoFrame):
            frame = f
            _break = True
            break
    if _break:
        break
   ....:

In [28]: frame.to_nd_array()
Out[28]:
array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       ...,
       [[ 0,  0,  0],
        [16, 16, 16],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [11, 11, 11],
        [ 0,  0,  0]]], dtype=uint8)
```

Note that I now that an ndarray that represents _three_ channels and with the wrong dtype.

And then I tried to do this:

```
In [29]: frame.to_nd_array(colorspace='gray16le')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-4d71a13e89d1> in <module>()
----> 1 frame.to_nd_array(colorspace='gray16le')

/home/ksze/PyAV/av/video/frame.so in av.video.frame.VideoFrame.to_nd_array (src/av/video/frame.c:3515)()

ValueError: total size of new array must be unchanged

In [30]: frame.to_image()
Out[30]: <PIL.Image.Image image mode=RGB size=512x424 at 0x29C82D8>
```

_Update_
It would be nice to be able to pass a flag to `to_nd_array()` so it just returns an ndarray with the original components and original bit-depth, with no colorspace or bit-depth conversion at all, just like in the original image. I wouldn't even mind working directly with the `VideoPlane` buffer. However, somehow the buffer's length does not match width \* height \* bytes-per-pixel, so I really don't know how to work with it directly.

**Comment by mikeboers** [comment]
I think this is highly related to #76. Lets see if fixing that resolved this.

**Comment by mikeboers** [comment]
I'm not having trouble using the buffer directly with your 8-bit sample. Can you provide a 16-bit sample?

I agree with `to_nd_array` not doing a colorspace conversion unless you ask for it.

**Comment by ksze** [comment]
Here is a 16-bit sample: https://www.dropbox.com/s/lt5hgk4wd86whhy/2015-01-26%2014-06-38.depth.avi?dl=0

**Comment by ksze** [comment]
By the way, I think you mean `import numpy as np` here:
https://github.com/mikeboers/PyAV/blob/master/av/video/frame.pyx#L250

**Comment by mikeboers** [comment]
Hah! I really did.

You can tell which method needs a test. ;)

**Comment by mikeboers** [comment]
Okay; fixed, and minimally tested!

(I also needed to return something from the method.)

**Comment by mikeboers** [comment]
Tell me if the data is coming out right. Also if you think this should be shaped `(424, 512)` or `(424, 512, 1)` (it is currently the former, but I'm thinking the latter for consistency with other pixel formats).

**Comment by ksze** [comment]
I would say whichever shape Pillow and OpenCV work best with. =P

I think both Pillow and OpenCV can work with just `(424, 512)`.

**Comment by ksze** [comment]
And I now understand why I was getting plane buffers slightly larger than I expected. It's because of this: http://ffmpeg.org/doxygen/trunk/structAVFrame.html#aa52bfc6605f6a3059a0c3226cc0f6567

The frame data alignment optimization.

Which means I have to discard a few bytes at the end of each horizontal line in each plane.

**Comment by mikeboers** [comment]
Interesting. I wonder if we can use strides in the Python buffer to deal with that.

**Comment by ksze** [comment]
What I do right now is to just load the plane data into an ndarray, reshape and then slice off the last few columns.

**Comment by mikeboers** [comment]
So much has changed about this that I'm closing it until it is a problem again.
