### ISSUE TITLE
Create video from numpy array ?

### ISSUE THREAD

**Issue by hadim** [mikeboers/PyAV#79]
Is that possible with the current binding to create a video from numpy array or PIL.Image ?

**Comment by mikeboers** [comment]
Here is an example for encoding a video out of a series of stills -> https://github.com/mikeboers/PyAV/blob/master/examples/encode_frames.py

It uses OpenCV to read the images into series a numpy arrays.

Good luck!

**Comment by hadim** [comment]
Thank you very much sir !

**Comment by Atrin4000** [comment]
This link is not working. is there any other code for  converting numpy to video?

**Comment by mikeboers** [comment]
That file is at https://github.com/mikeboers/PyAV/blob/develop/scratchpad/encode_frames.py

**Comment by mohammadkhair7** [comment]
link to original file not working , please provide a new link for the file you have

**Comment by WyattBlue** [comment]
> https://github.com/mikeboers/PyAV/blob/master/examples/encode_frames.py

https://github.com/PyAV-Org/PyAV/blob/main/scratchpad/encode_frames.py

**Comment by WyattBlue** [comment]
> link to original file not working , please provide a new link for the file you have

https://github.com/hmaarrfk/PyAV/blob/develop/scratchpad/encode_frames.py

**Comment by mohammadkhair7** [comment]
Thank you very much for this source code! well done!.

Mohammad Khair
