### ISSUE TITLE
plane.to_bytes() pads data up to 128

### ISSUE THREAD

**Issue by svilendobrev** [mikeboers/PyAV#81]
i'm reading audio, and in one case of mp3 / that is s16p format, first chunk is about 47 frames (94 bytes) but gets padded up to 128 bytes. With all the consequences.
As workaround i'm cutting it back to what it should be with

``` python
for frame in packet.decode():
 channelsdata = [ 
    p.to_bytes() [: 2*frame.samples * (nchannels if nchannels > len(frame.planes) else 1) ]
    for p in frame.planes ]
```

hoping its really padded at the end and not something else.
but thats too cumbersome.

**Comment by mikeboers** [comment]
I suspect this is the same frame padding optimization brought up near the (current) end of #77.

We could automatically trim this, but just need to be sure we fully understand every layout before doing so.

**Comment by jlaine** [comment]
As far as I'm concerned this works as designed, if you're going to access a plane's raw buffer you need to deal with the subtleties of alignment. Alternatively you can use higher level APIs such as the ndarray converters.
