### ISSUE TITLE
av.open does not accept unicode name in Python 3

### ISSUE THREAD

**Issue by svilendobrev** [mikeboers/PyAV#82]
i've tried to build on python 3.4.
The setup.py needs fixing : raw_config inside library_config() needs decoding into unicode
i.e.

``` python
def library_config(name): 
    ..after getting raw_config..
            try: unicode    #py2 here
            except: #py3 here
                import sys
                raw_config = raw_config.decode( sys.stdout.encoding)
   ...
```

and that makes setup.py work. 

Then, trying, av.open expects a bytes filename but gets unicode, and cython cannot autoconvert if not ascii. If filename is ascii, then all works (well i'm only reading audio). But If not ascii. no deal..

**Comment by mikeboers** [comment]
Which revision are you using? I thought the decode part of this was address recently (in be03c9bd4c694dacf4d298a3ef2cceb811f4ab91).

**Comment by svilendobrev** [comment]
on decode: i used whatever comes from pip, and that is not latest although version.num is same. now u're doing direct raw_config.decode, regardless of python 2 or 3, which may break something? dunno. if it works ok, doesnt matter.

**Comment by mikeboers** [comment]
Ok. So I need to re-release the current master for the setup.py. The filename thing is another issue I need to look into.

**Comment by mozbugbox** [comment]
Patch to accept unicode filename in Python3: [py3-filename-encoding.txt](https://github.com/mikeboers/PyAV/files/342710/py3-filename-encoding.txt)

**Comment by andreymal** [comment]
Non-English-speaking users (like me) can't use PyAV while this issue is not fixed :(
