### ISSUE TITLE
Debian stable compatibility

### ISSUE THREAD

**Issue by Psycojoker** [mikeboers/PyAV#83]
Hello,

I don't know how this ticket qualify between a bug and a feedback message but I've had to install pyav in a virtualenv on a debian wheezy in the previous days. Here is the result:
- by default you don't have the good packages in debian stable
- so you have to use wheezy-backports and run this command: "sudo apt-get install -t wheezy-backports libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev" (the "-t wheezy-backports" is very important here).
- still, once you have your packages, the compilation of pyav in a virtualenv from pypi doesn't work, you end up with missing definitions in the C files (sorry I don't have the exact log anymore :()
- so you have to compile ffmpeg following those instructions that works perfectly https://mikeboers.github.io/PyAV/#ubuntu-12-04-lts

I don't know if you want:
- to add this information in the documentation (I can do a PR)
- fix pyav building process (I won't be able to that)

Kind regards and thanks for this great lib :)

PS: if you could add a favicon on the documentation website, whatever it is, really, that would be so awesome, I keep losing the tab during my working sessions

**Comment by mikeboers** [comment]
Unfortunately, fixing this is out of scope of PyAV by a wide margin (simply due to the convoluted history of FFMpeg vs Libav). So, I've labeled this "docs" to add it to that pile todo (whenever I unbury myself at work).

I've done the PS, at least (assuming your browser is ok with PNG favicons). :wink: https://mikeboers.github.io/PyAV/

**Comment by mikeboers** [comment]
Oh, and thank you very much for sticking through the build process, and sharing here. I really appreciate having the assistance.

**Comment by jlaine** [comment]
I'm closing this issue: the current PyAV does support the current Debian stable release.

For older Debian releases, the same instructions as for older Ubuntu releases apply.
