### ISSUE TITLE
No Image method to_string()

### ISSUE THREAD

**Issue by arantius** [mikeboers/PyAV#85]
In my version of Pillow:

    >>> from PIL import Image
    >>> img = Image.new('RGB', (10, 10))
    >>> img.to_string
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 605, in __getattr__
        raise AttributeError(name)
    AttributeError: to_string
    >>> img.tostring
    <bound method Image.tostring of <PIL.Image.Image image mode=RGB size=10x10 at 0x7FA23E68C3F8>>
    
This bit me when trying to `av.VideoFrame.from_image()`, which tries to call the version with the underscore.  I'm not sure of the details here, did PIL or Pillow decide to change this at some point?  Is it likely that users will have versions installed that only have one or only have the other?

**Comment by mikeboers** [comment]
Looks like it is a typo to me, and should be `tostring`. I pushed a fix to master. Cheers!
