### ISSUE TITLE
Automated build / test of OSX wheels for PyAV

### ISSUE THREAD

**Issue by matthew-brett** [mikeboers/PyAV#89]
I made a repo for automated building of standalone OSX wheels for PyAV:

https://github.com/MacPython/PyAV-wheels

Builds are listed here:

https://travis-ci.org/MacPython/PyAV-wheels

The built wheels currently go to http://wheels.scipy.org

Example install command:

```
pip install -f http://wheels.scipy.org av
```

Me installing into a virtualenv:

```
$ mkvirtualenv av-test
New python executable in av-test/bin/python
Installing setuptools, pip...done.
(av-test)$ pip install -f http://wheels.scipy.org av
Collecting av
  This repository located at wheels.scipy.org is not a trusted host, if this repository is available via HTTPS it is recommend to use HTTPS instead, otherwise you may silence this warning with '--trusted-host wheels.scipy.org'.
  DEPRECATION: Implicitly allowing locations which are not hosted at a secure origin is deprecated and will require the use of --trusted-host in the future.
  Downloading http://wheels.scipy.org/av-0.2.2-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (6.7MB)
    100% |████████████████████████████████| 6.7MB 1.3MB/s 
Installing collected packages: av
Successfully installed av-0.2.2
(av-test)$ python -c 'import av'
(av-test)$
```

I took the liberty of inviting you (@mikeboers) to the team owning that repo.

I still haven't wrinkled out all the tests yet, but I thought I would let you know.

**Comment by matthew-brett** [comment]
I think I've now set up the tests correctly, but some of them are failing:

https://travis-ci.org/MacPython/PyAV-wheels/jobs/61658435

```
======================================================================
FAIL: test_matroska (tests.test_containerformat.TestContainerFormats)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/MacPython/PyAV-wheels/tmp_for_test/tests/test_containerformat.py", line 13, in test_matroska
    self.assertEqual(fmt.extensions, set(('mkv', )))
AssertionError: Items in the first set but not the second:
'mks'
'mk3d'
'mka'
======================================================================
FAIL: test_container_probing (tests.test_file_probing.TestAudioProbe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/MacPython/PyAV-wheels/tmp_for_test/tests/test_file_probing.py", line 20, in test_container_probing
    self.assertEqual(self.file.bit_rate, 270494)
AssertionError: 269558 != 270494
-------------------- >> begin captured logging << --------------------
libav.mpegts: DEBUG: parser not found for codec none, packets or times may be invalid.
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: test_container_probing (tests.test_file_probing.TestVideoProbe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/MacPython/PyAV-wheels/tmp_for_test/tests/test_file_probing.py", line 50, in test_container_probing
    self.assertEqual(self.file.duration, long(1580000))
AssertionError: 1620000 != 1580000L
-------------------- >> begin captured logging << --------------------
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpegts: WARNING: PES packet size mismatch
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: test_stream_probing (tests.test_file_probing.TestVideoProbe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/MacPython/PyAV-wheels/tmp_for_test/tests/test_file_probing.py", line 79, in test_stream_probing
    self.assertEqual(stream.coded_width, 720)
AssertionError: 0 != 720
-------------------- >> begin captured logging << --------------------
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpeg2video: ERROR: Invalid frame dimensions 0x0.
libav.mpegts: WARNING: PES packet size mismatch
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: test_movtext (tests.test_subtitles.TestSubtitle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/MacPython/PyAV-wheels/tmp_for_test/tests/test_subtitles.py", line 24, in test_movtext
    self.assertEqual(subs[0][0].ass, 'Dialogue: 0,0:00:00.97,0:00:02.54,Default,- Test 1.\\N- Test 2.\r\n')
AssertionError: 'Dialogue: 0,0:00:00.97,0:00:02.54,Default,,0,0,0,,- Test 1.\\N- Test 2.\r\n' != 'Dialogue: 0,0:00:00.97,0:00:02.54,Default,- Test 1.\\N- Test 2.\r\n'
----------------------------------------------------------------------
Ran 38 tests in 6.202s
FAILED (failures=5)
```

**Comment by mikeboers** [comment]
I actually have some of the same types of failures on my workstation (I see `AssertionError: 0 != 720` every time). There are, apparently, some subtle changes in FFmpeg for OS X, or OS X, that has inspected values come out a little different.

I would love to squash them, but have not yet figured them out.

**Comment by mikeboers** [comment]
I think a few of those are also related to the specific version of FFmpeg being used. The change in ASS format being one.

(Testing the wrapper of a constantly changing library with two forks is not easy business. =P)

**Comment by matthew-brett** [comment]
Is there a better ffmeg version I should pin to?

**Comment by mikeboers** [comment]
The tricky part with that question is if PyAV versions should bind to specific FFMpeg/LibAV versions, or be as generally supportive as possible.

To answer the specific question, I don't think so. OS X has not been passing a few specific tests (on my machines) for a long time, because the issues are actually in the wrapped libraries (e.g. using ffprobe gives the same values).

**Comment by matthew-brett** [comment]
I can see that the tricky question is - tricky.

For the wheels specifically, you can build a particular version of the library (ffmpeg, libav), and the way the wheel is built, you can ship the built version safely inside the wheel. I can see it would be much more difficult in the general case - for example on Linux.

**Comment by danielballan** [comment]
@matthew-brett Can you make a separate FFmpeg wheel? I built separate conda packages for FFmpeg, x264, yasm (which is only a build dep, not a run dep) and PyAV.  I chose FFmpeg n2.2.4, but others could be built and swapped out.

**Comment by matthew-brett** [comment]
I don't know of any real thought that has gone into wheels for things that don't get installed into Python installation directories.

Wheels for the various Python packages that use hdf5, currently just ship their own copies of the hdf5 library.

What would the ffmpeg wheel be used for do you think?

**Comment by danielballan** [comment]
By having the FFmpeg wheel separate from the PyAV wheel, one could specify
a version of FFmpeg and a version of PyAV without building the outer
product of all possibilities into wheels.

**Comment by matthew-brett** [comment]
I see - I hadn't considered that case.   I guess that, most of the time, you want some PyAV version, compiled against the most recent compatible version of ffmpeg.

Maybe it would be reasonable to cover on that case for now, with wheels, leaving some small number of users to compile their own PyAV, if they need to.

**Comment by danielballan** [comment]
Sounds good.

**Comment by mikeboers** [comment]
Another issue is that PyAV does have slightly different code paths compiled into it depending on the library you are building it against.

FFMpeg vs LibAV are certainly not runtime compatible, and even the cutting edge stuff on FFMpeg has been providing some problems.

So... it might actually be "best" (especially for now) to provide a single wheel with the FFMpeg it is built against.

**Comment by danielballan** [comment]
I see. We can address this on the conda side by listing the dependency on
FFmpeg as being on a specific version.
