### ISSUE TITLE
Installation Problem (from PyPI)

### ISSUE THREAD

**Issue by w495** [mikeboers/PyAV#90]
# Install Av from  PyPI

~~~

[w495@w495yb ffmpeg-1.2.2]$ sudo pip install av 
Downloading/unpacking av
Running setup.py egg_info for package av
    
Installing collected packages: av
Running setup.py install for av
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    from cpython.buffer cimport PyObject_CheckBuffer, PyObject_GetBuffer, PyBUF_SIMPLE, PyBuffer_Release
    
    from fractions import Fraction
    
    cimport libav as lib
        ^
    ------------------------------------------------------------
    
    av/utils.pyx:7:8: 'libav.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            else:
                raise AVError(-res, c_buffer)
        return res
    
    
    cdef dict avdict_to_dict(lib.AVDictionary *input):
                            ^
    ------------------------------------------------------------
    
    av/utils.pyx:35:25: 'AVDictionary' is not a type identifier
    
    <snip lots of the same>

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-root/av/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4KCe0x-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip-build-root/av
Storing complete log in /root/.pip/pip.log
~~~

# About Environment 

## About System

    [w495@w495yb PyAV]$ uname -a
    Linux w495yb 3.14.27-100.fc19.x86_64 #1 SMP Wed Dec 17 19:36:34 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
    [w495@w495yb PyAV]$

## About FFmpeg

    [w495@w495yb ffmpeg-1.2.2]$ which ffmpeg
    /usr/local/bin/ffmpeg

    [w495@w495yb ffmpeg-1.2.2]$ ffmpeg -version
    ffmpeg version 1.2.2
    built on May 17 2015 00:00:54 with gcc 4.8.3 (GCC) 20140911 (Red Hat 4.8.3-7)
    configuration: --disable-static --enable-shared --disable-doc
    libavutil      52. 18.100 / 52. 18.100
    libavcodec     54. 92.100 / 54. 92.100
    libavformat    54. 63.104 / 54. 63.104
    libavdevice    54.  3.103 / 54.  3.103
    libavfilter     3. 42.103 /  3. 42.103
    libswscale      2.  2.100 /  2.  2.100
    libswresample   0. 17.102 /  0. 17.102

    [w495@w495yb ffmpeg-1.2.2]$ ls -1 /usr/local/lib/libav*
    /usr/local/lib/libavcodec.a
    /usr/local/lib/libavcodec.so
    /usr/local/lib/libavcodec.so.54
    /usr/local/lib/libavcodec.so.54.92.100
    /usr/local/lib/libavcodec.so.56
    /usr/local/lib/libavcodec.so.56.26.100
    /usr/local/lib/libavdevice.a
    /usr/local/lib/libavdevice.so
    /usr/local/lib/libavdevice.so.54
    /usr/local/lib/libavdevice.so.54.3.103
    /usr/local/lib/libavdevice.so.56
    /usr/local/lib/libavdevice.so.56.4.100
    /usr/local/lib/libavfilter.a
    /usr/local/lib/libavfilter.so
    /usr/local/lib/libavfilter.so.3
    /usr/local/lib/libavfilter.so.3.42.103
    /usr/local/lib/libavfilter.so.5
    /usr/local/lib/libavfilter.so.5.11.102
    /usr/local/lib/libavformat.a
    /usr/local/lib/libavformat.so
    /usr/local/lib/libavformat.so.54
    /usr/local/lib/libavformat.so.54.63.104
    /usr/local/lib/libavformat.so.56
    /usr/local/lib/libavformat.so.56.25.101
    /usr/local/lib/libavutil.a
    /usr/local/lib/libavutil.so
    /usr/local/lib/libavutil.so.52
    /usr/local/lib/libavutil.so.52.18.100
    /usr/local/lib/libavutil.so.54
    /usr/local/lib/libavutil.so.54.20.100

---

What I should do to install it?

**Comment by danielballan** [comment]
I recently packaged PyAV on 64-bit Linux for conda, so if you use the conda
package manager you could try, conda install -c danielballan pyav.

**Comment by w495** [comment]
Thanks a lot!

## av.audio.frame.AudioFrame.type()

But, I get that for «Basic Demo» example:

    [w495@w495yb av-test]$ python3.4 ./test-2.py
    Traceback (most recent call last):
    File "./test-2.py", line 27, in <module>
        if frame.type == 'video':
    AttributeError: 'av.audio.frame.AudioFrame' object has no attribute 'type'
    [w495@w495yb av-test]$ 

I guess that it should be:

    #!/usr/bin/env python3.4
    # -*- coding: utf-8 -*-

    import av
    from av.video.frame import VideoFrame
    container = av.open('/path/to/video.mp4')
    for packet in container.demux():
        for frame in packet.decode():
            if(type(frame) == VideoFrame):
                frame.to_image().save('frame-%04d.jpg' % frame.index)

Will you mention this variant for Basic Demo?

## Pillow

After that i get

    [w495@w495yb av-test]$ python3.4 ./test-2.py
    Traceback (most recent call last):
    File "./test-2.py", line 12, in <module>
        frame.to_image().save('frame-%04d.jpg' % frame.index)
    File "av/video/frame.pyx", line 236, in av.video.frame.VideoFrame.to_image (src/av/video/frame.c:3388)
    ImportError: No module named 'PIL'
    [w495@w495yb av-test]$

Of course, `sudo conda install pillow` solves it, but it'll be more convenient to install all with `pyav`.

Thanks a lot, one more time!

**Comment by w495** [comment]
I have one more question

**Comment by w495** [comment]
# A little out of the case 
Do you support ffmpeg-2.6? Or only ffmpeg-2.2? 
I've try to compile pyav from source for ffmpeg-2.6

    [w495@w495yb PyAV]$ python
    Python 2.7.5 (default, Nov  3 2014, 14:33:39) 
    [GCC 4.8.3 20140911 (Red Hat 4.8.3-7)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> 
    >>> import av
    >>> 
    >>> container = av.open('/home/w495/Video/15sec.nr.mp4')
    Segmentation fault
    [w495@w495yb PyAV]$

Dmesg said:

    [864731.031836] python[12046]: segfault at 100000019 ip 00007f8748df8607 sp 00007fff81a58338 error 4 in libavutil.so.54.20.100[7f8748de2000+4a000]

## About Video

    [w495@w495yb PyAV]$ ~/bin/ffprobe /home/w495/Video/15sec.nr.mp4
    ffprobe version 2.6 Copyright (c) 2007-2015 the FFmpeg developers
    built with gcc 4.8.3 (GCC) 20140911 (Red Hat 4.8.3-7)
    configuration: --disable-static --enable-shared --disable-doc --extra-cflags=-I/home/w495/ffmpeg_build/include --extra-ldflags=-L/home/w495/ffmpeg_build/lib --bindir=/home/w495/bin --extra-libs=-ldl --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-x11grab
    libavutil      54. 20.100 / 54. 20.100
    libavcodec     56. 26.100 / 56. 26.100
    libavformat    56. 25.101 / 56. 25.101
    libavdevice    56.  4.100 / 56.  4.100
    libavfilter     5. 11.102 /  5. 11.102
    libswscale      3.  1.101 /  3.  1.101
    libswresample   1.  1.100 /  1.  1.100
    libpostproc    53.  3.100 / 53.  3.100
    Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/w495/Video/15sec.nr.mp4':
    Metadata:
        major_brand     : isom
        minor_version   : 512
        compatible_brands: isomiso2avc1mp41
        encoder         : Lavf54.63.100
    Duration: 00:00:15.08, start: 0.042667, bitrate: 728 kb/s
        Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 595 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
        Metadata:
        handler_name    : VideoHandler
        Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
        Metadata:
        handler_name    : SoundHandler

## About FFmpeg

    [w495@w495yb ~]$ ~/bin/ffmpeg -version
    ffmpeg version 2.6 Copyright (c) 2000-2015 the FFmpeg developers
    built with gcc 4.8.3 (GCC) 20140911 (Red Hat 4.8.3-7)
    configuration: --disable-static --enable-shared --disable-doc --extra-cflags=-I/home/w495/ffmpeg_build/include --extra-ldflags=-L/home/w495/ffmpeg_build/lib --bindir=/home/w495/bin --extra-libs=-ldl --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-x11grab
    libavutil      54. 20.100 / 54. 20.100
    libavcodec     56. 26.100 / 56. 26.100
    libavformat    56. 25.101 / 56. 25.101
    libavdevice    56.  4.100 / 56.  4.100
    libavfilter     5. 11.102 /  5. 11.102
    libswscale      3.  1.101 /  3.  1.101
    libswresample   1.  1.100 /  1.  1.100
    libpostproc    53.  3.100 / 53.  3.100
    [w495@w495yb ~]$ 

May be I have problem with my ffmpeg build, but all except pyav works fine.
Is it a case for new Issue for PyAV?

**Comment by mikeboers** [comment]
I don't have an immediate answer for the first issue you were having, but my first guess would be a very old Cython. You do also have two versions of FFMpeg, and I honestly can't imagine what that would do. :stuck_out_tongue: 

As far as I know, we support both FFmpeg and LibAV for all versions since late 2012 (so ~0.8 for FFMpeg).

I've updated the basic demo in the docs to reflect the current API, but yours does work find (although I would swap `type` for `isinstance`).

**Comment by mikeboers** [comment]
I don't want to install Pillow or PIL with PyAV, since it is not necessary, and there is the strangeness that comes with that fork. I'll make a new issue about it though.

**Comment by w495** [comment]
> You do also have two versions of FFMpeg
I have 4 different builds of ffmpeg, and one more from conda. 
PyAV works fine with conda's build, and ignores others.

**Comment by danielballan** [comment]
@mikeboers Yes, I agree that packaging PIL or pillow as a requirement in the conda package would be problematic. Conda has no notion of optional dependencies.

@w495 If you are running PyAV in the conda environment, it is linked against the conda-installed FFmpeg and will definitely ignore all others.
