### ISSUE TITLE
Warn if there is no PIL/Pillow

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#91]
From #90, people expect to get PIL/Pillow as a dependency, so we should at least warn at the end of the build output if it is not there.

**Comment by mikeboers** [comment]
This should also be the case for numpy.

**Comment by jlaine** [comment]
I'm not sure we actually need to do anything here, PIL / Pillow is really optional and if you decide to use it without installing it, the import failure is pretty clear.
