### ISSUE TITLE
Tag v0.2.3 for the sake of packaging?

### ISSUE THREAD

**Issue by danielballan** [mikeboers/PyAV#99]
@mikeboers I noticed the v0.2.3 version bump. You are probably aware that v0.2.2 does not build correctly on Python 3 because of the minor issue you fixed in 40b3cb. Therefore, my conda builds are based on v0.2.2.post56. Would you tag v0.2.3 as a release so I can package a stable version?

**Comment by mikeboers** [comment]
My mistake to miss that; it is done now!
